### ISSUE TITLE
Phone's calendar data push

### ISSUE THREAD

**Issue by GreatApo** [AmazMod/AmazMod#10]
Provide an API to push Calendar events to the watch

**Comment by Paxy** [comment]
+1 for this request, so we can use @GreatApo great calendar widget (https://github.com/GreatApo/AmazfitPaceCalendarWidget) with our google calendar.

**Comment by GreatApo** [comment]
Commit 4540217e9fb5ae41c78ebc2f34ec43b7ab7c2c3d

We still need some options and some adjustments.
Additionally, the first project using the data is [here](https://github.com/GreatApo/Amazfit-Timeline-Widget).
