### ISSUE TITLE
Missed Call notifications.

### ISSUE THREAD

**Issue by GrinFactor** [AmazMod/AmazMod#104]
Missed Call notifications would be a great feature

**Comment by lfom** [comment]
Amazfit already sends call notifications to watch, so it's obvious that you are notified about calls. And probably it's already possible, as @fcaronte noted on XDA:

<For missed call notification on my Samsung seam to need to active the notification for "contact" app and not "telephone">. So I vote for closing this one.

**Comment by GrinFactor** [comment]
As you wish. I just feel that the end user does not know about the "need to active the notification for "contact" app and not "telephone". Is it not possible for Amazmod to request those permissions when installed?

**Comment by lfom** [comment]
It's optional, and not essential as you already get the call notification. This can be added to FAQ later.

**Comment by edotassi** [comment]
Can be closed?

**Comment by lfom** [comment]
Info added to FAQ.

**Comment by fcaronte** [comment]
we have again problem with missing call notification, i receive the the "amazmod welcome" notification istead of missed call notification. here the two log one filter "amazmod" and other "amazmod | noti" and have a null point to here
[filter- amazmod.txt](https://github.com/AmazMod/AmazMod/files/3144358/filter-.amazmod.txt)
[filter amazmod, noti.txt](https://github.com/AmazMod/AmazMod/files/3144359/filter.amazmod.noti.txt)
![33a438dc-697a-49ae-b272-e8b1d6965c62](https://user-images.githubusercontent.com/26366403/57179109-425d7f80-6e7a-11e9-9739-c23fae354691.jpg)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Missed Call notifications.](https://trello.com/c/Ckz6CEma/8-missed-call-notifications)

**Comment by fcaronte** [comment]
now seem to work correctly on last dev branch, if need we can reopen.
