### ISSUE TITLE
Custom notifications only for certain apps

### ISSUE THREAD

**Issue by airainchoc** [AmazMod/AmazMod#113]
Would be nice to be able to use custom notifications only for certain apps. 

ATM answers don't work on SMS, so i'd like to be able to use standard notifs for it, but Gmail don't show body on standard, so i'd like to use custom for it

**Comment by diotto** [comment]
It would be great, but a workaround is to set some apps to notify with Amazfit Watch and others with Amazmod. I am doing this.

**Comment by diotto** [comment]
Using Stock Amazfit Watch notification + Amazmod makes this possible.
