### ISSUE TITLE
"Find my phone" feature

### ISSUE THREAD

**Issue by rastaboo** [AmazMod/AmazMod#149]
I think it could be great to add the option for "find my phone" action to the hardware button.
I used this feature on my bip with the Amazfit Tools app and it seemed very comfortable and useful.

**Comment by lfom** [comment]
How does it work with BIP?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rastaboo** [comment]
Through the Amazfit Tools app
Here's the article:
[http://help.amazfittools.com/knowledge_base/topics/button-control-amazfit](url)

**Comment by lfom** [comment]
Thanks. I think it works with these devices because it sends the button presses directly to phone, but on Pace/Stratos we'd have to add a listener for the actions... Maybe this can be added after the watch is unlocked, so no wake-locks are needed?

**Comment by rastaboo** [comment]
Sounds reasonable. You mean unlock the watch with the top button and double press the bottom one to perform the action?

**Comment by lfom** [comment]
I am thinking about something that would work with either Pace or Stratos...

**Comment by edotassi** [comment]
@rastaboo yes, wake lock prevent cpu standby

**Comment by rastaboo** [comment]
ok, I just found out that physical buttons are always busy with navigational functions while the watch is on.
Correct me if I'm wrong, it doesn't seem right to override the navigation control to implement "Find the phone" function.
Is there a chance to assign it to double press (on a turned on watch)?

**Comment by diotto** [comment]
We already have a native "Find my Phone" in Watch. Maybe just a shotcut for it in Widget ?

**Comment by fcaronte** [comment]
I decompiled the java file of stock "find my phone" feature, I put here because i don't know nothing of coding and on the right hands could be useful

[Find.My.Phone.tar.gz](https://github.com/AmazMod/AmazMod/files/2814154/Find.My.Phone.tar.gz)

**Comment by dibg** [comment]
i also wish for this future to come to true. I also asked from xiaomi for more mapping options in the watch a while ago. Nothing happened so we are on our own.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Find my phone" feature](https://trello.com/c/GGnwgtzj/9-find-my-phone-feature)

**Comment by 1immortal** [comment]
closing due to irrelevance
