### ISSUE TITLE
Make settings consistently named not using enable and disable mixed

### ISSUE THREAD

**Issue by daenny** [AmazMod/AmazMod#173]
The settings screen is very confusing. It should always just state the feature, i. e. " turn on screen on notification" and the toggle shows its status.
Especially using "Disable Xxx" and "Enable Xxx" mixed in the settings screen is very confusing.

**Comment by diotto** [comment]
I'm not sure if the best option is to keep only "Disable" or "Enable" in preferences.
For example: "Enable Custom Replies" would be changed to "Disable standard replies" (very similar to the above option "Disable standard notifications")  ? It would confuse even more.

**Comment by daenny** [comment]
I think that you misunderstood my complaint. This is how it is now:
![screenshot_amazmod_20181115-094058](https://user-images.githubusercontent.com/3392004/48540590-c61ab400-e8ba-11e8-9b25-b74ee28ff803.png)
 
I would propose:
![screenshot_amazmod_mod](https://user-images.githubusercontent.com/3392004/48540889-961fe080-e8bb-11e8-9217-031bdf3a039c.png)

Similarly I would keep "Enable Custom Replies". But call the "Disable standard notifications" something like "send standard notifications" (and invert the default value again)

Because enabling a toggle to disable something is very counter-intuitive.

**Comment by daenny** [comment]
@diotto what do you think?

**Comment by GreatApo** [comment]
BUMP

I totally agree. We have to look into this.

**Comment by GreatApo** [comment]
So, to get this going, I propose these changes. Please have a look and provide feedback. We are also interested in letting us know what options are not clear enough, so we can provide a better description.

![settings-changes](https://user-images.githubusercontent.com/9620510/55422193-fe254980-5572-11e9-8c23-d2f6619572eb.png)

**Comment by diotto** [comment]
For me they are ok @GreatApo!
What do you think @daenny ? It's what you were asking for? Suggestions?

**Comment by daenny** [comment]
Thanks for looking into this again. The proposed changes look good for me. That would make it a lot clearer :+1:

**Comment by GreatApo** [comment]
First simple part done. All options that didn't require an inversion were fixed.
Commit: 87335f0c7c677ce98391915ea0f50d1dfabce566

Next step is to fixe the remaining 3 options that also require new id names (to avoid old user settings been used) and inversion of the booleans in the code.

**Comment by GreatApo** [comment]
Commit: 77869ec9d693a9681b20646005ef8e2d25921c26
 
The following settings where inverted:
- Disable Notifications -> Push Notification
- Disable delay -> Reply Delay
- Disable when screen is on -> Send when screen is on

All done. Issue will close while we wait for feedback.
