### ISSUE TITLE
WIP - GreatFit implementation

### ISSUE THREAD

**Issue by GreatApo** [AmazMod/AmazMod#178]
I am going to gather all the work/features that have/can be done concerning the implementation of GreatFit in Amazmod. We have 2 different groups.

1. Transport various data to watch. These are the data that have to/can be transfer to watch in order to show them as watchface elements/widgets. The first 3 are the most wanted. If you have an other idea let me know.
- Phone's battery
- Phone's alarm
- Notifications / Phone calls count
- Sunrise, Sunset, tide
- Better weather data (we can overwrite system's weather data with other more accurate)

I have already coded the first 2 [here](https://github.com/GreatApo/AmazMod)
The settings for the above should be something like this:
![image](https://user-images.githubusercontent.com/9620510/44997369-6cdafe00-afb6-11e8-8004-421aedf953d1.png) The interval is already working.

2. Watchface settings. GreatFit is almost ready to became something like Facer. Two things need to be send to watch: images (we can save them to SD in a specific folder, this is not ready in GreatFit) and position/color settings. We should start from providing some default watchfaces and maybe load other from XML, setup a server or just load images and positions.
![image](https://user-images.githubusercontent.com/9620510/44997298-eaead500-afb5-11e8-98e6-15fa995d8c2c.png)
The data have to be transported directly to GreatFit and not amazmod service so the app saves the data to its shared preferences.
The user should be able to select a watchface, change it's settings if he wants (colors, widgets, features) and then load it to the watch. As a preview, most watchface settings can be seen in [this xml](https://github.com/GreatApo/GreatFit/blob/master/app/src/main/res/values/arrays.xml)

There should also be some options that concern all the watchfaces like target calories, target floors, age, step length (to convert steps to distance) and some of the features (see GreatFit's option menu).

Conclusion:
These are all ideas. What we can code depends on our free time.

**Comment by domsle** [comment]
I really like these ideas. What I would love to see on my watch is something like a rain alert, so I would be able to see whether it is going to rain today, with some % of probability (most providers give this info). Currently I can see that it is sunny now, but have no idea what it is going to be later.

**Comment by GreatApo** [comment]
@domsle that sounds like a notification. Please copy your post and open a new issue!

**Comment by MetalGearSolidNerd** [comment]
Is it possible for Amazmod to support Tasker Actions (https://tasker.joaoapps.com/plugins-intro.html) ?

Basically Amazmod would implement a Tasker Action which could be used to send custom data to a supporting watchface. Probably GreatFit could implement such a custom widget.

Tasker (Data) > Amazmod > Watch > GreatFit watchface (custom widget)

This would be similiar to "[Canvas for Pebble](https://pebblecanvas.blogspot.com/p/user-guide.html)" implemntation.

**Comment by GreatApo** [comment]
@MetalGearSolidNerd from what I understand, canvas for pebble is a way to make a custom watchface. It could be possible to make a watchface and move your widgets.
Let's just make it work firstly and we can later try to add more options.

**Comment by MetalGearSolidNerd** [comment]
@GreatApo Thank you for your response.

My request was more inclined towards a customized widget that can be fed data through Tasker rather than a customized watchface itself. For e.g. 1) We choose to display "tasker" custom widget on GreatFit watchface 2) This widget will be updated by data provided from Tasker 3) The watchface itself would only need to render data send to it through Tasker as is 4) Data sent from Tasker could range from stock prices parsed from websites to even custom weather scrapers

GreatFit is good as it is and will be looking forward in the future for further enhancements.

**Comment by GreatApo** [comment]
@MetalGearSolidNerd oh ok, now I got it :)

As far as GreatFit is concerned, it is quite easy to code it, given what we have now :D

I don't know how that data could be fetched from Tasker. I guess that is possible...

**Comment by giuliovale** [comment]
@GreatApo Not sure if this https://tasker.joaoapps.com/plugins-intro.html about @MetalGearSolidNerd request

**Comment by GreatApo** [comment]
@giuliovale yeah he has a link in his first reply.

Anyway guys, lets make the basic work and we can look into that later. Its already a mountain to code.

**Comment by giuliovale** [comment]
@GreatApo sorry  my fault.

**Comment by GreatApo** [comment]
Just a small update, calendar data are now forwarded.
Still missing:
- Sunrise, Sunset, tide
- Better weather data (we can overwrite system's weather data with other more accurate)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GreatFit implementation](https://trello.com/c/EJvPLsC6/11-greatfit-implementation)

**Comment by 1immortal** [comment]
Another idea that some user pointed out, that can be a nice addon:

- ability to track stocks - we can use https://blog.rapidapi.com/how-to-use-the-yahoo-finance-api/ , but it will require changes and addition to the GreatFit watchface
