### ISSUE TITLE
Notification about battery stats for charging

### ISSUE THREAD

**Issue by marek9336** [AmazMod/AmazMod#182]
Hi, can you add notification (to phone) about low battery  for example when i have under 35% (or custom)? It can be very cool  :)
Thanks Marek

**Comment by caiorrs** [comment]
more details on it. A friend of mine suggested to notify when the phone battery is at 15,10 and 5% (when discharging), and 90,95 and 100% (when charging). He said that the app Notify does that.

**Comment by marek9336** [comment]
I thought the percentage of the watch watches would be a notification on the phone. I have a watchface without a battery and warn me of my watch up to 15%, which will discharge within a few hours and turn off. My vision is to set the percentages in the phone in the apps that when 40% of the watch battery shows on the phone a notification that the watch has a 40%> watch on the watch

**Comment by lfom** [comment]
@marek9336 yes, it makes sense.

@caiorrs this would drain some battery, maybe it should be an option if you are using GreatFit as it syncs phone data anyway...

@GreatApo Check this please.

**Comment by GreatApo** [comment]
To sum up, 2 notifications are needed:
- Battery of phone (notification at watch)
- Battery of watch (notification of phone)

**Comment by GreatApo** [comment]
First attempt done: commit 471a76513a0852b6a49149d53e75b7b8734cc441
