### ISSUE TITLE
Adding new language?

### ISSUE THREAD

**Issue by skubi23t** [AmazMod/AmazMod#20]
Hi,

If I share you strings for polish language. Will you add it to apk?

**Comment by Kaudii** [comment]
Welcome. I am the author of the translation of the Amazfit Watch application into Polish on Android, I attach the PL files, although not everything is fully translated yet, but when added to your application, most are in my language. Soon I will finish the translation of the files and add them here.


[values-pl.zip](https://github.com/edotassi/AmazMod/files/1934920/values-pl.zip)

**Comment by edotassi** [comment]
@Kaudii could you do a pull request?

**Comment by edotassi** [comment]
@Kaudii can you send them by tomorrow?

**Comment by skubi23t** [comment]
What is going on with that? :)

**Comment by Kaudii** [comment]
Some family problems, some more, but everything is back to normal, so I will give you these files soon.

**Comment by Kaudii** [comment]
You can tell me why you and AmazMod in your days and months are displayed in the language of the system, in my case in PL, and how I do it is always EN, what to change in the application would be like you

**Comment by the4anoni** [comment]
@edotassi 
I dm'ed you on crowdin

**Comment by edotassi** [comment]
@the4anoni ok i will check

**Comment by the4anoni** [comment]
@edotassi Did you got PM ? If no I said that I can't choose Polish from languages to translate
My nickname is the same as on github.

**Comment by edotassi** [comment]
@the4anoni check now 😃

**Comment by Eyaloh** [comment]
Hi, can you add Hebrew language to amazfit 2?

**Comment by GreatApo** [comment]
> Hi, can you add Hebrew language to amazfit 2?

No, this is Amazmod.

Anyone interested in translations head to our [crowdin page](https://crowdin.com/project/amazmod)
