### ISSUE TITLE
Add "Missed notifications" notification when re-connecting to phone

### ISSUE THREAD

**Issue by Raspel16278** [AmazMod/AmazMod#250]
It possible to add function for missed notifications and calls? When I recieve mail, sms,... long distance from phone and after a time I come back to phone.

**Comment by lfom** [comment]
It's not clear what you want... Do you want AmazMod to queue notifications on phone when the watch isn't connected and then send them to watch when it re-connects? How would it be better than just check for notifications on phone (what you'd have to do anyway)?

**Comment by Raspel16278** [comment]
Yes, you ha a right. This will be great.

I dont check telephone everytime, when I come back. So you will be informed immediately, not after a while, when you check your phone. You dont miss a calls, messages...

 

BR

 

Rasto

**Comment by lfom** [comment]
I don't think it's useful, since you may have 1, 2 or dozens of missing notifications on your phone. But maybe add a notification when watch reconnects saying that there are pending notifications on phone is enough?

**Comment by lfom** [comment]
Title changed: the idea it to check if there are pending notifications when the watch re-connects to phone.

**Comment by lfom** [comment]
It was added to dev branch, but it's not instantaneous (check is done about every 2min to save battery).
