### ISSUE TITLE
Please provide the ability to receive notifications with actions

### ISSUE THREAD

**Issue by phys** [AmazMod/AmazMod#259]
Does the AmazMod provide the ability to receive notifications with actions from any Android apps?

**Comment by edotassi** [comment]
at the moment no

**Comment by lfom** [comment]
Adding for a future milestone (I think it's possible).

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Please provide the ability to receive notifications with actions](https://trello.com/c/cGplgP5H/13-please-provide-the-ability-to-receive-notifications-with-actions)
