### ISSUE TITLE
Transfer files via WiFi

### ISSUE THREAD

**Issue by edotassi** [AmazMod/AmazMod#260]
@lfom  suggested to transfer the apk file through wifi using adb.

this issue is to track and discuss this feature

**Comment by lfom** [comment]
Not only apk, you can push any files and install apk's directly using adb via WiFi, only watch's IP is needed (and keep it active).

**Comment by lfom** [comment]
Anyway, if we can enable the wifi Hotspot on watch like Huami does for file transfer it will allow adb as well as much faster and reliable file transfers (at the expense of more battery drain, of course, but as it may be quicker than maybe it's still better).

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transfer files via WiFi](https://trello.com/c/5OC1zwml/14-transfer-files-via-wifi)

**Comment by 1immortal** [comment]
bumping due to much higher relevancy

**Comment by GreatApo** [comment]
Quick update:
FTP file transfer from phone to watch now works for Android 9 and under (commit c19cb0e9f68547430da8c038675e83a530ce1b6e)

**Comment by GreatApo** [comment]
You can now enable/disable the FTP server from the Tweaking menu (Commit 0f9dbec89699a09d22c78a318abb26e2378af53f). Here is how you can transfer files from any device in the same network:

1. Connect to a network from watch's Settings->Connect->WiFi
2. Enable FTP server from Amazmod's tweak menu
3. Watch local IP and port will be shown (if you miss it, click the get local IP button, FTP port is always 5210)
4. Connect to watch from a device in the same network. If you want to download files, you can connect from a browser with a URL like this: ftp://192.168.1.1:5210 (change the IP based on your watch's local IP). To upload files you can use an FTP software.

**Comment by GramThanos** [comment]
Keep in mind that FTP support will be removed from major browser in the near future.

**Comment by 1immortal** [comment]
This works on PACE/Verge/Stratos and works horribly on S3, and it will probably remain like that.
