### ISSUE TITLE
Error in APK installation function from file explorer

### ISSUE THREAD

**Issue by diotto** [AmazMod/AmazMod#264]
After i select"Install" in any apk using file explorer i receive an error that the command failed.
After some waiting I can see that the APK is installed in Watch but the bluetooth connection between watch and phone is lost (with both Amazmod and Amazfit Watch)
Restarting the watch restore connection.

**Comment by lfom** [comment]
The problem was caused by a git translation between macOS and Windows files in the install apk script. If anyone wants to build their own version on PC, they must disable this feature in Git client installation.
