### ISSUE TITLE
Heart rate graph in main screen

### ISSUE THREAD

**Issue by GreatApo** [AmazMod/AmazMod#268]
Within WatchStatus data we can include the last heart-rate measurements and create a simple graph in the main screen. Maybe with an on/off option.

Data are available at:
```
// ADB
adb shell content query --uri  content://com.huami.watch.health.heartdata

// JAVA
public static final Uri CONTENT_HEART_URI = Uri.parse("content://com.huami.watch.health.heartdata");
paramContext = paramContext.getContentResolver().query(CONTENT_HEART_URI, null, null, null, "utc_time DESC LIMIT 1");
```

**Comment by GreatApo** [comment]
Commit 6d0c9677919d186658eb962d3f47b99c885cb32d

![7bb04dd6-1d84-4ce4-bcae-a90f1998187b](https://user-images.githubusercontent.com/9620510/55646774-f57f7e00-57d3-11e9-838d-ad571affb794.jpg)

**Comment by banhegyinorbert** [comment]
Hello GreatApo,

I love this chart. How can I implement?

thanks, 
Norbi

**Comment by GreatApo** [comment]
It will be available in the next release. You can compile the Dev version with android studio if you want it now, however, updates won't work for you afterwards.

**Comment by banhegyinorbert** [comment]
It looks amazing!!! When the update is supposed to come?
One more thing. How can I pull the HR data from app or the watch? I'd like to use it in Tasker, by receiving it as an intent and use it in a custom notification.
Thank you so much!

**Comment by GreatApo** [comment]
As in the current state, you can't do so. You need to edit the code.

**Comment by banhegyinorbert** [comment]
I would gladly subscribe as a tester! :)

**Comment by GreatApo** [comment]
You can do that from here: https://play.google.com/apps/internaltest/4697278970051666108
