### ISSUE TITLE
Download not working in file explorer

### ISSUE THREAD

**Issue by diotto** [AmazMod/AmazMod#285]
The download function is not working. When I try to download some file it freezes up after one or two seconds

**Comment by lfom** [comment]
I haven't had any issues, this can be closed?

**Comment by fcaronte** [comment]
For me is working too. The only download is not working is the folder download but probably is not implemented, and workaround is to compress it and then download the .tar.gz file

**Comment by GreatApo** [comment]
A user on XDA (cesareogallego ) also faced this problem. Here is the log he provided.
[log.txt](https://github.com/AmazMod/AmazMod/files/3109112/log.txt)

**Comment by fcaronte** [comment]
Me too, and appended when download screenshot too (not everytime)

**Comment by fcaronte** [comment]
this is what have when download is stuck
![image](https://user-images.githubusercontent.com/26366403/56692175-e52b3680-66e1-11e9-87a5-6e0c89f6cfa5.png)

**Comment by fcaronte** [comment]
do you think add a status bar notification when download start could help to avoid stuck? on file upload we have the notification and seem to work better

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Download not working in file explorer](https://trello.com/c/CrTsbW1G/15-download-not-working-in-file-explorer)

**Comment by sylas** [comment]
Unfortunately, I encounter the same bug - downloads stop in some random moments. Log attached.
[logcat.txt](https://github.com/AmazMod/AmazMod/files/3219557/logcat.txt)

**Comment by Damien-G38** [comment]
Same problem here. Unable to download a file. There are 2 scenarios : either it freezes during the process, or the process is completed but the file is corrupted.

**Comment by fcaronte** [comment]
seem to work correctly on last dev branch. For now we can close.
