### ISSUE TITLE
button to answer the call

### ISSUE THREAD

**Issue by fosiczka** [AmazMod/AmazMod#312]
Please add the option to accept the call. Some bluetooth handsfree doesn't have a hardware button to answer a call, my watch would make my life easier :-) 

Thanks

**Comment by lfom** [comment]
Probably it won't happen, for two reasons:
1. Call notification are handled by Amazfit app itself, not AmazMod;
2. It would require permission to make calls probably, what it's desirable.

**Comment by N73dp** [comment]
Yep,just answer would be awesome, i always use bt headphones
