### ISSUE TITLE
notification offset delay manual control

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#322]
on some setups with some watches and phones, there is a visible delay with the stock notification, if enabled, and the custom UI one.
is it possible to add a user-controllable bar to the settings, that will control the actual delay time for the settings, like the backlight bar?

**Comment by diotto** [comment]
I vote we have our own notification drawer and stop generating standard notifications (except user prefers using only, without custom notifications).

**Comment by diotto** [comment]
Now that we have Amazmod own notification drawer, do we still need to have Standard + Custom UI notificiations ? Couldn't standar notifications be configured in Amazfit Watch App and Amazmod basically for Custom UI ?
Is this still an issue @1immortal ?

**Comment by lfom** [comment]
@diotto Yes, standard notifications are still needed, stock Amazfit app doesn't do a good job, so AmazMod adds a lot of features, and still it's an option for those who don't want to install service app on watch.

**Comment by 1immortal** [comment]
I think that the original issue can be closed, there's no logic in that, now that I think of that.
The reasonable and logical thing is to use Custom notifications or the stock ones, not both.
