### ISSUE TITLE
Hiding group messages. 

### ISSUE THREAD

**Issue by yener90** [AmazMod/AmazMod#331]
Hello,

Could you add a feature to remove group messages (for exampls whatsapp) for notifications? I cam from Huami Bip and that had this feature. 

I only want important messages on my watch. On my phone the group messages should be still shown. But not on my watch. 

Regards yener90

**Comment by lfom** [comment]
Latest dev builds (unreleased) have a filter feature, probably it does what you want? You can filter out notifications based on title/message text filters.

**Comment by yener90** [comment]
Yes thats exactly what I want. When we expect with release?
