### ISSUE TITLE
Persistent notification

### ISSUE THREAD

**Issue by zeromentu** [AmazMod/AmazMod#332]
After three file upload there is a persistent notification

**Comment by lfom** [comment]
What phone model and Android version? I tried here, with persistent notification on, and I see a notification about the file transfer, and I can dismiss it manually, so what do you think is the issue actually?

**Comment by zeromentu** [comment]
Im using mi 8 with miui10 pie.
The problem is after the file transfer is complete, it says it's 100%, however that notification of can't demiss it, need to reboot to make it disappear

**Comment by lfom** [comment]
Any dev seeing this? I have never seen this issue here...
@diotto @GreatApo @fcaronte @1immortal

**Comment by fcaronte** [comment]
Usually a hide completely the amazmod and amazfit persistent notification and so I usually not see any notification of transfer, but I try to enable notification and send more file in one time and more file one to one and the notification can be dismissed with a swipe and so for me on android 8 Samsung is work correctly

**Comment by diotto** [comment]
Couldn't reproduce here, Stock Android 8 (Moto G4)

**Comment by 1immortal** [comment]
Verified on Android 7.1.1, with 1.1.3.1 debug app. Sent the service apk to the watch, file copied successfully, notification regarding![](https://i.imgur.com/beVjmhI.png) the upload remains. Please see attached ss.

**Comment by diotto** [comment]
@1immortal did the notification stayed persistent or can you dismiss it?

**Comment by 1immortal** [comment]
i could dismiss it, its not there for life.

**Comment by diotto** [comment]
> 
> 
> i could dismiss it, its not there for life.

So there is no bug for you. The notification was supposed to stay there (but not persistent).
@zeromentu do you still have this problem with current release (1.1.3) ?

**Comment by zeromentu** [comment]
Well it seems to work fine on the current versions, I would consider this as fixed
Thanks for all your help

**Comment by diotto** [comment]
So i'm closing the issue :smiley:
