### ISSUE TITLE
Messenger issue

### ISSUE THREAD

**Issue by vibecatalin** [AmazMod/AmazMod#333]
Hello!
With the latest versions of Amazmod on Facebook messenger I get the first notification repeated.
I have Ungroup settings Enabled, and tried Messenger Light unfortunately has the same problem.
I will attach logcat and screenshot
Thanks!
[logs-2018-12-21-14-56-25.zip](https://github.com/AmazMod/AmazMod/files/2702993/logs-2018-12-21-14-56-25.zip)

![screenshot_20181221-145734_amazmod](https://user-images.githubusercontent.com/46049190/50345837-111e8b80-0539-11e9-85d9-447a136e8975.jpg)

**Comment by fcaronte** [comment]
@lfom is the bug you try with me? Right? New dev should fix this

**Comment by lfom** [comment]
This bug is present in the current release version, but was fixed a long time ago, I think it's included in the current beta version being tested... FB Messenger changes a lot each version, sometimes this break things in AmazMod. I could care less, as I don't use it...

**Comment by GreatApo** [comment]
Messenger seems to work fine on dev channel.

I close this, please re-open if there is still a problem in the next release.
