### ISSUE TITLE
Recorder Widgets - AmazModService Duplicates

### ISSUE THREAD

**Issue by BuStRaMa** [AmazMod/AmazMod#336]
Problem:
![photo5913226968323699154](https://user-images.githubusercontent.com/5473557/51392582-1ffb5c80-1b3e-11e9-8ec5-8d73eaea1bde.jpg)

How to recreate: 
1. Enter AmazMod's Widget
2. Choose settings -> Recorder Widgets
3. Uncheck Sports and exit
4. After entering again AmazModService getting duplicates

Logcat: 
[amazmod.txt](https://github.com/AmazMod/AmazMod/files/2773288/amazmod.txt)

**Comment by lfom** [comment]
What version are your using? It should be fixed in the dev branch as of now...

**Comment by BuStRaMa** [comment]
Application ver. 1.1.0
Service ver. 1838

**Comment by fcaronte** [comment]
Yes I confirm on dev branch work correctly 👍

**Comment by lfom** [comment]
> Application ver. 1.1.0 Service ver. 1838

If you are using your own builds from dev branch, probably an older build caused the problem. To fix this in the latest builds, you must clear service's data and erase the system property "springboard_widget_order_in", in this order. Both can be done using adb. But it's just a cosmetic issue...
