### ISSUE TITLE
Option to Disable JobScheduler (or discard notifications after some time disconnected)

### ISSUE THREAD

**Issue by diotto** [AmazMod/AmazMod#339]
If user is far from phone, watch if off or airplane mode is on in watch the notifications are being stored in a queue by JobScheduler.

When watch connects back lots of notifications arrive in it.

We may define a max age for notifications to be stored in queue, maybe allow it as a preference?

**Comment by GreatApo** [comment]
An other approach/bug/improvement is to remove the scheduled notification if you remove it (seen or swiped from phone).

I am on Dev channel (notifications remove not working) in case it is fixed.
