### ISSUE TITLE
After update Amazmod 1.1.0

### ISSUE THREAD

**Issue by pitchayasht** [AmazMod/AmazMod#347]
After update Amazmod 1.1.0 Notification is Back to Standard UI

Can I change notification to Custom UI ?

**Comment by pitchayasht** [comment]
preferencea on my watch right?

**Comment by jaimeescano** [comment]
I got the update too, but it seems the "watch-service" didn't update (yet). So I guess we should wait until the watch component get updated too.

Currently I have phone app version 1.1.0, with watch-service version 1702.

**Comment by pitchayasht** [comment]
After update service today everything is ok
thank you fir hard work

**Comment by fcaronte** [comment]
probably only need to restart bot phone and watch

**Comment by pitchayasht** [comment]
Thank you after restart both everything ok
