### ISSUE TITLE
Does not update service apk in watch

### ISSUE THREAD

**Issue by ega6226** [AmazMod/AmazMod#356]
Hi,

When I open the application it appears that there is an update. I accept, and start transmitting.

when it is finished, it says that a message will appear on the clock, but nothing appears.

Regards

**Comment by ega6226** [comment]
Hi,
I tried to uninstall the service from AMAZFIT TOOL, but I get this message:
Uninstalling com.amazmod.service ...
Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]

**Comment by fcaronte** [comment]
1. Make sure you have app 1.1.0 on phone and service 1702 on watch;
2. Open widget on watch, tap on hold on the logo, you should see a scrolling menu;
3. Search for "Revoke Admin" and tap it, if it worked you should see a toast (message) on watch screen saying it was "disabled";
4. Uninstall

**Comment by diotto** [comment]
Uninstall is probably not needed. After "Revoking Admin" (steps suggested by @fcaronte ) you can try to update again, probably with no issues now.

**Comment by ega6226** [comment]
thanks, everything perfect

**Comment by fcaronte** [comment]
perfect, so you can close with bottom right button
