### ISSUE TITLE
Amazmod 1.1.0 breaks APK handling 

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#357]
When installed, in some applications, when trying to install an apk, nothing happens.
does works when AmazMod removed

**Comment by 1immortal** [comment]
https://youtu.be/xJynW5K9NY4

**Comment by fcaronte** [comment]
probably after reinstall is work again, because i think you have set as default ( i don't know what say the bottom text )

**Comment by diotto** [comment]
Probably it's what @fcaronte said. Already reinstalled?

**Comment by lfom** [comment]
Simply don't make AmazMod the default app to handle APK packages, duh...

**Comment by 1immortal** [comment]
cannot reproduce anymore
