### ISSUE TITLE
Reject call phone call and send SMS

### ISSUE THREAD

**Issue by GreatApo** [AmazMod/AmazMod#359]
Feature suggestion by Petar Bojovic (Amazfit Facebook group)

Call reject feature with customized SMS.
It would be great if you can add a future to reject call and automatically send SMS with pre-defined context.

**Comment by lfom** [comment]
Amazfit deals call notifications, and it's very aggressive doing it, it's not even possible to disable this without freezing Amazfit... And even if it's possible, it would request a lot of permissions that aren't desirable and would probably block publishing app on PlayStore.
