### ISSUE TITLE
Message history not working

### ISSUE THREAD

**Issue by Disturbedbcn** [AmazMod/AmazMod#360]
Hi everyone,

The new message history in amazmod launcher is not working. When I receive a message and want to consult it in the history, amazmod service is closed. Then I enter again and no messages are shown, is always empty (and the counter number is showing more messages that I have).
There's any workaround to solve this? Thanks.

**Comment by diotto** [comment]
Hello, Are you using custom UI notifications or standard only?

**Comment by Disturbedbcn** [comment]
I've tried both options, the service is always stopping.

**Comment by davigar1391** [comment]
I have the same problem. When i want to consult the notifications, amazmod service is closed. I tried to reset the watch to factory defaults and reinstall everything and I still have the same problem. My watch is a Stratos with 2.3.7.0 version.

**Comment by davigar1391** [comment]
I have made a logcat

[log.txt](https://github.com/AmazMod/AmazMod/files/2825485/log.txt)

**Comment by lfom** [comment]
It is a firmware issue, it can't be fixed in AmazMod.

**Comment by davigar1391** [comment]
> It is a firmware issue, it can't be fixed in AmazMod.

Firmware issue of my mobile phone?
