### ISSUE TITLE
Auto Lock Screen Issue

### ISSUE THREAD

**Issue by fcaronte** [AmazMod/AmazMod#371]
I have a problem with the auto lock screen after receive a custom ui notification. after a reboot, the first notification is receive and scree lock correctly but after second one, the screen is not lock anymore

**Comment by fcaronte** [comment]
on version 1843 autolock work good with and without enable the setting to "disable screen on",
on new version autolock work only if you enable "disable screen on"

**Comment by diotto** [comment]
In version 1843 screen and backlight were turning off/locking together, independent if you dismiss or wait for timeout. In current dev this was not working, made a small change in dev to make it work again.
