### ISSUE TITLE
Forced closes on watch service

### ISSUE THREAD

**Issue by siriusblackhu** [AmazMod/AmazMod#372]
Hi, I am using Amazmod with 1760 service and CustomUI notifications for a long time without problems. Today I updated phone app to 1.1.0 version and the watch service to 1843 version and the service is force closing sometimes when I receive CustomUI notifications or always when I want to see the notifications history. 

I downgrade the app and service to the previous versions and all is working perfectly again. What is the problem?

**Comment by lfom** [comment]
How are we supposed to know if you don't give any technical information, not even the watch model and firmware, phone model and firmware, and a logcat? Github isn't meant for support, if you can't provide technical info, there are other channels for it...
