### ISSUE TITLE
Version 1843 can't be installed on the watch

### ISSUE THREAD

**Issue by ikemanet** [AmazMod/AmazMod#373]
Hi, today I opened the app on the phone and it said there was new version 1843. I have v1702 currently on the watch, it is not rooted, but after sending the apk, nothing was happened, then I tried installer with my laptop, it uninstalled 1702 and then restarted my watch then nothing happened. Please help me to check this issue. Thank you.

**Comment by GreatApo** [comment]
You don't has if the app uninstalls or not. Run the install from ADB and if there are not errors just let it run untill it finishes (may take 15min).

If you get an error, I would propose factory reset it the watch.

**Comment by 1immortal** [comment]
upgrade instructions:

1. Make sure you have app 1.1.0 on phone and service 1702 on watch;
2. Open widget on watch, tap on hold on the logo, you should see a scrolling menu;
3. Search for "Revoke Admin" and tap it, if it worked you should see a toast (message) on watch screen saying it was "disabled";
4. Now open AmazMod on phone and you should see a message about the service update, proceed to download and install;
5. After it is pushed to watch, you should see a confirmation of the update with a countdown.
If the launcher restarts after 5, it worked fine. If it gets stuck or you don't see the confirmation, use the File Explorer on AmazMod on phone to go to /sdcard/, find service-release-1843.apk, tap and hold on it and choose "Install".
If all that fails ... factory reset your watch, and install all from scratch :)

@lfom instructions
