### ISSUE TITLE
Message problem

### ISSUE THREAD

**Issue by Pali28** [AmazMod/AmazMod#374]
Hello. 

i have problem with messages for exp. in fb messanger. if someone send me "hello" watch show "hello" directly second message "how" on the watch "hello". so still only first message show on the watch....
+
widget on the first page on the watch not function... still end on the menu

thank you

amazmod service 1843
stratos rom 2.3.8.0
phone oneplus 6 / android 9

**Comment by lfom** [comment]
Hello. Both were fixed for the next release. This version took too long to be released so it has a few minor bugs. About the widget order, as a workaround, when it is reseted you can open the menu in AmazMod widget and choose Reorder Widgets item, this should make AmazMod the first widget again when you closes it.

**Comment by Pali28** [comment]
thank you for answer.
when will be available new release?

**Comment by diotto** [comment]
It's under beta testing. If no issues are found, next days.
