### ISSUE TITLE
Badge Indentifying app in notification

### ISSUE THREAD

**Issue by diotto** [AmazMod/AmazMod#375]
Create a small badge representing which app sent the notification. Right on the right lower corner of contact picture.
Example:
![Example](https://developer.android.com/images/ui/notifications/wear_2x.png)

**Comment by GreatApo** [comment]
Commit 43fea87c219b44b85891490af2c89951c406a0fc

@diotto can it be closed?

**Comment by diotto** [comment]
Sure!
