### ISSUE TITLE
ER: push swimming activity to Strava 

### ISSUE THREAD

**Issue by Wil63** [AmazMod/AmazMod#380]
As amazmod is here to do what is missing in the standard Stratos software, I would appreciate that my swimming pool activities were pushed to Strava.
It isn't the case, though it works fine for cycling and running. I am afraid it is the case for every indoor activities?

**Comment by lfom** [comment]
Planned, please see #50 (you can add suggestions there, if needed).

**Comment by Wil63** [comment]
Well, #50 is a functionality (if I well understood the request) that is already covered by the official mobile app "Amazfit Watch". For example, as soon as my outdoor bike activity is finished, it is created with the tracks in Strava. It is true that I don't know if it is possible for others like Runtastic...
But for indoor activities, like swimming in particular, the standard app is doing nothing. I have to create a manual activity in Strava, and copy the distance, duration ; that's why I was asking for this functionality.

**Comment by lfom** [comment]
No, #50 means exporting any activity to TCX so thet can be uploaded to any 3rd party service.
