### ISSUE TITLE
ER: phone notification during sport activity 

### ISSUE THREAD

**Issue by Wil63** [AmazMod/AmazMod#381]
I am wondering if I am the only one who needs it, sorry if it is the case.
When I am doing Mountain Bike in winter, my watch is under my warm clothes, I can not see the screen. I use my phone for the map, and sometimes I have alerts on my watch, which is vibrating,  like heart frequency, but I can't see it. It would be wonderful to push this alert to the phone, as an option, to be able to see it !

**Comment by lfom** [comment]
Let me try to understand what you want: you want to push activity notifications from watch to phone? If yes, there is a big problem: they are not notifications, and probably there is no way to "intercept" them so they can be pushed to phone.

Maybe, in the future, Amazfit watches will have an app like GhostRacer, they will record the activities by itself, so in this case we can use AmazMod to push notifications to phone...

**Comment by Wil63** [comment]
Yes you understood my need. I understand it can be complex to catch these notifications but maybe it is possible to read the notification history in the watch, as long as they are not deleted by the user.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ER: phone notification during sport activity](https://trello.com/c/uhGOxJht/17-er-phone-notification-during-sport-activity)
