### ISSUE TITLE
[REQUEST] 1880 Service APK

### ISSUE THREAD

**Issue by the4anoni** [AmazMod/AmazMod#389]
Hello
I need 1880 apk to install from pc to watch

It doesnt't install from Amazmod beta tried many times ,even waited 30 minutes.

**Comment by the4anoni** [comment]
Issue to close: APK was on Watch memory.


https://www38.zippyshare.com/v/Hyw1qdTp/file.html
If someone is having problems like me.

**Comment by lfom** [comment]
Current service APKs can be found here: 
https://github.com/AmazMod/AmazMod/tree/master/service-releases

**Comment by the4anoni** [comment]
Good to know this apk is on github
