### ISSUE TITLE
Remove firebase, migrate to tinylog and implement a crash report method

### ISSUE THREAD

**Issue by diotto** [AmazMod/AmazMod#390]
Remove firebase and implement tinylog logging to file. If possible catch exceptions and create an activity for reporting it (with stacktrace) sending log together (by mail, maybe)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactoring](https://trello.com/c/9k883sY1/3-refactoring)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove firebase, migrate to tinylog and implement a crash report method](https://trello.com/c/0g8pTucd/18-remove-firebase-migrate-to-tinylog-and-implement-a-crash-report-method)

**Comment by diotto** [comment]
Most Firebase classes were removed. Now we have some related to GMS (Continuation and Tasks) and still some calls to FirebaseAnalytics i think cannot be removed.

**Comment by lfom** [comment]
Removed all firebase events, kept ont Crashlytics for release builds. Tinylog is working great. Closing.
