### ISSUE TITLE
Remove unused classes / resources

### ISSUE THREAD

**Issue by diotto** [AmazMod/AmazMod#391]
We have lots of unused classes and resources. We can :

-Use android studio refactor to delete all u used files
- Configure Gradle to removed unused resources only from the build

**Comment by lfom** [comment]
I think the binaries are already streamlined when built, we just need to remove the unused classes that we are sure we won't use anymore...

**Comment by diotto** [comment]
I've read that it's necessary this in build.gradle (which we don't have, afaik) to streamline the build:

buildTypes { 
        release { 
             shrinkResources true 
        }
}

As it's not a big issue recovering deleted files I suggest we tag current code informing well remove unused resources and do a clean just using Android Studio refactor.

Details: https://stackoverflow.com/questions/6373482/remove-all-unused-resources-from-an-android-project

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactoring](https://trello.com/c/9k883sY1/3-refactoring)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove unused classes / resources](https://trello.com/c/nn7CjBEH/19-remove-unused-classes-resources)

**Comment by GreatApo** [comment]
Unused resources deleted:
- Commit 0b3ad35ae11603c7a5fdf724268ce323365f6aa4
- Commit d6bff4faea86a5c6313f4254a963c02aa52dabf2

**Comment by lfom** [comment]
More unused stuff removed:
- Commit 613e3c11d26e65fe9a126ba548b7e7ea3e7fa4e3
- Commit 7f66ce74d8ced42b28810b1f8ec74c0aa4f26d8f
- Commit e1c0dc13df01d05e48f3b980b331bbe09e197920
- Commit 119c1cf2761a1be537ea26e333357f6d9f2ee4d0
- Commit c928bfaede3dcb86d2648110b620200e0e6fee51
- Commit f5d55ca2d207b0de718b656ada4c81e69c247172
- Commit 43b623899723af71807fe3168e2119e8aec94ddb

I will test `shrinkResources true` in gradle... Closing.

**Comment by lfom** [comment]
For the record: shrinkResources requited minify, what breaks a few things when running the app, so unless some custom rules are build to fix it, they cannot be used.
