### ISSUE TITLE
Suggestions Amazmod

### ISSUE THREAD

**Issue by MateusMI** [AmazMod/AmazMod#398]
Suggestions Amazmod

* Put some way to notify battery percemeter.

Example: "15%, charge your battery", "100% Battery Charged"

** Set the time notifications display
Example: Notification of Whatsapp / Telegram 10s, e-mail 5s, defined by the user to their mode.

*** Set the display time of the call notification vibrate and touch the screen, because sometimes you can not touch the clock to turn off or silence, and the clock keeps vibrating until you touch the clock.

If possible give more ideas, I'm just trying to help with suggestions, if not allowed excuse me. I just try the app that is already good.

Thank you .

**Comment by diotto** [comment]
Thanks for the suggestions. We are evaluating them!!!!

**Comment by fcaronte** [comment]
1) now exist :)
2) if you need to read long text, you need to scroll and so not need to increase timeout (you can set a general timeout from amazmod setting)
3) i think is impossible make modification to the call notification because are manage from official amazfit app

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestions Amazmod](https://trello.com/c/2OLLwkF3/20-suggestions-amazmod)

**Comment by diotto** [comment]
Already implemented in current dev branch
