### ISSUE TITLE
WhatsApp/Messenger call notifications not working

### ISSUE THREAD

**Issue by fcaronte** [AmazMod/AmazMod#400]
Today I see that when received a WhatsApp call, service go force close. I pick a log with crash 
[fc on voip call.txt](https://github.com/AmazMod/AmazMod/files/2862080/fc.on.voip.call.txt)

**Comment by 1immortal** [comment]
there are some missing notifications as well with VoIPs
![screenshot_2019-02-13-20-51-48-865_com edotassi amazmod](https://user-images.githubusercontent.com/5845985/52900231-255ecc00-31fc-11e9-80d1-2cf8fb244c60.png)
![screenshot_2019-02-14-14-35-46-472_com edotassi amazmod](https://user-images.githubusercontent.com/5845985/52900232-25f76280-31fc-11e9-9b82-ab44acfbf7c4.png)

**Comment by diotto** [comment]
Is this happening in dev branch @fcaronte ?

**Comment by diotto** [comment]
ERROR:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String amazmod.com.transport.data.NotificationData.getKey()' on a null object reference at com.amazmod.service.ui.fragments.NotificationFragment.onCreate(NotificationFragment.java:96)

**Comment by fcaronte** [comment]
I test again on last commit Dev and now is not notification nothing (talking about WhatsApp call) but is not crash. If I not answer the call, I receive the lost call message correctly.the option for that is enabled and seem that after the call if I go into amazmod I see there isn't connection and have difficult to reconnect without need to reboot

**Comment by fcaronte** [comment]
make some other test and see that facebook messenger call got FC too and need a launcher reboot to connect again to phone, if you disable the "enable voice call notification" no more force close and only the missing call notification

**Comment by GreatApo** [comment]
Additionally, we need to also look for this report from Kind of working

> When I receive a call now (v1.1.3 + 1880), I get the call notfication via Amazfit but then if I unlock the watch I also see "Welcome to Amazmod" message. Seems like Amazmod restarted.

Original issue: https://github.com/AmazMod/AmazMod/issues/377

**Comment by GreatApo** [comment]
Messenger calls do not seem to work at all. Additionally, there was an error (not crash) on answering the call:
![image](https://user-images.githubusercontent.com/9620510/55806512-49da7480-5ad8-11e9-8470-99e01d501871.png)

**Comment by fcaronte** [comment]
I try again and when receive a call from WhatsApp amazmod service force close
![IMG_20190409_161941](https://user-images.githubusercontent.com/26366403/55807981-78118180-5ae3-11e9-8dd6-8e0f16f31173.jpg)

**Comment by GreatApo** [comment]
Commit: 5324faee6ce9508375008ac08f07ca867379770b

Crash avoided from watch's side however it seems that wrong data are transmitted (errors keep popping afterwards).

**Comment by reflecx** [comment]
[amazemod-whatsapp call.log](https://github.com/AmazMod/AmazMod/files/3123911/amazemod-whatsapp.call.log)
For what it's worth, here's a Amazmod.log when a Whatsapp call is received. It seems that the notification to the watch is not being sent until the ringing ends. That notification seems to crash Amazmod watch service (build 1893) as well since I get a "Welcome to Amazmod" message. The missed call notification comes in ok.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WhatsApp/Messenger call notifications not working](https://trello.com/c/JnQhmqNK/21-whatsapp-messenger-call-notifications-not-working)

**Comment by fcaronte** [comment]
Work in last Dev branch
