### ISSUE TITLE
Notification/Vibration after install app

### ISSUE THREAD

**Issue by ahsim** [AmazMod/AmazMod#402]
I noticed that you added ability to install apk file directly from file manager on the watch but will be cool to receive vibrate notification after installation complete (or error)

**Comment by GreatApo** [comment]
If this can be done, it will be a good solution to the problem of not knowing if the installation is finished.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notification/Vibration after install app](https://trello.com/c/35s2VZ6N/22-notification-vibration-after-install-app)

**Comment by fcaronte** [comment]
added! you will see that on next release
