### ISSUE TITLE
Clean memory option (apps filter)

### ISSUE THREAD

**Issue by ahsim** [AmazMod/AmazMod#404]
will be cool to have extended clean memory option in the settings of amazmod on the watch. I noticed that after clean memory some needed for me app was closed too, but I want to have ability to close not all apps so will be cool to have some task manager)

**Comment by GreatApo** [comment]
I would propose a list like the "app manager" with a "clean all" button at the top and all the ram apps afterwards (I am not aware if it is possible though). Is is simpler and user will have a better view of the running apps.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean memory option (apps filter)](https://trello.com/c/AECNcaEU/23-clean-memory-option-apps-filter)

**Comment by 1immortal** [comment]
implemented on the watch side a long time ago.
