### ISSUE TITLE
cant open files with spaces in name from watch service

### ISSUE THREAD

**Issue by ahsim** [AmazMod/AmazMod#409]
if name contains spaces or dots I can't install it directly from the watch from build in file manager. I got "Unknown file type" error. Fix this please

**Comment by fcaronte** [comment]
Confirm with space is not working but I think is an adb limitations, regards dots I don't see any problems to install like myapp.v.1.0.0.apk only space give problems

**Comment by diotto** [comment]
Probably escaping or putting file name between quotes solves this.

**Comment by fcaronte** [comment]
yes confirm quotes is the fix. i try wqith manually shell command and with this is not workpm install /sdcard/a b.apk
        pkg: /sdcard/a
        ver: b.apk
Failure [INSTALL_FAILED_INVALID_URI]

but if i add quote work correctly
pm install /sdcard/"a b.apk"
        pkg: /sdcard/a b.apk
Success

so probably need to Update the script adding quotes
