### ISSUE TITLE
Change Input Method

### ISSUE THREAD

**Issue by sniperla** [AmazMod/AmazMod#412]
Hey Guys, one Problem i think. If i choose to change the Input Method in the Mod App what can it do? I have no Buttons they i can choose. What is it be? Who wants that? Can i write some Words over the Display from my Amazfit Verge? Thanks.

**Comment by diotto** [comment]
Hi sniperla. Do you have an keyboard apk installed in your watch ? If yes, it should appear in a list at "Change Input Method" screen.

**Comment by sniperla** [comment]
Hey Marciello. No, i have No extra Input Method App. What kind of them say
you would you personaly use and tell me which app? I would love to answer
some short messenges via mia Verge Watch. Its  so cool. But it come more
and more functions to the Mod and that is GREAT! Maybe it is possible the
Modepicture that comes from above who Sound and Light are shown and the
flightmode that this were a bit Pimped? My English is bad, sry. An another
Menü Layout Maybe to choose if Flightmode and the Automatic Light Mode and
and. you know what my Idea are? Thank You Very much for your Answer. Ps. I
have switched from my iPhone SE back to my Axon 7 Mini. Theres an Icon for
the Amazfit Battery Load. See on my Picture that is on my Mail. Greetings
from Germany...Uwe

Marcelo Diotto <notifications@github.com> schrieb am Do., 21. Feb. 2019,
18:21:

**Comment by diotto** [comment]
Hi @sniperla , I suggest you to use TouchOne keyboard (https://forum.xda-developers.com/smartwatch/amazfit/change-language-touchone-keyboard-t3895770/post78812286#post78812286) or Minuum.

**Comment by diotto** [comment]
Hi @sniperla did you manage to install a keyboard in your Verge ? I expect yes!!
Can we close this issue ?

**Comment by sniperla** [comment]
Hello.. Yes i have installed the Writing Apk. And it works Perfekt. Its
still very hard to use it normaly for Chat.

Thanks for your Mail....

Marcelo Diotto <notifications@github.com> schrieb am Mi., 13. März 2019,
15:29:

**Comment by diotto** [comment]
Nice to know that the keyboard is working!!! Unfortunatelly a smartwatch is not so good for chatting. I prefer to use predefined messages and the keyboard i rarely use.
I'm closing this issue.

**Comment by sniperla** [comment]
Yes. Close it. Thanks for your request.
Love that AmazMod. Hafe you evwr think about to made a Own Custom Rom for
the Verge Watch or the "Amazfit - Family" where all is included? What you
think?

Greetings from Germany
Uwe

Marcelo Diotto <notifications@github.com> schrieb am Mi., 13. März 2019,
21:21:

**Comment by diotto** [comment]
@sniperla I suggest that you use Saratoga's ROM: https://forum.xda-developers.com/smartwatch/amazfit/paceficator-project-verge-3-0-15-0-rom-t3887306

The only missing thing is a keyboard

**Comment by sniperla** [comment]
Ja, its okay i think for "the normalo's" of User. I thought it wouldt be a
"Blast" of a New Graphical User Interface like all the other Others outside
but for us Smartwatches. DPI Change must be vailable earlier in the Menu.
An complete Change if VIEW of the Smartwatch OS. You absolutely know what i
mean?!? Samsung and Huawei and also Huami are pretty the Same Looking and
Menu List System. Maybe like the LG Smartphone with 3D Menu System. Its a
Round Display. Let us begin and think "more Round". Im a german Guy and
okay i can write some of my ideas but thats the End of it than. German
talking where so.Much easier...But. Okay..

You have Questiones? Maybe German lang? Do you know anyone ho knows a more
that little Bit German speak?
Greetings....Good Night wishes to You and the Team!!

Bye. Uwe

Marcelo Diotto <notifications@github.com> schrieb am Do., 14. März 2019,
00:44:

**Comment by verma47** [comment]
I use many many keyboards but no one works I have amazfir verge help me
