### ISSUE TITLE
Updating Service APK from phone app canceled if the phone's orientation is changed

### ISSUE THREAD

**Issue by mignat** [AmazMod/AmazMod#413]
Steps to reproduce:
1 . Have an older than latest service-app on the watch 
2. Open the phone app
3. Start the service-app update 
4. While the apk is transfering to the watch change the phone's orientation

Problem:
The file transfer cancels and you are re-prompted to update the service app

**Comment by 1immortal** [comment]
its a known issue at this point, thanks

**Comment by diotto** [comment]
Firebase also pointed to this URL as an insight for this bug: https://stackoverflow.com/questions/22924825/view-not-attached-to-window-manager-crash

**Comment by diotto** [comment]
One option (probably easier one) is to lock orientation during update using the "Screen.lockOrientation(this)"
Another option is changing android manifest:
https://stackoverflow.com/questions/5913130/dont-reload-application-when-orientation-changes

**Comment by diotto** [comment]
StackTrace:

com.afollestad.materialdialogs.MaterialDialog.dismiss (MaterialDialog.java:993)
com.edotassi.amazmod.ui.fragment.WatchInfoFragment.updateDownloadCompleted (WatchInfoFragment.java:372)
com.edotassi.amazmod.update.UpdateDownloader$1.onDownloadComplete (UpdateDownloader.java:40)
com.downloader.request.DownloadRequest$2.run (DownloadRequest.java:259)
