### ISSUE TITLE
Delete all notifications

### ISSUE THREAD

**Issue by ega6226** [AmazMod/AmazMod#415]
Hi,

Is it possible to delete all notifications that are saved on the watch?

Regards

**Comment by 1immortal** [comment]
yes, long tap on the "Notifications" in AmazMods' notification drawer, and you'll have the ability to delete all notifications

**Comment by ega6226** [comment]
Hi,

You mean here? 
![whatsapp image 2019-02-22 at 08 22 03](https://user-images.githubusercontent.com/43537728/53230148-53be2a80-3686-11e9-8797-f8e0a5828747.jpeg)

I pulse it for a long time and it does not do anything.
