### ISSUE TITLE
Notifications for local ics calendar

### ISSUE THREAD

**Issue by SoerenEilenberger** [AmazMod/AmazMod#417]
Hi, first of all thanks for the great work. 

I have some issues getting the calendar on my watch though - but that is a different story. 

I think it would be great getting notifications from events that are being stored on the watch. I know that we can synchronise this or watch and get notifications for events on our phones. But the great thing about amazmod and synchronising the calendars to the watch, is that one can be detached from the phone and yet be notified or at least see events. so I will not miss an appointment when I don't carry my phone with me.

I think I read on some homepage about it may smart that there is not a need for this but I think there is a very valuable use case. It makes the Amazfit Stratos basically a fully fledged SmartWatch.

Once again thank you so much for your great work and time you put into this!

**Comment by diotto** [comment]
Hi @SoerenEilenberger , thanks for your contribution. If I understood well, this is already implemented. If you configure amazmod to send phone events to watch they are stored locally in watch and can be seen without having your phone with you. You just need Amazmod (to sync events to watch) and TimelineWidget (https://github.com/GreatApo/Amazfit-Timeline-Widget) or (https://github.com/GreatApo/AmazfitPaceCalendarWidget) installed in watch.
Feel free to reopen the issue if it's not what you were asking for.
Regards!!

**Comment by SoerenEilenberger** [comment]
Hi @diotto, thanks for your reply! 
I have both installed (currently can't get events shown in both widgets though - neither via local or ICS Amazmod events push, nor via the ICS URL in the text file nor a downloaded ICS copied on the watch).
I meant really a notification, a reminder, something that vibrates, as it does for a notification on the phone.

**Comment by SoerenEilenberger** [comment]
Sorry can't find the way how to reopen the case

**Comment by GreatApo** [comment]
Issue moved at [Calendar Widget](https://github.com/GreatApo/AmazfitPaceCalendarWidget/issues/14).
