### ISSUE TITLE
Option to dismiss notifications on phone when custom notifications are dismissed on watch

### ISSUE THREAD

**Issue by brownstein666** [AmazMod/AmazMod#419]
Maybe an option to dismiss the notification on phone when I delete from watch, or another button just for that.

**Comment by diotto** [comment]
I think we already have this for standard notifications. Maybe the method just needs to be called when removing a custom notification too. What do you think @GreatApo ?

**Comment by GreatApo** [comment]
Yes, this works for standard notifications. We can probably do it for custom notifications too.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Option to dismiss notifications on phone when custom notifications are dismissed on watch](https://trello.com/c/zqUH1cLP/24-option-to-dismiss-notifications-on-phone-when-custom-notifications-are-dismissed-on-watch)

**Comment by lfom** [comment]
It was added to current dev branch, please reopen if there are any issues.
