### ISSUE TITLE
Old readed notification still push to watch 

### ISSUE THREAD

**Issue by stanleyhunk** [AmazMod/AmazMod#420]
I'm experiencing some problem with notification, all the readed notification between the duration of bluetooth disconnected and reconnected still push to watch, try fix this problem please, thank you

**Comment by tone7777** [comment]
+1
 I am in the same situation.

**Comment by diotto** [comment]
This is not exactly a problem. It's how JobScheduler works. It stores all notifications and send them to watch when it reconnects. In current dev version there is an option to disable this behavior. We are testing and improving and and, soon, it'll be released
