### ISSUE TITLE
Notifications delay

### ISSUE THREAD

**Issue by EgorOA** [AmazMod/AmazMod#421]
Hi!

There are some troubles for me with new AmazMod

1. Frequent connecting / disconnecting after receiving a notificatications like described in https://github.com/AmazMod/AmazMod/issues/311
2. Dramatically increased power comsumption - 4 days max in real life instead of 6 on previous versions of AmazMod. 
3. Not all of notifications are displayed on the watch - sometimes there are no notifications at all. But test notifications from About page are normal.

First screen of Amazmod here
![image](https://user-images.githubusercontent.com/25991277/53716169-10717200-3e65-11e9-9878-6d46a6b8d87a.png)
AmazFit App is 2.6.10 and it had not been updated after service was updated.
This power graph was taken for period almost without notifications - watch was laying on the table all time with plane mode on night, but 60% percent was drained for 3 days - it is not good for me.

What else info can I paste here to help with my problems?

**Comment by EgorOA** [comment]
Can new features like sending notification icons increase power consumption? Is caching of images implemented now?

**Comment by EgorOA** [comment]
Besides issues described in head message I can detect that there is a visible delay before appearing messages on the watch. Can it be explained that service is goes in error state and restores it's functionality with a delay? How can I see that there are no errors (FC) for AmazMos service?

**Comment by EgorOA** [comment]
Today I have noticed amazing record: message from WhatsApp appeared on the watch half an hour later then I have read it on the phone and web WhatsApp in the brower! Where did the message go??? Was it AmazMod or AmazModService?

**Comment by EgorOA** [comment]
New version is much better, continue to evaluate

**Comment by EgorOA** [comment]
There is a delay between message received by phone and notification on the watch. And that delay not constant (but increasing to the evening??? or other reasons?)

**Comment by GreatApo** [comment]
You can see errors from an adb log. Amazmod uses the already established connection of Amazfit app. We know the the connection is not perfect but the battery drain is far better than establishing a new bt connection.
We can't really asses the delays because they depend on a huge number of factors. We have seen huge differences between different phones. On the other hand we do try to fix and enchant the code.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications delay](https://trello.com/c/hoCFPxQM/25-notifications-delay)

**Comment by EgorOA** [comment]
Sorry, Pavel. Can't open your links - says "Card not found."

**Comment by EgorOA** [comment]
Can say that 1894 version is worse than 1893 - there are delays and not delivered notifications :(

**Comment by EgorOA** [comment]
There are no notifications with 1894 version thought test notifications and calls are working

**Comment by 1immortal** [comment]
Hi,

please re-validate all permissions and notification approval access on both app, Amazfit and AmazMod

**Comment by EgorOA** [comment]
Reinstalled AmazMod on watch with PC .exe
Now notifications are alive but delay is present
Not everytime but regular
It seems to me that watch is in sleeping mode and not always goes from it when notification on the phone is raised.

**Comment by GreatApo** [comment]
> It seems to me that watch is in sleeping mode and not always goes from it when notification on the phone is raised.

It is possible the other way around :P

**Comment by diotto** [comment]
Do you have the "Store notifications while disconnected" option enabled? If yes, try disabling that.
I may help with the delays BUT if you are having disconnections you'll lose the notifications that arrives during the disconnected time.

**Comment by EgorOA** [comment]
> Do you have the "Store notifications while disconnected" option enabled? If yes, try disabling that.
> I may help with the delays BUT if you are having disconnections you'll lose the notifications that arrives during the disconnected time.

Thanks, I'll try it

**Comment by EgorOA** [comment]
> Do you have the "Store notifications while disconnected" option enabled? If yes, try disabling that.
> I may help with the delays BUT if you are having disconnections you'll lose the notifications that arrives during the disconnected time.

Thanx! Much better!
