### ISSUE TITLE
Message in watch AmadModService Stopped

### ISSUE THREAD

**Issue by tone7777** [AmazMod/AmazMod#423]
I have one stratos chinnese version but I put the firmware internacional version, I want to see in Spanish.
I have the apk amazmod in the watch and the mobile. If I active the notificacions when I want to read all notifications that I have received always show the error "AmazModService Stopped". If I disconnect the notifications sometimes when I see the screen of amazmod in the watch, I see the same error "AmazModService Stopped".

I don't know what I can do to quit this error.

![img-20190304-wa0031](https://user-images.githubusercontent.com/48218307/53766018-f326bd00-3ed1-11e9-989f-169a2637d25b.jpg)

**Comment by tone7777** [comment]
Well, I tried to connect it to another phone, a BQ and it does not give me that problem, so I think the problem comes with my Huawei phone :(
I have problems with my Huawei and Amazmod because I do not receive notifications at times and I have disabled the mobile everything I've seen of energy saving :(

**Comment by aspie74** [comment]
The same here, also with a Huawei

**Comment by antares10** [comment]
I also have a huawei and the same problem. Any solutions?

**Comment by antares10** [comment]
Solution is to use:
`Drawable drawable = resources.getDrawable(notification.icon);`
instead of 
`Drawable drawable = resources.getDrawable(iconId);`
in the NotificationFactory.java in the phone app.

**Comment by tone7777** [comment]
That command, Do I have to run in the mobile app in settings -> run command Shell??

Thanks!

**Comment by antares10** [comment]
> That command, Do I have to run in the phone app in settings -> run command Shell??
> 
> Thanks!

No, the developer guys will modify the source code then I hope it will work and be in the next release.

**Comment by tone7777** [comment]
Ok, thanks!

**Comment by diotto** [comment]
> Solution is to use:
> `Drawable drawable = resources.getDrawable(notification.icon);`
> instead of
> `Drawable drawable = resources.getDrawable(iconId);`
> in the NotificationFactory.java in the phone app.

Hi @antares10 , just changed that in code. 
For me no difference. Can you and @tone7777 check ?
If you don't know how to build from git/android studio contact me and i can send you a pre-build apk file.

**Comment by antares10** [comment]
I have changed this line and built it when I added this comment. Since then I am using this version. The no difference is normal, I did not want to modify the behaviour, only make it work on huawei phones. So if it works for you on another phone, and works for me on a huawei I think it should be changed in the next release. I hope @tone7777 can confirm it.

**Comment by davigar1391** [comment]
I builded and installed the /dev branch with the changes and It's working perfectly on my Huawei phone.

**Comment by tone7777** [comment]
> > Solution is to use:
> > `Drawable drawable = resources.getDrawable(notification.icon);`
> > instead of
> > `Drawable drawable = resources.getDrawable(iconId);`
> > in the NotificationFactory.java in the phone app.
> 
> Hi @antares10 , just changed that in code.
> For me no difference. Can you and @tone7777 check ?
> If you don't know how to build from git/android studio contact me and i can send you a pre-build apk file.

I don't know how yo build, if you don't mind send to me preocupa tell me how I can build.

Thanks.

**Comment by GreatApo** [comment]
I compiled the latest dev service version, you can get it from [here](https://we.tl/t-SetYjwWwUx) (will be there for 7 days). This is only for testing, YOU WILL NOT BE ABLE TO UPDATE FROM THIS VERSION (you will have to uninstall it and install an official version).

I am closing this issue as "fixed", reply in case this specific bug is not fixed.
Thank you for the feedback.

**Comment by tone7777** [comment]
> I compiled the latest dev service version, you can get it from [here](https://we.tl/t-SetYjwWwUx) (will be there for 7 days). This is only for testing, YOU WILL NOT BE ABLE TO UPDATE FROM THIS VERSION (you will have to uninstall it and install an official version).
> 
> I am closing this issue as "fixed", reply in case this specific bug is not fixed.
> Thank you for the feedback.

Thanks! I will get It and install this version. I will can check It probably today or tomorrow. 

Thank you.

**Comment by kubikub** [comment]
Hello ! This dev version works great ! no more FC on the watch. Notification comes from my huawei P20 without any problems.

Could you please confirm the beta or release version which will be issue with this dev version integrated.
Regards.

**Comment by tone7777** [comment]
> I compiled the latest dev service version, you can get it from [here](https://we.tl/t-SetYjwWwUx) (will be there for 7 days). This is only for testing, YOU WILL NOT BE ABLE TO UPDATE FROM THIS VERSION (you will have to uninstall it and install an official version).
> 
> I am closing this issue as "fixed", reply in case this specific bug is not fixed.
> Thank you for the feedback.

I just try this version that I had downloaded days before, but I have the same problem, stop service when I want to answer a message.
