### ISSUE TITLE
Delete folder with content inside it

### ISSUE THREAD

**Issue by fcaronte** [AmazMod/AmazMod#426]
There is a bug on service file manager where I can't delete directly a folder with other file inside it but you need to manually delete all file inside and then the empty folder

**Comment by diotto** [comment]
I was checking how to implement it and it's not hard but, after thinking a little more, I'm not sure if we really want to permit the removal of a Folder with all contents direcly from watch interface. 
Any mistake may cause user to loose lots of files. Forcing user to delete contents before deleting folder is some sort of prevention mechanism.
What do you think @1immortal @GreatApo @lfom @edotassi ?

**Comment by fcaronte** [comment]
yes i'm think on this too, but then i think you have a confirmation popup after a long click and so i think is difficult to do for mistake
