### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ega6226** [AmazMod/AmazMod#429]
Hi,

Since the last update I have had several problems related to notifications.

When some notification (whatsapp, gmail) arrives to the phone, sometimes it does not reach the clock, and all of a sudden you all enter at once.

Normally I turn off the clock at night, the next day when I turn it on, all the notifications I have had at night begin to appear and I have already seen it on the phone.

Thanks

**Comment by amknipp** [comment]
Same here. I had to uninstall Amazmod because this is draining my battery. I'm waiting for the next update to download it again.

**Comment by ega6226** [comment]
Yes, my battery consumption has also increased.

**Comment by diotto** [comment]
Hi @ega6226 and @amknipp . Samsung devices are having frequent disconnections with watch (not related to amazmod). As a workaround we implemented a scheduler which stores the notifications and send them when watch reconnects. This scheduler caused sometimes delays and battery drains. In current development version we are making this scheduler optional, I expect this improves the delays and reduces drains.

**Comment by ega6226** [comment]
I have a Xiaomi Mi A1
