### ISSUE TITLE
Will have an iOS version?

### ISSUE THREAD

**Issue by avelinocneto** [AmazMod/AmazMod#430]
Hi guys,
recently I've migrated to iOS, so we will have an ios version for amazmod?
thanks

**Comment by diotto** [comment]
Hi @avelinocneto , unfortunatelly it's not in our roadmap. Any experienced iOS developer interested in joining the project and helping in it is welcome.

**Comment by GreatApo** [comment]
I am closing this issue since this project is completely related to the operation system it is coded on. Like diotto said, if anyone wants to work on this, he is more than welcome to join the team.
