### ISSUE TITLE
How do I uninstall AmazMod?

### ISSUE THREAD

**Issue by skorokithakis** [AmazMod/AmazMod#431]
Notifications stopped coming to the watch and I want to completely uninstalling AmazMod, but even flashing the stock firmware didn't do it. How can I remove the apk from the watch?

**Comment by fcaronte** [comment]
try to read here if you find useful thing and maybe try to understood what wrong with notification first to uninstall everything

https://github.com/AmazMod/AmazMod/blob/master/FAQ.md

**Comment by diotto** [comment]
Hi @skorokithakis , the FAQ @fcaronte  posted has it, but if you are not familiar with adb/apkinstaller/other tools, the easiest way is to Unpair / Pair watch from phone.

**Comment by skorokithakis** [comment]
I'm trying to uninstall and I'm getting this:

```
12:45:45 $ adb shell pm uninstall com.amazmod.service
Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]
```

**Comment by fcaronte** [comment]
As Is written on previous posted FAQ you need to do this
![Screenshot_20190309-115626_Samsung Internet](https://user-images.githubusercontent.com/26366403/54070627-7f363d00-4262-11e9-8c6f-3128913eaa26.jpg)

**Comment by skorokithakis** [comment]
I did do that, and I still get the same error message. Do I need to restart the device afterwards?

**Comment by fcaronte** [comment]
So probably you update without previously remove admin right and so now you need to wipe your watch and the easy way is like @diotto say with unpair and pair again
