### ISSUE TITLE
Notification bug with filtered app

### ISSUE THREAD

**Issue by fcaronte** [AmazMod/AmazMod#432]
Sometime, need to understand better when and how, when i receive a message from whatsapp contact, i receive normally but then, if receive other message from a "filtered" contact i receive notification with last previous message (intead of not receive noting) from non filtered people. Sorry if not explain clearly  -.-'

**Comment by diotto** [comment]
Maybe it's related to whatsapp behavior. AFAIK when you have unread messages and receive a new one whatsapp generates notifications for the new message (which could be filtered) and also for the old unread ones.

**Comment by GreatApo** [comment]
I think the problem is what diotto describes. Issue is closed until further investigation is needed.
