### ISSUE TITLE
Service widget (watch) - hide/show/select shortcuts

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#440]
in most cases, most of the users will use some 2 to 4 options of the entire settings and functionality that available on the watch.
an option of hiding/moving to top/re-order seems as a nice addition.

**Comment by dsounds** [comment]
My reordering of widgets defaults every time I restart the watch. :(

**Comment by 1immortal** [comment]
I was not referring to the widgets, more the actual settings in the amazmod widget.
regarding the defaults, make sure that you tap the keep location on the phone app, and place the widget from the watch itself on the wanted location and sync your settings

**Comment by GreatApo** [comment]
I don't think there are options in there that are used every day.

Maybe what we need is to select what shortcuts should be in the widget.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [watch service widget - ability to hide/re-order settings](https://trello.com/c/dJX5q9zs/26-watch-service-widget-ability-to-hide-re-order-settings)
