### ISSUE TITLE
Received messages are not getting updated after last update

### ISSUE THREAD

**Issue by javiermontanov** [AmazMod/AmazMod#446]
With the last update the number of received messages are not getting updated after are reviewed. Now the number of messages are constantly increased without decreasing, this was working perfectly before.
The number of messages now is looking like a some "counter" for all received messages, and that is not helpful at all.
App release 1.1.5
AmazMod service release 1889

![fotobug-0000](https://user-images.githubusercontent.com/600466/54948374-de5aa980-4f12-11e9-9942-8cfc072c5340.jpg)

**Comment by fcaronte** [comment]
counter decrease if you delete notification inside it

**Comment by GreatApo** [comment]
The counter works correctly. Like fcaronte mentioned, you need to delete the messages to make it decrease.

**Comment by antares10** [comment]
Ia it possible to somehow synchronize the counter with the current notifications on the phone?

**Comment by fcaronte** [comment]
Yes as i know is into Todo list with no ETA
