### ISSUE TITLE
Application Filter bug (System Apps and saving)

### ISSUE THREAD

**Issue by HFCCandeias** [AmazMod/AmazMod#448]
I installed the AMS 1889 on watch and Amazmod app 1.1.5 on phone but I can't receive any messages notifications, I tested sent notifications in about option and all works fine... In 1.1.5 app I can't see the "mensagem" in systems app under the Config menu, on the other version I see them and i could select them to receive notifications when a text message is received... My Phone is a Huawei P20 Pro on Android 9... Thanks in advance

**Comment by diotto** [comment]
Hi @HFCCandeias , did you enable "System Apps" in Application List ?

**Comment by morube** [comment]
Hi @diotto, I have the same issue as HFCCandeias, notifications only arrive when AmazMod app is open. I verified that AmazMod has automatic start permission. I have enabled "System Apps" but don't know what I have to activate.

Thx!

**Comment by HFCCandeias** [comment]
Hi @diotto, yes I have system apps enabled, but in the 1880 versios I have an option in system apps "Mensagens" that I enabled to received text messages... The other features works, incoming calls, notifications of enabled apps, etc... Thanks

**Comment by diotto** [comment]
> 
> 
> Hi @diotto, I have the same issue as HFCCandeias, notifications only arrive when AmazMod app is open. I verified that AmazMod has automatic start permission. I have enabled "System Apps" but don't know what I have to activate.
> 
> Thx!

@morube your problem is different. Your AmazMod phone app is probably  being killed by battery optimization. Remove it from Optimization List and you are done. :smile:

**Comment by diotto** [comment]
> 
> 
> Hi @diotto, yes I have system apps enabled, but in the 1880 versios I have an option in system apps "Mensagens" that I enabled to received text messages... The other features works, incoming calls, notifications of enabled apps, etc... Thanks

Very Strange. Nothing was changed in that. And its not related to watch service (1880), the list of apps is done only in phone. If I understood well 1.1.3 worked and now 1.1.5 not, right ?
Have you tried to Enmable System Apps and searched for "Messages" in the upper right search icon ? Maybe that search caused some problem.

**Comment by HFCCandeias** [comment]
![Screenshot_20190401_124825_com edotassi amazmod](https://user-images.githubusercontent.com/48959449/55325375-d18f0600-547c-11e9-8f41-1031512a2929.jpg)
@diotto you are correct, in the 1.1.3.i don't have this problem...

**Comment by diotto** [comment]
Thanks! So it's related to search. I'll look at that!
Thanks!
Workaround is to search for app, right ?

**Comment by HFCCandeias** [comment]
If you need more information just ask

**Comment by diotto** [comment]
Just checked that if you:
1) Enter the "Selected Applications" activity
2) Mark the "Enable System Apps"
3) Unmark the "Enable System Apps"

Then system apps appears.
Can you try to reproduce it @HFCCandeias ?

**Comment by HFCCandeias** [comment]
![Screenshot_20190401_134853_com edotassi amazmod](https://user-images.githubusercontent.com/48959449/55328734-f5eee080-5484-11e9-87be-2e1f7ccf99a1.jpg)

**Comment by HFCCandeias** [comment]
Unmarked system apps

**Comment by morube** [comment]
> > Hi @diotto, I have the same issue as HFCCandeias, notifications only arrive when AmazMod app is open. I verified that AmazMod has automatic start permission. I have enabled "System Apps" but don't know what I have to activate.
> > Thx!
> 
> @morube your problem is different. Your AmazMod phone app is probably being killed by battery optimization. Remove it from Optimization List and you are done.

Thx!! that's the problem!

**Comment by HFCCandeias** [comment]
@diotto now it woks, now I can select "mensagem" in system apps... Thanks for the correction

**Comment by GreatApo** [comment]
There seems to be a problem with the apps filter:
- System apps sometimes do not appear even if checked
- Apps are not saved and need multiple tries

**Comment by fcaronte** [comment]
fixed we can close :)

**Comment by GreatApo** [comment]
Apps are sometimes not saved and need multiple tries. I still have to review the code.

**Comment by GreatApo** [comment]
After a quick look in the code I didn't notice anything else strange. This issue is closed until further review is needed.
