### ISSUE TITLE
Update to 1889

### ISSUE THREAD

**Issue by lxnunorodrigues** [AmazMod/AmazMod#449]
Hi , i receive that update on my mobile , i click to yes , its downloadind and transfer to my clock but dont make anythink , if i click on my clock one time amazfit desepears , if i reboot , appears the last 1880

whats happened !

**Comment by DMTwo** [comment]
Same issue here!

**Comment by fcaronte** [comment]
install process can take 20min to install with two automatic reboot. if you manually reboot, you stop update process

**Comment by DMTwo** [comment]
Confirmed, updated sucessifully!
I pot it to update and forget about it, I don't know how long it took, but now it's in 1889 version.

**Comment by diotto** [comment]
As @fcaronte stated and @DMTwo confirmed, you just need to wait. If it not works your watch's ADB process may be hang. Restart watch and try again.
REMEMBER: the process is long and may take up to 20 minutes, some times.
