### ISSUE TITLE
crash 1889 service

### ISSUE THREAD

**Issue by paraflu** [AmazMod/AmazMod#450]
Service crash on boot.

> W/InputDispatcher(  381): channel '35af4e33 com.amazmod.service/com.amazmod.service.springboard.LauncherWearGridActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 
> E/InputDispatcher(  381): channel '35af4e33 com.amazmod.service/com.amazmod.service.springboard.LauncherWearGridActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 
> I/ActivityManager(  381): Process com.amazmod.service (pid 1204) has died
> 
> W/ActivityManager(  381): Scheduling restart of crashed service com.amazmod.service/.MainService in 6576ms
> 
> I/WindowState(  381): WIN DEATH: Window{35af4e33 u0 com.amazmod.service/com.amazmod.service.springboard.LauncherWearGridActivity}
> 
> W/InputDispatcher(  381): Attempted to unregister already unregistered input channel '35af4e33 com.amazmod.service/com.amazmod.service.springboard.LauncherWearGridActivity (server)'
> 

Some suggestion? I've checked the auth but nothing there.

**Comment by sniperla** [comment]
Hello, Paraflu,
between it dont work, you have to Setting Back your Watch. Go and set it complete Back. Then install it again. It max boot 2-3 times. If nothing change, then update to to the similar Version.

**Comment by paraflu** [comment]
Thanks it work!
