### ISSUE TITLE
No notification indicator on watchface or lockscreen

### ISSUE THREAD

**Issue by dsounds** [AmazMod/AmazMod#453]
Hi, I cannot find how to turn on notification indicator/icon/dot on watchface or lockscreen... is there any ? If not, can this be implemented ?  

I cannot understand how this isn't done by Amazfit in the first place. Such a basic feature.
Something like notification LED on mobile phones.  I think Samsung Galaxy Watch has some little yellow dot on the watchface, if there is unread/missed notification.

Thank you very much!

**Comment by diotto** [comment]
There is already a notification counter implemented as a system config named "CustomWatchfaceData" and freely available to Applications or WatchFaces to use.
Command bellow returns number of notifications available: 
{"phoneBattery":51,"phoneAlarm":"seg 05:45","updateTime":1554064085235,"notifications":8}

AFAIK, the only watchface using this feature, until now, is GreatFit: https://github.com/GreatApo/GreatFit/releases
