### ISSUE TITLE
Error installing APKs with spaces or dots in name

### ISSUE THREAD

**Issue by ahsim** [AmazMod/AmazMod#455]
Apk files with spaces and (or) dots in name starts to install but never finished

**Comment by fcaronte** [comment]
this is the log when try to install a apk with space. deviceutil seam to read correctly the script is miss the ""
04-15 23:33:50.096 2373-2373/com.amazmod.service D/DeviceUtil: DeviceUtil installBusybox file already exists, size: 1576152
04-15 23:33:50.097 2373-2373/com.amazmod.service D/DeviceUtil: DeviceUtil installApkAdb installCommand: log -pw -tAmazMod $(sh /data/data/com.amazmod.service/files/install_apk.sh /storage/emulated/0/APK/quickshortcutmaker 1.0.13-1.apk OK /data/data/com.amazmod.service/files/bin 2>&1)
04-15 23:33:50.551 2552-2552/? D/AmazMod: install_apk continuing, arg1=(/storage/emulated/0/APK/quickshortcutmaker) arg2=(1.0.13-1.apk) arg3=(OK) arg4=(/data/data/com.amazmod.service/files/bin) 
04-15 23:33:50.593 2553-2553/? D/AmazMod: install_apk PATH:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin OLDPATH:/data/data/com.amazmod.service/files/bin 
04-15 23:33:50.972 2557-2557/? D/AmazMod: install_apk killing adb server  
04-15 23:33:54.110 2558-2558/? D/AmazMod: install_apk installing: /storage/emulated/0/APK/quickshortcutmaker 
04-15 23:33:54.367 2560-2560/? I/AmazMod: install_apk adb: Missing APK file 
04-15 23:33:54.492 2561-2561/? D/AmazMod: install_apk killing background processes 
04-15 23:33:54.617 2563-2563/? D/AmazMod: install_apk killing adb  
04-15 23:33:59.780 2589-2589/? D/AmazMod: install_apk kill-all

**Comment by GreatApo** [comment]
fix attempt
Commit: 5e647fc504c7ed79fdbc7f6dff85c8f8589f075f

**Comment by GreatApo** [comment]
fix attempt 2
Commit: 7b9640f63ecf4835d214a7732c49ff7b0c0db804

**Comment by fcaronte** [comment]
For me fix 2 work correctly 👍🏻

**Comment by GreatApo** [comment]
I am closing the issue. If there are still problems, it will be reopened.
