### ISSUE TITLE
Screenshots upside down

### ISSUE THREAD

**Issue by mplx** [AmazMod/AmazMod#456]
Screenshots taken with AmazMod are upside down and need to be rotated.

`AmazoMod 1.1.5, AmazMod Service 1889, ROM 3.2.0.20`

![ss_20190330_133259287](https://user-images.githubusercontent.com/1986588/55276267-4c77e580-52f2-11e9-96e9-eece8e4a7c90.png)

**Comment by 1immortal** [comment]
it happens on Verge devices only, PACE and Stratos ssed normally.

**Comment by mplx** [comment]
OK, I see. Thanks for the reply. I guess the problem is more sophisticated than simply checking for the device and rotate the image...

AmazMod rocks! 👍

**Comment by diotto** [comment]
Thanks @mplx!
We can try, in the future, rotating the picture after taking the screenshot. 👍

**Comment by GreatApo** [comment]
Color fix: commit ea4d9dd3cd273248d7ac0928b2c65b16a27f8e05
Rotate done: commit c12e82d0412d73dc14215e6f3c65036b50887c42
