### ISSUE TITLE
Battery Notifications - Data source

### ISSUE THREAD

**Issue by eranelbaz** [AmazMod/AmazMod#457]
Hey
I want to do battery status notifications,
I saw in your code that you log the battery level,
but could not find the log directory...
what is the path?

**Comment by GreatApo** [comment]
There are 4 points of interest in terms of battery:
- Phone/Service for watch's battery
- Phone/Service for phone's battery

Watch's battery:
- the phone requests the battery of the watch, the watch replies and phone saves the battery
-- App requests and gets the battery in: AmazMod\app\src\main\java\com\edotassi\amazmod\receiver\BatteryStatusReceiver.java
-- Service gets the request in function "requestBatteryStatus": AmazMod\service\src\main\java\com\amazmod\service\MainService.java

Phone's battery:
- phone transmits its battery and the watch receives it
-- AmazMod\app\src\main\java\com\edotassi\amazmod\receiver\WatchfaceReceiver.java
-- Service gets the data in function "watchface": AmazMod\service\src\main\java\com\amazmod\service\MainService.java

We intended to add this feature but haven't found the time to do so. Feel free to play around! It seems that the easiest way to send trigger notifications would be from watch when phone data arrive or when watch battery is requested. The draw back of this would be that the notification will trigger not when battery drops under the target level but in the next battery update.

Two options need to be created (probably for each) one for the target battery level limit and an on/off switch.
It is noted that the default watch notification is irrelevant of this feature.

Relevant request [here](https://github.com/AmazMod/AmazMod/issues/182).

**Comment by GreatApo** [comment]
I am closing this request. For further question/discussion please move at this [relevant request](https://github.com/AmazMod/AmazMod/issues/182).
