### ISSUE TITLE
Amazamod service has stopped

### ISSUE THREAD

**Issue by saydric** [AmazMod/AmazMod#463]
Hi and thank you for your work !
I encountered a crash of amazmod just after the installation and each time I try to launch the service.
amazmod service: 1890
stock: 3.2.1.0
phone: Galaxy A7 (2018)
android: 9

Here is the logcat, I hope it can help:

D/AmazMod ( 1875): AmazModService HermesEventBus init
W/art     ( 1875): Suspending all threads took: 5.714ms
I/art     ( 1875): Background partial concurrent mark sweep GC freed 915(62KB) AllocSpace objects, 0(0B) LOS objects, 34% free, 974KB/1486KB, paused 10.103ms total 55.516ms
D/AmazMod ( 1875): AmazModService cleanOldBatteryDb
D/AmazMod ( 1875): LauncherWearGridActivity mode: S
I/AmazMod ( 1875): WearMenuFragment newInstance
D/OpenGLRenderer( 1875): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas   ( 1875): Validating map...
V/WindowManager(  381): Adding window Window{3259d371 u0 com.amazmod.service/com.amazmod.service.springboard.LauncherWearGridActivity} at 2 of 4 (after Window{a16529e u0 com.huami.watch.launcher/com.huami.watch.launcher.Launcher})
D/AmazMod ( 1875): WidgetSettings: com.amazmod.service.MainService@1f5624cc \ /storage/emulated/0/Android/data/com.amazmod.service/files
D/AmazMod ( 1875): MainService onCreate HermesEventBus connect
D/AndroidRuntime( 1875): Shutting down VM
E/AndroidRuntime( 1875): FATAL EXCEPTION: main
E/AndroidRuntime( 1875): Process: com.amazmod.service, PID: 1875
E/AndroidRuntime( 1875): java.lang.RuntimeException: Unable to create service com.amazmod.service.MainService: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/AndroidRuntime( 1875):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2771)
E/AndroidRuntime( 1875):        at android.app.ActivityThread.access$1800(ActivityThread.java:151)
E/AndroidRuntime( 1875):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
E/AndroidRuntime( 1875):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1875):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 1875):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 1875):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1875):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1875):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 1875):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 1875): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/AndroidRuntime( 1875):        at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
E/AndroidRuntime( 1875):        at org.json.JSONTokener.nextValue(JSONTokener.java:94)
E/AndroidRuntime( 1875):        at org.json.JSONObject.<init>(JSONObject.java:156)
E/AndroidRuntime( 1875):        at org.json.JSONObject.<init>(JSONObject.java:173)
E/AndroidRuntime( 1875):        at com.amazmod.service.support.NotificationStore.setNotificationCount(NotificationStore.java:103)
E/AndroidRuntime( 1875):        at com.amazmod.service.MainService.onCreate(MainService.java:209)
E/AndroidRuntime( 1875):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2761)
E/AndroidRuntime( 1875):        ... 9 more
W/ActivityManager(  381):   Force finishing activity 1 com.amazmod.service/.springboard.LauncherWearGridActivity
W/InputMethodManagerService(  381): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@b612730 attribute=null, token = android.os.BinderProxy@d4b48d9

**Comment by GreatApo** [comment]
This has been fixed in the latest dev version. It this the officially released service?

Run this command with ADB, it will fix your error:
adb shell settings put system CustomWatchfaceData 0

**Comment by saydric** [comment]
Thank you it worked fine after disabling CustomWatchfaceData !

This is the version than I found here https://github.com/edotassi/AmazMod/releases/latest 
and using the win installer  Amazmod.service.installer.ver.1890.exe

**Comment by GreatApo** [comment]
You didn't disable it :P
The error was caused because CustomWatchfaceData didn't exist (returned null), hence, you just gave it an random value (0 in this case). So you are not missing any feature's now.

Ok, we need to replace that file asap.

**Comment by GreatApo** [comment]
I think the problem will be fixed with a new release.
