### ISSUE TITLE
A few enhancements to notifications/replies

### ISSUE THREAD

**Issue by lfom** [AmazMod/AmazMod#47]
- [x] Notification should be closed or dismissed when a reply is sent, or at least give some feedback that message was sent;
- [ ] Add app icon to the notification on watch;
- [ ] Text of multiline canned replies are being cut off (button doesn't expand to show all content).

**Comment by fcaronte** [comment]
With " Add app icon to the notification on watch" you mean to make a notification when I receive a notification and don't do nothing? At now if I don't read a notification immediately I'm lost it and can't read anymore. It's the same for you?

**Comment by lfom** [comment]
The idea, for now, is to send both notifications, so you can reply using CustomUI and still manage notifications using the watch. 

@fcaronte do you have a Telegram account? you'd be very welcome in the beta test group.

**Comment by fcaronte** [comment]
Yes I've reinstalled it with @fcaronte user name

**Comment by diotto** [comment]
Done long time ago.
