### ISSUE TITLE
Screenshot colors

### ISSUE THREAD

**Issue by mplx** [AmazMod/AmazMod#471]
It's no big deal but I'm curious - why are screenshot colors incorrect?

| Icon | Screenshot | Watch |
| - | - | - |
| Overview | Green | Green |
| Pulse rate | Blue | Red |
| Sport | Blue | Red |
| Sleep | Red | Blue |

![pic1](https://user-images.githubusercontent.com/1986588/55671474-acd9ca80-5890-11e9-9773-236c61c0969a.png)
![pic2](https://user-images.githubusercontent.com/1986588/55671475-aea38e00-5890-11e9-907b-59f05bc965d5.jpg)

`AmazMod 1.1.5` `AmazMod Service 1891` `Model A1811` `Firmware 3.2.1.0`

**Comment by diotto** [comment]
It's related to operating system, and not amazmod. We found a workaround and implemented it, also the upside down bug in verge was fixed too. It still needs more testing and maybe optimizations, but probably in next version it'll be fixed

**Comment by mplx** [comment]
Thanks for the follow-up. Looking forward for the release! :)

**Comment by GreatApo** [comment]
Related closed issue: https://github.com/AmazMod/AmazMod/issues/456
Color fix: commit ea4d9dd3cd273248d7ac0928b2c65b16a27f8e05
Rotate done: commit c12e82d0412d73dc14215e6f3c65036b50887c42
