### ISSUE TITLE
Connect/Disconnect alert options (duration/vibration)

### ISSUE THREAD

**Issue by dibg** [AmazMod/AmazMod#475]
Yesterday i lost my phone while cycling. Normal disconnect alert vibration is not engough to notify the user while exercising. I propose a option in the menu to change the duration from 1 seconds up to 5 seconds. Also a alternative 3 short vibration can do the trick. Thats a simple addition that will save couple of phones from thiefs and bad luck. I wish that this future was available yesterday.

**Comment by dibg** [comment]
In addition to the watch vibrating, also the phone can play a selectable sound for a selectable duration if the watch disconnectes. If it's possible to overwrite silence profile like the amazfit app does when you request to find your phone even better. Point in case, if they stole your phone in the bus, your reaction time will make all the difference.

**Comment by 4eGuevara** [comment]
By the way, about silence profile and disconnect/connect vibration during it - can you make that watch don't vibrate about disconnect/connect when silence active???

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Connect/Disconnect alert options (duration/vibration)](https://trello.com/c/Jyz9SHg2/29-connect-disconnect-alert-options-duration-vibration)
