### ISSUE TITLE
Maps notifications don't work

### ISSUE THREAD

**Issue by renzettis** [AmazMod/AmazMod#477]
Tested because written in changelog but doesn't worked

Service: v1891

**Comment by fcaronte** [comment]
![image](https://user-images.githubusercontent.com/26366403/56736508-9c6a9080-6768-11e9-82ce-c0f8eb641c1a.png)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maps notifications don't work](https://trello.com/c/R6cXrZvG/30-maps-notifications-dont-work)

**Comment by fcaronte** [comment]
Work on last Dev branch
