### ISSUE TITLE
Add heart-rate measurement

### ISSUE THREAD

**Issue by GreatApo** [AmazMod/AmazMod#480]
To take heart-rate measurements we need to manually use the sensor. All the needed info are at: WearHealth.apk/com.huami.watch.heartrate.MeasureHeartRateActivity

The heart-rate sensor is 21:
```
this.mSensorManager = (SensorManager) getSystemService("sensor");
this.mHeartrateSensor = this.mSensorManager.getDefaultSensor(21);
```
It seems that we need to get new values and wait for a good accuracy...

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add heart-rate measurement](https://trello.com/c/38x1hANw/31-add-heart-rate-measurement)

**Comment by 1immortal** [comment]
do we want to add this as a user called activity to the HR graph? tap to measure?
