### ISSUE TITLE
Feature Request: Add ability to (force) update service running on watch 

### ISSUE THREAD

**Issue by rafilkmp3** [AmazMod/AmazMod#482]
I am with the cable right now, received the playstore update then I pushed the apk to the watch but i cant force update the AmazMod-service to latest version .

I tried through run comand on amazmod app but i got the following error : 
`pm install -r -d  /sdcard/AmazMod-service-1891.apk`

![image](https://user-images.githubusercontent.com/12433667/55845953-4bc52780-5b1a-11e9-9029-0f87c8349b8e.png)

Can we have a button to update the service instead waiting a notification ?

**Comment by rafilkmp3** [comment]
I am able to workarround holding in the file manager the apk and the install app was presented to me

**Comment by GreatApo** [comment]
Try
`adb install -r /sdcard/AmazMod-service-1891.apk`
