### ISSUE TITLE
Ungrouped notifications not removed from watch when read on phone

### ISSUE THREAD

**Issue by alexagr** [AmazMod/AmazMod#488]
In the latest Amazmod version 1.1.5 ungrouped custom notifications are not removed from the watch when read on the phone. Option "Disable remove notifications" is turned off.
In case this matters - my phone is Xiaomi Mi8 SE with MIUI 10.2.2.0 (xiaomi.eu) and most of my notifications are from WhatsApp.

**Comment by InsertCoinPls** [comment]
This happen to me too. It's very annoying.

**Comment by alexagr** [comment]
Is there anything that I can do to help with the fix? Any logs to collect? Any debug version to run? It's really annoying to manually clean up notifications every day...

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ungrouped notifications not removed from watch when read on phone](https://trello.com/c/bDZMNzur/32-ungrouped-notifications-not-removed-from-watch-when-read-on-phone)

**Comment by lfom** [comment]
It worked with standard ui already, was added to custom ui in current dev branch. it seems to work properly, please reopen if needed.

**Comment by alexagr** [comment]
The problem still exists on version 1902.
Notifications read on phone (Mi8SE, MIUI 10.2.3.0) are not removed from the watch.

**Comment by lfom** [comment]
> The problem still exists on version 1902.
> Notifications read on phone (Mi8SE, MIUI 10.2.3.0) are not removed from the watch.

What apps, exactly? Some apps can't sync with watch since they don't use "standard" notifications or the use the same ID for every notification? If it still happens, please add a screenshot with the Notifications Log in AmazMod showing the ones that weren't synced.
