### ISSUE TITLE
Add filters for Notifications

### ISSUE THREAD

**Issue by lfom** [AmazMod/AmazMod#49]
For enabled apps, users should be able to create filters to block notifications. For instance, create a filter to not display notifications of FB apps with "requested to join" to block notifications of new requests to join a group.

**Comment by diotto** [comment]
It would be great the possibility to replace notification title and text using RegExp.

**Comment by diotto** [comment]
Solved in commit [2debf86](https://github.com/AmazMod/AmazMod/commit/2debf86b7a043232f8c8d9eaf840c1eac0cee91b)
