### ISSUE TITLE
Amazmod crash since 1890 and 1891 

### ISSUE THREAD

**Issue by Kookie69** [AmazMod/AmazMod#497]
Has anyone else had this issue since 1890 where about once every day or second day the Amazmod app crashes cause a massive battery drain if you don't catch it and restart the watch then it is fine again and never had this issue with 1880 and before that and i have seen 1 other in the community with the same issue so i'm not the only 1 so i hope this can be looked into as this app has been awesome on my Stratos thanks.

**Comment by GreatApo** [comment]
Can we have a log to scan for the error?

**Comment by GreatApo** [comment]
I am closing this issue as further information were not provided. Please, comment again if the problem persists in the lattest versions.
