### ISSUE TITLE
GPX/TCX direct export into Strava / other services

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#50]
if possible, it would be great to be able to export directly from the Amazmod app the activity to GPX/TCX and via 3rd services API to import it into the relevant service, like Strava / Endmondo / Runtastic etc

**Comment by diotto** [comment]
We can export tcx/gpx bit to transfer it to watch we need #285 to be fixed. It's a blocker.

**Comment by dcaldr** [comment]
Ok, so as i'm getting through my English- right now there isn't function to auto sync everything to google Fit nor Runtastic?

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GPX/TCX direct export into Strava / other services](https://trello.com/c/IpOnlFkW/4-gpx-tcx-direct-export-into-strava-other-services)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GPX/TCX direct export into Strava / other services](https://trello.com/c/RYJNDQnM/6-gpx-tcx-direct-export-into-strava-other-services)

**Comment by Fernandofat** [comment]
Hi guys, I am a developer, how can I help to achieve this? I have the watch and the lack of a relevant platform support like Strava, Endomondo, etc is a HUGE pain.

Please let me know how can I help.

**Comment by lfom** [comment]
> Hi guys, I am a developer, how can I help to achieve this? I have the watch and the lack of a relevant platform support like Strava, Endomondo, etc is a HUGE pain.
> 
> Please let me know how can I help.

Pull requests are welcome. But how isn't Strava supported? It works very well with all activities with GPS data (of course). Other services as well as supports for non-GPS activities is available via third party apps.

**Comment by 1immortal** [comment]
Right now Strava is supported on all major "sports" models, GPX and TCX exports are possible via unofficial Amazfit apps such as the AeX project.
