### ISSUE TITLE
Lists of notifications in watch on main screen

### ISSUE THREAD

**Issue by 4eGuevara** [AmazMod/AmazMod#514]
Can you make an option to show lists of notification on watch where the standard notification shown (on main screen below by the swipe)?

**Comment by GreatApo** [comment]
If we could, we would have done it :P

**Comment by 4eGuevara** [comment]
Ok))))

**Comment by 4eGuevara** [comment]
Very strange. I found on 4pda post, where is user using 1891 ver has notification on main screen with disabled notification in amazfit http://4pda.ru/forum/index.php?showtopic=918703&view=findpost&p=84561498

**Comment by GreatApo** [comment]
Sorry, I thought you wanted to see the custom notifications there.

There are 3 ways you can manage notifications:
- Let Amazfit do it (you need to turn Amazmod "Disable Notifications" on)
- Amazmod stock notifications (just leave the "Disable Notifications" off and close the Notifications from Amazfit)
- Amazmod with Custom UI Notifications (Enable Custom UI notifications and close the Notification from Amazfit)

The first 2 will show the notifications in your main screen when you swipe up.

**Comment by 4eGuevara** [comment]
Ok, thx, now I understand!

**Comment by danki2** [comment]
@GreatApo is there any option to enable the notifications when swipe up when the Custom UI Notifications is on?
