### ISSUE TITLE
Filter apps or mute senders from notification on watch

### ISSUE THREAD

**Issue by lfom** [AmazMod/AmazMod#52]
Idea: user can swipe left on a notification and a new screen will be presented with the options to permanently disable notifications for the app (remove from apps list that send notifications to watch) or mute the sender of the same type of notifications for pre-determined times: 15min, 1h, 1day.

**Comment by diotto** [comment]
Fixed in [f244d56](https://github.com/AmazMod/AmazMod/commit/f244d5611bc2d6c6543360ccfb683a7008f01d96)
