### ISSUE TITLE
Workaround to avoid long process update

### ISSUE THREAD

**Issue by fcaronte** [AmazMod/AmazMod#520]
I found a trick to "fix" the long update process and go from 20m\1h to only 3\5 minutes
I use paceon app to stay screen on dimmed during installation process (we can use amazmod same features because during installation can't work) so we need to find something with wakelock during installation process (or something like that)

**Comment by ahsim** [comment]
AmazMod already has this function
on start:
wakeLockDim.acquire(60*60*1000L /*1 hour*/);
on finish:
wakeLockDim.release();

But I dont know is how to detect start and finish.
And my suggestion also to add vibration at finish

**Comment by fcaronte** [comment]
I don't know if is call wakelock but with enabled screen is more fast. As now take 1hour on my pace device

**Comment by diotto** [comment]
> 
> 
> AmazMod already has this function
> on start:
> wakeLockDim.acquire(60_60_1000L /_1 hour_/);
> on finish:
> wakeLockDim.release();
> 
> But I dont know is how to detect start and finish.
> And my suggestion also to add vibration at finish

Can't be done because during upgrade process amazmod is killed. The wakelock should be done using install.sh script. 
Maybe creating a wakelock using some shell command ?

Found this in stackoverflow:

shell command to acquire a wake lock

  echo lock_me > /sys/power/wake_lock

shell command to release the same wake_lock

  echo lock_me > /sys/power/wake_unlock

Can someone test if this works ?

**Comment by diotto** [comment]
Post with more commands: https://stackoverflow.com/questions/5780280/how-can-i-see-which-wakelocks-are-active

**Comment by fcaronte** [comment]
if i try this command,

adb shell "echo AmazMod_UPDATE > /sys/power/wake_lock"

then i try to see wake lock with this

adb shell "cat /sys/kernel/debug/wakeup_sources"
![image](https://user-images.githubusercontent.com/26366403/56523032-4a96f000-6547-11e9-87c9-ce55fca9cae4.png)


i see that wakelock is active

adb shell "echo AmazMod_UPDATE > /sys/power/wake_unlock"
![image](https://user-images.githubusercontent.com/26366403/56522854-1a4f5180-6547-11e9-9a49-cd7e4a9aa401.png)
wakelock timer go to 0 (Active Since)

i try to add that command on update_service_apk.sh but i don't know how to track

**Comment by fcaronte** [comment]
i try with enabling previus command to make the wakelock and then try to install an apk with locked screen and take only 30second!!! and i see amazmod complete install popup. after disabling again wakelock i try same apk same situation and after 2minutes nothing done and installation finish only after i manually unlock the screen. i think is the right road :)

**Comment by fcaronte** [comment]
i've update script and start Working correctly with the wakelock and installation is fast,  i'm making other test because sometime is not catch the wakelock release, maybe i need to add some waiting time to the script

**Comment by fcaronte** [comment]
seem that script work correctly for normal apk install, but on amazmod install, enable wakelock but after reboot script switch off and so is not disable wakelock :(

**Comment by fcaronte** [comment]
Fixed ad push a pull request :)
