### ISSUE TITLE
Add dialog "Hide app?" by long click on app icon on main widget in the watch

### ISSUE THREAD

**Issue by ahsim** [AmazMod/AmazMod#522]
To prevent accidental removing favorite apps while sliding.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add dialog "Hide app?" by long click on app icon on main widget in the watch](https://trello.com/c/D7HTQ3Gq/33-add-dialog-hide-app-by-long-click-on-app-icon-on-main-widget-in-the-watch)

**Comment by lfom** [comment]
Long click isn't suitable for widget as usually is is triggered when swiping the widget as well. A menu will be create to handle customization in the future. Closing.
