### ISSUE TITLE
Delay after vibration

### ISSUE THREAD

**Issue by antares10** [AmazMod/AmazMod#532]
Hi!

I noticed that sometimes after the vibration on the watch the notification has a delay. Sometimes about 10 seconds. Sometimes it work right after the vibration, but randomly between 0-10 sec. I use custom notifications.

Here is a logcat:

> 04-23 18:06:57.082 986-999/com.amazmod.service D/AmazMod: MainService action: incoming_notification
04-23 18:06:57.082 986-999/com.amazmod.service D/AmazMod: MainService onDataReceived: com.amazmod.service.events.incoming.IncomingNotificationEvent@220fef1a
04-23 18:06:57.247 986-986/com.amazmod.service D/AmazMod: MainService incomingNotification vibration: 200
04-23 18:06:57.272 986-986/com.amazmod.service D/AmazMod: MainService incomingNotification: amazmod.com.transport.data.NotificationData@23beea4b
04-23 18:06:57.272 986-986/com.amazmod.service E/AmazMod: DnD lowSDK exception: android.provider.Settings$SettingNotFoundException: zen_mode
04-23 18:06:57.273 986-986/com.amazmod.service D/AmazMod: NotificationService notificationSpec.getKey(): amazmod|test|999
04-23 18:06:57.273 986-986/com.amazmod.service D/AmazMod: NotificationService1 notificationSpec.getKey(): amazmod|test|999
04-23 18:06:57.273 986-986/com.amazmod.service D/AmazMod: NotificationService postWithCustomUI: 6
04-23 18:06:58.063 986-986/com.amazmod.service I/AmazMod: NotificationFragment newInstance key: amazmod|test|999|1556035617273
04-23 18:06:58.064 986-986/com.amazmod.service D/AmazMod: NotificationWearActivity startTimerFinish
04-23 18:06:58.064 986-986/com.amazmod.service I/AmazMod: NotificationWearActivity onCreate key: amazmod|test|999|1556035617273 | mode: add | wasLckd: false | mustLck: false | scrTg: false
04-23 18:06:58.130 986-986/com.amazmod.service I/AmazMod: NotificationFragment onAttach context: android.app.ContextImpl@1e54772
04-23 18:06:58.130 986-986/com.amazmod.service I/AmazMod: NotificationFragment onCreate: key amazmod|test|999|1556035617273 | mode: add
04-23 18:06:58.130 986-986/com.amazmod.service I/AmazMod: NotificationFragment onCreateView
04-23 18:06:58.505 986-986/com.amazmod.service I/AmazMod: NotificationFragment onViewCreated
04-23 18:06:58.505 986-986/com.amazmod.service I/AmazMod: NotificationFragment updateContent context: android.app.ContextImpl@1e54772 | key: amazmod|test|999|1556035617273
04-23 18:06:58.505 986-986/com.amazmod.service I/AmazMod: FragmentUtil defaultLocale: en
04-23 18:06:58.596 986-986/com.amazmod.service D/AmazMod: DeviceUtil isVerge: checking if model A1619 is an Amazfit Verge: false
04-23 18:06:58.596 986-986/com.amazmod.service I/AmazMod: NotificationFragment loadReplies
04-23 18:06:58.865 986-986/com.amazmod.service I/AmazMod: NotificationFragment updateContent try
04-23 18:06:58.898 986-986/com.amazmod.service D/Vibrator: UID:10028 opPkg:com.amazmod.service milliseconds200
04-23 18:06:58.898 986-986/com.amazmod.service W/System.err: java.lang.RuntimeException: Vibrator
04-23 18:06:58.899 986-986/com.amazmod.service W/System.err:     at android.os.SystemVibrator.vibrate(SystemVibrator.java:72)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at android.os.Vibrator.vibrate(Vibrator.java:80)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at android.os.Vibrator.vibrate(Vibrator.java:65)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at com.amazmod.service.ui.fragments.NotificationFragment.updateContent(NotificationFragment.java:263)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at com.amazmod.service.ui.fragments.NotificationFragment.onViewCreated(NotificationFragment.java:119)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:908)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:834)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
04-23 18:06:58.900 986-986/com.amazmod.service W/System.err:     at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
04-23 18:06:58.901 986-986/com.amazmod.service W/System.err:     at android.support.wearable.view.FragmentGridPagerAdapter.finishUpdate(FragmentGridPagerAdapter.java:227)
04-23 18:06:58.901 986-986/com.amazmod.service W/System.err:     at android.support.wearable.view.GridViewPager.populate(GridViewPager.java:1214)
04-23 18:06:58.911 986-986/com.amazmod.service W/System.err:     at android.support.wearable.view.GridViewPager.populate(GridViewPager.java:1064)
04-23 18:06:58.911 986-986/com.amazmod.service W/System.err:     at android.support.wearable.view.GridViewPager.onMeasure(GridViewPager.java:1375)
04-23 18:06:58.911 986-986/com.amazmod.service W/System.err:     at android.view.View.measure(View.java:17547)
04-23 18:06:58.911 986-986/com.amazmod.service W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.view.View.measure(View.java:17547)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.view.View.measure(View.java:17547)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.support.wearable.view.BoxInsetLayout.onMeasure(BoxInsetLayout.java:147)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.view.View.measure(View.java:17547)
04-23 18:06:58.912 986-986/com.amazmod.service W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at android.view.View.measure(View.java:17547)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2648)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at android.view.View.measure(View.java:17547)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
04-23 18:06:58.913 986-986/com.amazmod.service W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
04-23 18:06:58.914 986-986/com.amazmod.service W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
04-23 18:06:58.914 986-986/com.amazmod.service W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5904)
04-23 18:06:58.914 986-986/com.amazmod.service W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
04-23 18:06:58.914 986-986/com.amazmod.service W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
04-23 18:06:58.914 986-986/com.amazmod.service W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:550)
04-23 18:06:58.914 986-986/com.amazmod.service W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
04-23 18:06:58.943 986-986/com.amazmod.service W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
04-23 18:06:58.943 986-986/com.amazmod.service W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-23 18:06:58.943 986-986/com.amazmod.service W/System.err:     at android.os.Looper.loop(Looper.java:135)
04-23 18:06:58.943 986-986/com.amazmod.service W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
04-23 18:06:58.944 986-986/com.amazmod.service W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-23 18:06:58.944 986-986/com.amazmod.service W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
04-23 18:06:58.944 986-986/com.amazmod.service W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
04-23 18:06:58.944 986-986/com.amazmod.service W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-23 18:06:59.241 986-986/com.amazmod.service I/Choreographer: Skipped 66 frames!  The application may be doing too much work on its main thread. <

**Comment by ahsim** [comment]
I have same issue

**Comment by GreatApo** [comment]
The errors you see in the log are "normal" and are generated every time the watch vibrates. I think you get the notification after the vibration because it is called first and the a new notification activity is called. 

I can't say that the code is optimized to be fast (haven't check it) but the line "Skipped 66 frames! The application may be doing too much work on its main thread." says it all.

Try to clean your memory and unload your watch a little, that might help.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Delay after vibration](https://trello.com/c/uooe7WVv/34-delay-after-vibration)
