### ISSUE TITLE
Ability to show Whatsapp/Telegram images (enhancement)

### ISSUE THREAD

**Issue by javiermontanov** [AmazMod/AmazMod#547]
Right now, for example, when we receive an image message of whatsapp (let's suppose that a contact is just sending an image message) on the watch's notification we can see:
1. The contact's avatar (little image on top) and the contact's name, this is OK because we're expecting to have this behavior to save space .
2. The image sent is just showed as a default image icon is not the real image.

We should be able to see the real image, is this possible?

**Comment by fcaronte** [comment]
as now is working as you say, you need to enable "show image" to amazmod setting, (not remember the exactly type) and need to have enable the "auto download picture" to whatsapp setting. this feature is a little buggy but you should to see something

**Comment by fcaronte** [comment]
Yes see photo seem to stop working or work rarely

**Comment by fcaronte** [comment]
I think we have problems with this feature, seem to not work anymore. Need investigation

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ability to show Whatsapp/Telegram images (enhancement)](https://trello.com/c/yjbopdqU/36-ability-to-show-whatsapp-telegram-images-enhancement)

**Comment by lfom** [comment]
Still happening in latest dev branch? @fcaronte said he uses an app to test notifications with images, what is it? does it work the same as images from W/T?

**Comment by fcaronte** [comment]
Yes WhatsApp for me is stop working from a lot of time, but I see some guy were still work with WhatsApp and Amazon notification. For me is work with a fake notification test app only

**Comment by fcaronte** [comment]
The app I've use for test is that

https://play.google.com/store/apps/details?id=com.wagner.valentin.notificationmaker2

**Comment by mgo098** [comment]
No.massage received at the  phone

**Comment by lfom** [comment]
It doesn't work anymore with WhatsApps on Android Pie and up (probably Nougat an up, but untested), and simply there is no way to retrieve the image as of now due to Android system limitations. The other apps the use the "common" notification with pictures work fine. Closing.
