### ISSUE TITLE
Greatfit collapses

### ISSUE THREAD

**Issue by Pablo1437** [AmazMod/AmazMod#549]
Widgets that depend on amazmod cause it to stop

**Comment by fcaronte** [comment]
On my pace I can't reproduce that, I try amazmod+greatfit and pacecalendar with sync enabled and all seem to work correctly. Try to take a log

**Comment by GreatApo** [comment]
@Pablo1437 your problem has already been reported on GreatFit [here](https://github.com/GreatApo/GreatFit/issues/40).

GreatFit hasn't been updated for a while because I have been busy.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)
