### ISSUE TITLE
Delay sending notification to Watch (feature request)

### ISSUE THREAD

**Issue by Galwayguy** [AmazMod/AmazMod#554]
Could there be a short say 30 second delay from a notification arriving on the phone & going to the watch. Often the phone is close & I can dismiss the notification on the phone. This would reduce the number of watch notifications saving battery etc

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Delay sending notification to Watch (feature request)](https://trello.com/c/lh7hzadI/37-delay-sending-notification-to-watch-feature-request)

**Comment by lfom** [comment]
There is a problem with this: either it will drain phone battery to make sure it will wait 30s while app is in the background, or there is no way to make sure it will last exactly 30s (usually system postpones background services, specially on EMUI/MIUI).
