### ISSUE TITLE
watch display does not turn on after update 1894

### ISSUE THREAD

**Issue by digaodyck** [AmazMod/AmazMod#563]
right after installing service 1894, the watch display did not turn on by specific moving as before. It is really hard to see anything on it when it's dark.

**Comment by GreatApo** [comment]
You mean when you raise your hand? When custom/standard notifications arrive?

**Comment by digaodyck** [comment]
when I raise my hand and also by pressing a button at night. It worked fine with 1893. I have a stratos watch.

**Comment by fcaronte** [comment]
Try disable and enable again that option and power off few minutes and switch on again

**Comment by banhegyinorbert** [comment]
Strange. I have a Stratos too. Hand raising works for me. But the middle button is dead here too.

**Comment by digaodyck** [comment]
oh, yeah, that worked. It seems it was just hung. Thanks a lot!!!

**Comment by fcaronte** [comment]
Good, full reboot usually fix everything 🤣 we close for now 👍🏻

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)
