### ISSUE TITLE
Notification reply not sent for real

### ISSUE THREAD

**Issue by fcaronte** [AmazMod/AmazMod#565]
We have problem with whatsapp/telegram reply from stored notifications. I try to understood when append this but sometime, or with group chat (i not understood for now) i open a stored notification, reply and see the reply is sent confirm but no real message are sent. here the log, and maybe the photo of the place could be the problem
[noreply.txt](https://github.com/AmazMod/AmazMod/files/3149909/noreply.txt)
![8b0921a1-951b-45ca-8056-bbd893648b23](https://user-images.githubusercontent.com/26366403/57256532-24994180-7057-11e9-9688-bf923f52b246.jpg)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notification reply not sent for real](https://trello.com/c/Hj8l7oMU/40-notification-reply-not-sent-for-real)

**Comment by diotto** [comment]
@fcaronte was the notification already removed from phone? IMO that DeadException may be a tip that the notification is not available on phone anymore

**Comment by fcaronte** [comment]
yes is removed, but is not the problem, for example now i try to reply to a group whatsapp notification from yesterday and work correctly. i don't understood when work or not and why

**Comment by fcaronte** [comment]
For now seem to not appended anymore, close for now.
