### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by banhegyinorbert** [AmazMod/AmazMod#566]
Hello,
Since the last update (1894) my battery drops from 100% to ca. 28% during the night. Even if my internet connection is off on the phone and the watch is not on my arm.
The first occasion was yesterday after I installed the latest version on my watch throught the phone app.
What can be the problem?
thanks, 
Norbi

**Comment by fcaronte** [comment]
Have you try with a full shout down and switch on again? Is not normal this drain and I not ear about this problem from other user

**Comment by banhegyinorbert** [comment]
I have rebooted the phone 2x, but seemed like nothing would work. Perhaps some background process was going on.
http://imgur.com/5IaKPxk
Can we find it out from any log file?

**Comment by fcaronte** [comment]
have you install a new watchface apk ?

**Comment by banhegyinorbert** [comment]
Nope. Only the new update to the watch.

**Comment by 1immortal** [comment]
please check your watch in flight mode mode

**Comment by banhegyinorbert** [comment]
Same sh*t is happening:
http://imgur.com/rFS8nIh

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Battery drain](https://trello.com/c/xCJAEEaT/41-battery-drain)

**Comment by JanHavel** [comment]
@1immortal and others
please can u share your median battery life and what have you already installed?

** Stratos: usually my battery holds +- only 18hours**
Installed:
- AmazMod
- GreatFIt (watchface) (+ few older WFZ faces) 
- Calculator, Keyboard Touchone, MyWatchNotes, PaceCalendarWidget

![image](https://user-images.githubusercontent.com/22323884/58085134-7051fc00-7bbc-11e9-856c-e5c7e5ac4ac4.png)

![image](https://user-images.githubusercontent.com/22323884/58085270-b4450100-7bbc-11e9-8236-d66ef8e52965.png)

**Comment by lfom** [comment]
![IMAGE 2019-06-30 14:35:03](https://user-images.githubusercontent.com/15659999/60400011-505f1200-9b44-11e9-98e1-6d0cec3f9a9a.jpg)

Latest dev branch build (battery graph disabled on phone).

**Comment by fcaronte** [comment]
we close for now
