### ISSUE TITLE
Interval training

### ISSUE THREAD

**Issue by banhegyinorbert** [AmazMod/AmazMod#569]
Hello guys,
The builtin interval training option in Amazfit app refreshes the pace alert very poorly. Since the GPS technology is the same as in Garmin as far as I know, the implementation of "virtual pacer" is perhaps possible. https://apps.garmin.com/en-US/search?q=Virtual+pacer&appType=&count=30&device=&showAllDevices=false&deviceLimit=&sort=mostRecent
I know nothing about programming, but perhaps we could work together with the Garmin developers.
How to start? What should I tell them about the basic of the Xiaomi OS?

thanks, 
Norbi

**Comment by 1immortal** [comment]
Hi,
You wish to increase the interval of alerts during interval training?

**Comment by banhegyinorbert** [comment]
Hi!
I wish to have alerts triggered by hitting the value. At the current setup I get alerts ca. every 1km and e.g. for a 0.2km interval it is not enough. Is there an existing solution?

**Comment by 1immortal** [comment]
no, and i'm doubtful about the ability to tap in into mid training and poping alerts during it by Amazmod

**Comment by banhegyinorbert** [comment]
Sorry! I didn't mean that I want custom alerts during the workout. But to get an interval sub-app in Amazmod, which gives alerts better, than the builtin one. And get alerts when my pace is out of the range set.

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Interval training](https://trello.com/c/XeLwGDFt/43-interval-training)

**Comment by diotto** [comment]
Sorry, but it's something that should be done in the ROM, not in an addon app like AmazMod. Unfortunatelly we can't help.

**Comment by banhegyinorbert** [comment]
Ok! Thanks a lot!
