### ISSUE TITLE
Music sync & music player

### ISSUE THREAD

**Issue by divsln** [AmazMod/AmazMod#572]
I just suggest and maybe you could do this.
1.Sync some directory on the phone,with music in my case, automatically,if new track in folder music was added,it will automatically synchronization with watch memory.
2. If music playing on the phone,show player control on all screen,after unlock you can with swipe control next track with swipe on right, previous track with swipe on left,and volume up or down with swipe to top or to bottom.
Thanks for all you work!

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature request](https://trello.com/c/wwTXzld2/44-feature-request)

**Comment by lfom** [comment]
1. probably it won't happen as Bluetooth file transfer isn't reliable as we don't have access to Bluetooth stack directly;
2. System tray/drawer cannot be used (or you can use music control from stock Amazfit, so how it would be different?), we could use an overlay button like what is used as of now in current dev branch, but this would make part of the (small) screen not available for touches and it would increase battery usage somewhate even if used only while screen was on.
