### ISSUE TITLE
Notification counter

### ISSUE THREAD

**Issue by mplx** [AmazMod/AmazMod#574]
I'm not sure what the notification counter actually is supposed to do (other than counting total number of notifications which it seems to do so), so it *might* be a bug (`Service 1894`, Watch `A1811/Verge`):
- CustomUI disabled: constantly increases with each notification received.
- CustomUI enabled: does **not** increase when notification is received.
- Never decreases when notifications are read (in stock notification reader). Starts with 0 when restarting the watch.
- Touching it _always_ shows a screen with text "empty".

![ss_20190515_131210246](https://user-images.githubusercontent.com/1986588/57786997-da8a1d00-7734-11e9-9df6-a848ac8e64f0.png)

![ss_20190515_131237922](https://user-images.githubusercontent.com/1986588/57787002-dd850d80-7734-11e9-8de0-05212ec7340f.png)

**Comment by lfom** [comment]
Already fixed in current dev branch.

**Comment by williknow** [comment]
I have experienced a similar issue. Just now the counter says 3. When I touch it it opens a list with 5 notifications. But I have read this notifications on the phone. They should not be there any more.

**Comment by lfom** [comment]
As I said, it is fixed in dev branch, you can try a bleeding edge build or wait for new release. Closing.
