### ISSUE TITLE
Custom notifications UI dont dismissed

### ISSUE THREAD

**Issue by lvalladares** [AmazMod/AmazMod#575]
I've a problem with the custom UI.

Even if i haven't marked the ungroup notifications, they get ungrouped and when (for example) i open a whatsapp conversations with 20 messages, of the 20 notifications on the watch only 1 gets erased and the other 19 still there

Also, a suggestion: It would be nice if i can dismiss notifications only by swip (like default app) or it would be even better if the auto-response could be integrated in the default UI (i dont think this is possible)

Im using service 1894 and app 1.1.6 Build 212

**Comment by lfom** [comment]
1. was added to current dev branch
2. probably it will never be added as swipe is used to dismiss the notifications log.

**Comment by lfom** [comment]
Closing, as swipe probably won't be added due to technical issues and customUI syncing was added to dev branch already and seems to work fine (most of the time).
