### ISSUE TITLE
Ability to add edit locations

### ISSUE THREAD

**Issue by marcospiridon** [AmazMod/AmazMod#579]
New location widget/app only allows locations to be added with current location. An improvement to this is to be able to add new locations that are not the current one or edit coordinate of existing locations. This can be useful for several cases, like navigation, Geocaching etc.
Amazmod can enable such locations editor.

**Comment by lfom** [comment]
I did a quick research and it seems that the data is stored in a database inside the app which isn't available for third party apps, so it it does not look like it is possible...

**Comment by marcospiridon** [comment]
Thank you @lfom for you interest.
I think there are a lot of uses for this functionality, like geocaching, where we want to load our geolocations/coordinates at home into the watch and navigate afterward. But as it is currently, where you have to be at the location to store it it just serves the purpose of where did I park my car kind of use cases, which it's useful, but limited.
Do you think its possible to access that database if we allow root access in the amazmod widget?

**Comment by lfom** [comment]
Probably, you can copy the db, edit it then move it back and restart the app.. I tried using backup/restore, and it didn't work... It actually has some unused fields in the db.
