### ISSUE TITLE
Sporadic welcome to Amazmod wizzard on watch

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#592]
Every now and then i have a wizzard of "welcome to Amazmod" appearing on watch.
Only the service is installed.
Happens on 1894
logcat attached
[logcat2.txt.gz](https://github.com/AmazMod/AmazMod/files/3244614/logcat2.txt.gz)

**Comment by diotto** [comment]
Hello @1immortal , unfortunatelly i cant reproduce your error.
Made a commit trying to fix it

**Comment by 1immortal** [comment]
thank you kind sir @diotto

**Comment by diotto** [comment]
So, is the bug fixed? Are you not welcome anymore 🤣 ? Can we close issue @1immortal ?

**Comment by 1immortal** [comment]
da, issue fixed, i'm not welcome anymore, switching to some other app that will be happy to see me every time.
:'(
