### ISSUE TITLE
Last connected location (watch lost)

### ISSUE THREAD

**Issue by GreatApo** [AmazMod/AmazMod#594]
Considering the fact that I might implement a feature utilizing location data (in order to calculate Sunrise/Sunset), we can track the last location of the watch (that was connected to Amazmod).

Then we could provide this point along with the location of the next location measurement (if different) on a map in order to track the "lost" location.

I am suggesting a phone-side location data retrieval.

**Comment by 1immortal** [comment]
wouldn't it drain a little more the battery of the watch, as an ongoing location monitoring by the GPS?

**Comment by GreatApo** [comment]
> wouldn't it drain a little more the battery of the watch, as an ongoing location monitoring by the GPS?

That's why the GPS tracking should be phone-side. Moreover, it can be default off and users could enable/disable it.

Additionally, the information can be passed in the watch, to find the phone last connected location.
