### ISSUE TITLE
Enable watchface from amazmod

### ISSUE THREAD

**Issue by fcaronte** [AmazMod/AmazMod#595]
I think would be a good feature to can enable as current watchface when you sent to the watch using amazmod and maybe add a long press on wfz\apk with as "set as active"

**Comment by diotto** [comment]
Done for WFZ files
Do we really need that for APK too ?

**Comment by fcaronte** [comment]
Stock app can do it, but probably we can do that only if is easy to check if an APK was a watchface

**Comment by fcaronte** [comment]
probably for apk could be good to have an "install and set as active" button
