### ISSUE TITLE
Submit AmazMod to F-Droid

### ISSUE THREAD

**Issue by mplx** [AmazMod/AmazMod#606]
Did you consider [submitting](https://f-droid.org/en/contribute/) AmazMod to F-Droid? I can't tell if AmazMod is finally a valid app according to their [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) but I guess it be would so?

- [Easy way](https://gitlab.com/fdroid/rfp/issues)
- [Fast lane](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md)

**Comment by 1immortal** [comment]
due to libs by huami, i think that it will be somehow problematic to submit it there ... @diotto @lfom your toughts?

**Comment by mplx** [comment]
are those linked statically? so you will be right :( - AFAIK it can only be included when the complete app can be compiled with freely available software...

**Comment by diotto** [comment]
Huami Libs are not open source. Maybe it's a problem to have it on fdroid.

**Comment by mplx** [comment]
are those statically linked to the apk, or are these some kind of dynamically linked, ie. the apk just calls them and they have to exist from another app?

**Comment by GreatApo** [comment]
> are those statically linked to the apk, or are these some kind of dynamically linked, ie. the apk just calls them and they have to exist from another app?

Statically...

**Comment by 1immortal** [comment]
@diotto @lfom ?

**Comment by lfom** [comment]
It cannot be posted there, it uses 3rd party libs linked statically... Probably we can submit it to APKMirror and/or APKPure and UptoDown.
