### ISSUE TITLE
App doesn't use own fonts system-wide

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#616]
AFAIK, i know that we have our own font in the system, but its not being used everywhere in the app.
If there's an option of adding fonts, maybe we can add an option of using it everywhere in the app, and even letting the end user to select their own fonts?

**Comment by lfom** [comment]
The system font isn't used in the phone app everywhere? Where it isn't? And why would it be needed/useful besides cosmetics?

**Comment by 1immortal** [comment]
that old Hebrew/Arabic stuff from a year ago - there are some locations in the app that uses the built-in font, and other that relays on the stock, and it some combinations, the "weird" languages are not shown properly.

**Comment by lfom** [comment]
Extra fonts are used only in service, not on phone... If you are seeing different fonts in the phone app, probably it is due to the new localization implementation and/or theming.

**Comment by 1immortal** [comment]
I meant the service, not the phone.

**Comment by 1immortal** [comment]
irrelevant due to service translations available from next release and in the current Edgy builds
