### ISSUE TITLE
Test notification

### ISSUE THREAD

**Issue by otaviobravim** [AmazMod/AmazMod#620]
Hello!

First of all, I would like to thanks everyone that is involved in the development of this app. Its a whole new life to the watch! 

I would like to ask you if is there a way to put a "Test Notification" button somewhere in the settings. I am asking that because I often change my phone's ROM, and sometimes I don't receive notifications on watch and I don't know if this is a ROM issue, or I just messed up the permissions so I have to go and check. Also, sometimes I show Amazmod to people with Pace or Stratos, but I can't show how better is the notification system without asking them to send me something. 

Kind regards

**Comment by lfom** [comment]
There are 3 test notifications in the About -> 3 dots menu (top right).

**Comment by fcaronte** [comment]
Yes we just have this button, go to info, 3dot on top right and here you can find all test notification you need

**Comment by otaviobravim** [comment]
Thanks a lot, I was not an obvious place for me, but now I know!
