### ISSUE TITLE
AmazMod Fails to run on Xihu/Nexo device

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#625]
[amazmod.txt](https://github.com/AmazMod/AmazMod/files/3353725/amazmod.txt)

07-03 14:14:25.386 25303 25303 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.amazmod.service.MainService: java.lang.SecurityException: com.amazmod.service was not granted  this permission: android.permission.WRITE_SETTINGS.

07-03 14:16:52.362 25660 25660 D AmazMod : WidgetSettings.getBoolean(): WidgetSettings getBoolean exception: org.json.JSONException: No value for pref_amazmod_overlay_launcher
07-03 14:16:52.380   655 19637 E DatabaseUtils: Writing exception to parcel
07-03 14:16:52.380   655 19637 E DatabaseUtils: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.

tested with latest dev build of 02/07/2019

**Comment by lfom** [comment]
Did you activate device admin before trying to start AmazMod on watch? If it doesn't work the Android version on Nexo blocks WRITE_SETTINGS and we will have to change a few things in the code...

**Comment by 1immortal** [comment]
he did tried that AFAIK, can't be sure

**Comment by 1immortal** [comment]
[nexo.amazmod.crash.txt](https://github.com/AmazMod/AmazMod/files/3413993/nexo.amazmod.crash.txt)

admin granted, doesn't work

**Comment by diotto** [comment]
It's Android 8, so we need to:

Have the <uses-permission> element in the manifest as normal.

Call Settings.System.canWrite() to see if you are eligible to write out settings.

If canWrite() returns false, start up the ACTION_MANAGE_WRITE_SETTINGS activityso the user can agree there to allow your app to actually write to settings.

In other words, writing to settings is now a double-opt-in (agree to install, agree separately in Settings to allow), akin to device admin APIs, accessibility services, etc.

From https://stackoverflow.com/questions/32083410/cant-get-write-settings-permission

**Comment by lfom** [comment]
I think Pavel granted WRITE_SETTINGS in watch preferences, didn't work.

**Comment by lfom** [comment]
Follow up: Android Oreo requires a bunch of permissions, that can be asked for user to comply on watch but Huami didn't add support for the more "exotic" ones like "overlay draw": it opens the proper screen to grant permission but there is no way to close/go back. Other than this, no adb binary on watch, so many features that rely on this are broken as of now. Last but not least, there is no way to grant Device Admin (my bet is it is a system bug).

**Comment by 1immortal** [comment]
closed due to irrelevance, AmazMod will not be supported on these devices
