### ISSUE TITLE
Use phone internet - internet companion

### ISSUE THREAD

**Issue by whitebird** [AmazMod/AmazMod#626]
For a private app i'm writing I need access to a few internet endpoints. Is it possible to integrate the reverse engineered Amazfit Internet Companion in AmazMod? This way I don't need an extra app running in the background for basic calls.

Thank you in advance.

Source: https://github.com/KieronQuinn/AmazfitInternetCompanion

**Comment by JanHavel** [comment]
Is this connected with this?
https://forum.xda-developers.com/smartwatch/amazfit/mywatchbrowser-simple-browser-pace-t3925303

**Comment by whitebird** [comment]
That's not my response on the forum, no.

**Comment by lfom** [comment]
Added in 10aa74d511d1b60d16617652d34d5a269976677e, please install a bleeding edge build for testing, and close if it works.

**Comment by lfom** [comment]
It seems I dropped the gun very soon, but this should work properly without any changes in your source code.
https://github.com/AmazMod/AmazMod/releases/tag/edgy

**Comment by whitebird** [comment]
Thank you very much for the swift response and testing implementation, I will test it soon.

**Comment by lfom** [comment]
I made a widget myself that uses the same library, and it is working well. To used with AmazMod, you must download the latest bleeding edge build, and enabled the companion support in settings.

**Comment by whitebird** [comment]
Thanks! Do You maybe have a copy of that widget code? Maybe I can use that as a starting point.

**Comment by lfom** [comment]
> Thanks! Do You maybe have a copy of that widget code? Maybe I can use that as a starting point.

https://github.com/KieronQuinn/AmazfitSpringboardPluginExample

**Comment by whitebird** [comment]
> 
> 
> > Thanks! Do You maybe have a copy of that widget code? Maybe I can use that as a starting point.
> 
> https://github.com/KieronQuinn/AmazfitSpringboardPluginExample

Ah yes, I was using that as a test, but it gave me some problems. But you managed to make it work, so I'll look into it a bit more. Thanks!

**Comment by lfom** [comment]
Widget have a few shortcomings that you must keep in mind:
- use simple layouts or you may end with a black screen (I use a Framelayout and then Linearlayouts inside it, avoid Constraint/Relative layouts);
- It runs inside SpringBoard, so you cannot call methods/data that run in your app's own threads. Not even saved settings work.
