### ISSUE TITLE
Need to break phone-watch connection to remove/reinstall service

### ISSUE THREAD

**Issue by EgorOA** [AmazMod/AmazMod#632]
I have noticed recently that there is a need to break phone-watch connection (terminate AmazFit app on the phone) to remove/reinstall service apk on the watch - I think that there is some connection handler in service prevents to do it while connection is alive. Probably it can be done programmatically while remotely reinstalling service from phone?

**Comment by lfom** [comment]
Please expound. I replace service APK on watches using adb install -r all the time and it works always, being connected to phone or not.

**Comment by EgorOA** [comment]
You are right.
Something  wrong is happened with my watch - I can't uninstall service via adb
`C:\ ... \adb>adb uninstall com.amazmod.service`
`Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]`
And I cannot revoke device admin nor with AmazMod Tweaking menu nor with service preferences...

**Comment by ahsim** [comment]
EgorOA, I think I have same problem. How did you uninstall old build? I see only one in app manager

**Comment by EgorOA** [comment]
> EgorOA, I think I have same problem. How did you uninstall old build? I see only one in app manager

I've tried to uninstall service via 'adb uninstall com.amazmod.service' and got an error 'Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]' even using 'Revoke admin' from service settings on the watch
Then I have downloaded .exe from release and tried to uninstall service with it.
Service was uninstalled with reboot. In watch widgets appeared AmazMod 1760 service. Try to uninstall service via 'adb uninstall com.amazmod.service' and got familiar error 'Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]'. Long tap on widget to show menu and Revoke admin. Next try was successfull.

**Comment by lfom** [comment]
Probably you had installed an older version that used Device **Owner** instead of admin. There is no way to revoke it now, either factory reset or install an old build with `adb install -r -d`, revoke device owner and then uninstall.

**Comment by ahsim** [comment]
What older version I need to install for revoke device owner and then uninstall?

**Comment by lfom** [comment]
Much older, one that used Device Owner instead of Device Admin... I think it is pre-1800.
