### ISSUE TITLE
Mijia Smart Home

### ISSUE THREAD

**Issue by Alixil-A** [AmazMod/AmazMod#638]
I'm so new in Amazfit-Verge and AmazMod, So if this is basic or repetitious, sorry for that …
I got my Verge mostly for its ability to connect/control to Mijia Smart Home devices but unfortunately my device is A1811 (Global) and it doesn't have this possibility to do so …
Please advise if there is any way to activate or install MiHome on Verge ???

![d24c21e00e19b8a0fdc7cb320074b29bcopy](https://user-images.githubusercontent.com/52750908/60981132-fe3f9d00-a34a-11e9-8642-87b141e21452.jpg)

**Comment by 1immortal** [comment]
you need to flash this on your watch - 
https://forum.xda-developers.com/smartwatch/amazfit/paceficator-project-verge-3-0-15-0-rom-t3887306
Please note that this will void your warranty
