### ISSUE TITLE
Mute in whatsapp is ignored

### ISSUE THREAD

**Issue by logg-sar** [AmazMod/AmazMod#641]
Hi there

I´m using AmasMod for forwarding Whatsapp-Messages.
In one of this groups is quite a lot of spam ;) so I decided to ignore it.

However - this messages are also forwarded.
Works as designed or error?

Thanks

**Comment by lfom** [comment]
What did you do to "ignore" it?

**Comment by logg-sar** [comment]
https://faq.whatsapp.com/en/android/26000003/

Muting Notifications

**Comment by lfom** [comment]
If you muted Whatsapp and you are still getting notifications, then it is a problem with WhatsApp... AmazMod only pushes the notifications that are displayed on phone to the watch...

**Comment by 1immortal** [comment]
You can create a filter for what you want to mute by selecting the app, tapping it, and adding words as a condition for filtering.
https://youtu.be/sevYnC6EImc

**Comment by logg-sar** [comment]
Well, I´ll leave this closed but:

I checked this double - if whatsapp is muted the cellphone is muted and also the webinterface (via web.whatsapp.com) but not the watch.  If it would be Whatsapp problem it would fail in the cellphone and the webinterface. But it doesn´t

Howeiver - I really didn´t know about this filter. Its not what I´v expected but its working. Thank you for this.

**Comment by lfom** [comment]
You must check your phone/settings definitely: there is no way AmazMod would push a notification to watch if it does not exist on phone. Maybe WhatsApp creates a "silent" notification or creates and destroys it? Anyhow, if it is created on phone, then it is pushed to watch if it fills the requirements in AmazMod settings.
