### ISSUE TITLE
location crash

### ISSUE THREAD

**Issue by yuvalshahar** [AmazMod/AmazMod#644]
hi, I have a brand new Stratos 2.
every time that I'm turning the GPS on by starting an activity or workout the device shutting down / crashes.
when I tried going directly to the menu and turn on the location the device crash again.
a few days ago I have updated the software version to the latest version.
any advice?

[20190715_202955.zip](https://github.com/AmazMod/AmazMod/files/3401664/20190715_202955.zip)

**Comment by 1immortal** [comment]
Hi Yuval, 

it seems like you have a faulty GPS or some issue with the AGPS/location detection.
This is not related by any means to AmazMod.
1. Try to check this issue outside, under the sky, where your watch can detect a valid GPS signal.
2. Update the AGPS config by updating and syncing with the Amazfit application.
3. If any of the above won't work, try to factory reset your watch by going to the phone app, and unpair from the watch menu.

Regards,
AmazMod team

**Comment by yuvalshahar** [comment]
hi,
i have tried all the above but the watch keeps shutting off every time I
start a new activity or turn on the location.
I thought that it might related somehow to Amazmod because its the only
thing that I changed in the past few days.
thanks for the response,
Yuval

‫בתאריך יום ד׳, 17 ביולי 2019 ב-15:54 מאת ‪Pavel Zeldin‬‏ <‪
notifications@github.com‬‏>:‬
