### ISSUE TITLE
Notifications fine tuning font sizing

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#651]
If possible, instead of normal/big/huge sizes, can we set a font size selection by arrows ?
![image](https://user-images.githubusercontent.com/5845985/62004719-517a6380-b131-11e9-9b42-99a811951bb2.png)

**Comment by 1immortal** [comment]
@diotto @lfom what do you think captains?

**Comment by lfom** [comment]
The main problem is that if it is too big it will break layouts... Why would it be useful (any situation where the available sizes aren't enough)? We can use any method to set the size more precisely, the only thing we need to fix is the min/max values...

**Comment by 1immortal** [comment]
i think that the minimum can be set as the stock font size, like the normal right now, and the max can be lets say twice  the size of the Huge mode right now, tunable by 1. can the notifications be warped on the current layout of the actual notification screen?

**Comment by reffu42** [comment]
Not sure if this should go in a new issue, but I built the apk from source after switching the "Large" Font size to 16px (from 18px), and it looks much better. I find it to be more readable at a glance than "Normal" (14px) and much less of it gets cut off than the normal size for Large. I would be happy with just adding "Medium-Large" (or whatever name makes sense) at 16px

**Comment by fcaronte** [comment]
Probably add this intermediate value is the solution 👍

**Comment by fcaronte** [comment]
done, added 3 more intermedie size and add a split setting to have different text size for title and content :)

**Comment by fcaronte** [comment]
Done in commit https://github.com/AmazMod/AmazMod/commit/e5a1cd88ddd92fbb5330408e596bf8b70c0ba6f1
