### ISSUE TITLE
No se agrupan las notificaciones de un mismo remitente

### ISSUE THREAD

**Issue by aKaiLS13** [AmazMod/AmazMod#653]
Estoy encantado con AmazMod!!! Y sobretodo felicitar al equipo de desarrollo.

Cuando recibo varias notificaciones por whatsapp, todas me aparecen de forma individual, de forma que si algun contacto me envia varias, las recibo todas de forma independiente. Se podrian llegar a agrupar??

Muchas gracias y seguid asi!!

**Comment by lfom** [comment]
Either disable "ungroup notifications" or live with that...
