### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by PapsDola** [AmazMod/AmazMod#655]
In dark theme some text are barely visible, that is the txt in navy blue colour.
![Screenshot_20190803-065905_AmazMod](https://user-images.githubusercontent.com/48089044/62407214-47d37e80-b5bd-11e9-8e53-a4ec38e390bc.jpg)

**Comment by lfom** [comment]
Known bug, and that's why it was qualified as "beta".

**Comment by fcaronte** [comment]
we have a fix for that on dev branch. if you want to try you need to remove current version and install prerelease version
https://github.com/AmazMod/AmazMod/releases/tag/edgy
