### ISSUE TITLE
a vibration every hour o'clock

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#658]
Hi, I have a request. Would you be able to introduce the option that the clock comes every hour o'clock?. As they did the casio, that every hour gave two beeps, but with vibrations. And I found an app that does it, but it would be ideal for Amazon to introduce it. The app is called Blip Blip hourly chime. Thank you!

**Comment by fcaronte** [comment]
Added on last Dev version 😁

**Comment by wladOSnull** [comment]
how can i turn on the chime ?

**Comment by fcaronte** [comment]
You need to install the blending edge version and then you will find on service setting on last option

**Comment by wladOSnull** [comment]
I installed latest apps, but can't found settings

**Comment by fcaronte** [comment]
If with last app you mean the official release is not out for now, if you
want to try you need to uninstall and install this version
https://github.com/AmazMod/AmazMod/releases/tag/edgy

Il mer 25 set 2019, 10:12 Wlad <notifications@github.com> ha scritto:

> I installed latest apps, but can't found settings
>

**Comment by fcaronte** [comment]
Have you found it?

**Comment by wladOSnull** [comment]
I'll try to reinstall the app in the evening, and reply to you (i'm a
little busy). Thanks for help)

**Comment by wladOSnull** [comment]
Ok, this work fine.

but now a new desire)
In the future, add a power on screen, when the watch does chime. (like a
photo)

**Comment by fcaronte** [comment]
I don't see the utility of something similar 🤔

**Comment by wladOSnull** [comment]
Ah shit, maybe you right.

I go to sleep, thanks man, amazmod is beautiful app

**Comment by wladOSnull** [comment]
Hm, the sound of the chime disappear
and a phantom vibration appeared (now in 2:06)

Sent from Mail for Windows 10

**Comment by fcaronte** [comment]
I'm wait to receive back my verge and then I can test the sound part

**Comment by wladOSnull** [comment]
strange question. What is type of the hourly chime (vibration) ? ('bzz', 'bzz-bzz' …)

when the hour is even, the clock vibrates once ("bzz") and does not chime. After any time (2, 4, 20 … minutes) the clock vibrates a second time. Reboot does not help.

Sent from Mail for Windows 10

**Comment by fcaronte** [comment]
what you watch? on pace i keep enable all day without problem and a bzz-bzz (two vibration) every hour 1:00, 2:00 etc
now i enable on verge to try with the sound

**Comment by wladOSnull** [comment]
Verge 1 generation

Sent from Mail for Windows 10

**Comment by wladOSnull** [comment]
Fuckin lol, one mute `bzz` again (now is 6:00)

Sent from Mail for Windows 10

**Comment by fcaronte** [comment]
have you check to enable the "tone" volume with no volume you can't see any chime. i test on verge and work two vibration but sound is broken now with verge i can fix it, wait for next commit

**Comment by fcaronte** [comment]
ok now is work with sound, i was miss to enable it  :-P wait for next self build on blending edge and try if work better

**Comment by wladOSnull** [comment]
Omg another problem, i noticed, chime was shutting down on his own (after change any settings , for example: change the volume of messages and ‘chime’ shuts down)
Sent from Mail for Windows 10

**Comment by fcaronte** [comment]
for me seem work, try to update service on your verge

**Comment by wladOSnull** [comment]
Yep, it work (  yet :D  )

Sent from Mail for Windows 10
