### ISSUE TITLE
Connectivity issues with current beta version

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#659]
report by a user
1.1.8/1901 - unable to connect, reverified few times by me
[amazmod.log](https://github.com/AmazMod/AmazMod/files/3468623/amazmod.log)

**Comment by fcaronte** [comment]
He try clean install?
He check if install by error a service APK on phone too
He try to reboot both phone and watch?

**Comment by 1immortal** [comment]
[report1.zip](https://github.com/AmazMod/AmazMod/files/3490270/report1.zip)
[report2.zip](https://github.com/AmazMod/AmazMod/files/3490271/report2.zip)
more logs from disconnection and service crashes:
report1 is from a Galaxy S9 device on 1.1.8 beta with a Stratos 2.3.10.5 running 1901
report2 is from my 7.1.1 device with identical configuration

**Comment by 1immortal** [comment]
@diotto @lfom can you guys have a look please?
On both watches after a while a service error starts to pop, and its impossible to connect to the watch, a memory clear/app relaunch needed on phone for the entire thing to get back working together

**Comment by fcaronte** [comment]
on samsung can you try to check if you add app "telephone" (the samsung one) on amazmod app list? i remember he crash with that setting

**Comment by fcaronte** [comment]
and try to be sure that guys have both app update because can't work as mixed version 1901+1.1.8(build215)

**Comment by 1immortal** [comment]
as of today, after setting the phone app, 1.1.8, to run in the background without getting killed, no errors nor crashes. nothing was changed on the phone app settings.

**Comment by fcaronte** [comment]
close for now if problem appear again we open again this
