### ISSUE TITLE
Custom replies don't work for some apps

### ISSUE THREAD

**Issue by Qufyy** [AmazMod/AmazMod#661]
Currently they work for Viber and Facebook Messenger. Discord and Instagram don't work.

Latest Android version, latest stock watch ROM, latest Amazmod release

**Comment by 1immortal** [comment]
beta release or stable release?
Did they ever work for these 2 apps?

**Comment by Qufyy** [comment]
Stable and no, they never worked

**Comment by diotto** [comment]
Can you please check is these apps support answering directly from the
notification on phone? If not, amazmod can't do that too, as it uses the
notification to answer.

Em qua, 7 de ago de 2019 09:30, Qufy <notifications@github.com> escreveu:

**Comment by Qufyy** [comment]
All of the apps support replying from the notifications, I use it all the time

**Comment by fcaronte** [comment]
I try Instagram replies using AmazMod beta and reply sent correctly for me. Discord never used but should work too

**Comment by lfom** [comment]
Again... It's not enough that the app supports replies in the notification, it must support the standard Android reply method in the standard notification. Many apps use non-standard notifications for their own reasons, and these won't work with AmazMod (for replies, some don't even get their notifications pushed as they use "continuous" or some other weird notifications), Line and Signal are known examples.
