### ISSUE TITLE
Service on watch not updating to 1903

### ISSUE THREAD

**Issue by deadl0ck** [AmazMod/AmazMod#665]
My Watch is on 1902 (which updated fine with no issues) but I now get a notification that version 1903 is available.

I proceed to update as follows:

- Phone downloads the new version
- Phone transfers the new version to the watch
- Watch seems to install the new version OK

After reboot (of both phone and watch) the version on the watch is still being reported as 1902 and I'm prompted again to update.
I've gone through this loop a few times...

**Comment by diotto** [comment]
Hello @deadl0ck , how are you?

Thanks for the feedback. Version 1901 and 1902 are beta and they had a specific bug which doesn't allow you to update using OTA.

As a fix, we suggest you to go to AmazMod Phone App > Tweaking  and execute the following command:

adb install -r /sdcard/AmazMod-service-1903.apk 

If the above solution does not work, unfortunatelly you'll have to update it using a PC:

1. download the APK and manually install adb install -r AmazMod-service-1903.apk on your watch from https://github.com/AmazMod/AmazMod/releases/tag/v1.1.8-217-1903

or 

2. Download the installer from the link mentioned above and install the newer version on top of yours on the watch.

**Comment by deadl0ck** [comment]
Thanks @diotto - I'll see how it goes - I'll close this now as I'm assuming at worst the manual install will work.

**Comment by deadl0ck** [comment]
**adb install** worked
