### ISSUE TITLE
Notification issues with 1902

### ISSUE THREAD

**Issue by deadl0ck** [AmazMod/AmazMod#666]
Hi,

I running 1902 on a Pace with an Honor View 10 (Basically a Huawei phone)

I'm having very sporadic notifications and I often have to stop the app with a "force stop" and restart it.

I have disabled the aggressive memory management that the EMUI version of Android uses on the Huawei/Honor phones and I'm still getting the same results.

Also - I know the actual app is not being killed as when I go into it's already running and connected (it's not re-starting...).

Sometime the Notification tests will not work also.

Here are the logs from the last time this happened (i cleared them before the issue): [https://drive.google.com/drive/folders/1KwDpXm-5ZR-MKkXkJSFCBC52VI_9OvM-?usp=sharing](https://drive.google.com/drive/folders/1KwDpXm-5ZR-MKkXkJSFCBC52VI_9OvM-?usp=sharing)

**Comment by fcaronte** [comment]
Try to search for "optimize" on setting, there is another menu were you need to disable from optimization and usually is miss to do because is a little hidden on Huawei\honor

**Comment by deadl0ck** [comment]
I've done that already @fcaronte .
Here are the settings:
https://i.ibb.co/nckkjRW/Screenshot-20190820-062307-com-huawei-systemmanager.jpg
https://i.ibb.co/PxVvtz8/Screenshot-20190820-092921-com-android-settings.jpg

I've also done it for the AmazFit app

**Comment by fcaronte** [comment]
Ok and you add a "lock" on the multitasking menu too? And maybe try to update to last 1903

**Comment by deadl0ck** [comment]
"you add a "lock" on the multitasking menu too" - is that a phone setting or something on AmazMod ?

I've not been able to update to 1903 - I need to do it with a windows machien which I have not had a chance to do yet - see #665

**Comment by deadl0ck** [comment]
I've been looking for the lock - I don't think it's available on EMUI 9 - it was the little lock icon on the  app's top right on the older version (that you saw when you look at the recent apps) - right ?

**Comment by fcaronte** [comment]
Ok let's see if something change 👍🏻

**Comment by deadl0ck** [comment]
Hmmm - not much better
What's interesting is that I went to AmazMod (even though it's "locked") and it's Watch Information now says "Disconnected" - even though the AmazFit app is connected....

I've done a force stop and it still can't connect.

If I then "Force Stop" on the AmazFit app I get the "Phone disconnected" message on the phone and then the phone connected,
If I then "Force Stop" AmazMod it then connects.
So it's as if AmazFit app is connected to the phone OK, but AmazMod has lost connection with the AmazFit App

Does that make sense ?

**Comment by fcaronte** [comment]
Can you try to disable all the graph and greatfit\calendar send data button? Try keep only notification to be sent and see if happen again maybe reboot both phone and watch too

**Comment by deadl0ck** [comment]
OK - updated to 1903 last night and I've just disabled the graphs and the greatfit button.
I'll keep you posted

**Comment by deadl0ck** [comment]
No difference - I'm going back to the AmazFit app and see if it's working for notifications - I suspect it ma be an issue with the AmazFit app that is being reflected on the AmazMod app

**Comment by kerplunk86** [comment]
I'm running 1903 because the stable release just started messing up my notifications. 1903 did not fix my issues and have already excluded amazmod from battery saver and what not.

**Comment by deadl0ck** [comment]
So I think I'm making progress.
I was running AdGuard (https://adguard.com/en/adguard-android/overview.html) on my phone and I uninstalled as I thought it might be doing something as it monitors all traffic on the phone and blocks certain stuff.
My AmazFit app is working much better now so I'm going to move back to AmazMod later today and see if it's working as well

**Comment by fcaronte** [comment]
Good, let's say us if fix for amazmod too 👍🏻

**Comment by deadl0ck** [comment]
It's looking good so far for me - here's the steps on Huawei / Honor EMUI 9 to make it work:

(1) Settings -> Apps -> Apps-> AmazMod ->Power Usage Details -> App Launch : Turn Off "Manage Automatically" and make sure that all "Manage Manually" options are on - Screenshot: https://i.ibb.co/0j1dBjC/Screenshot-20190822-115454-com-huawei-systemmanager.jpg

(2) Settings -> Apps -> Select the 3 dots on the top left -> Special Access -> Battery Optimization -> Select All Apps from the down at the top -> Select AmazeMod -> Select "Don't Allow" - Screenshot: https://i.ibb.co/GpVTFFv/Screenshot-20190822-120219-com-android-settings.jpg

(3) "Lock" the app: Select the square icon on the bottom of the screen to show all running apps - find AmazeMod -> Drag it down and release it and a Lock icon should appear to the right of it's name - screenshot: https://i.ibb.co/Fs4h6Mx/Screenshot-2019-08-22-12-07-16-725.png

(4) If you're running AdGuard, uninstall it !

You need to also do the same for the AmazFit app

**Comment by fcaronte** [comment]
@kerplunk86 try to check this step ☝🏻

**Comment by kerplunk86** [comment]
Not really sure how to do all that as I own the LG V30 but I did make sure it wasn't on the battery saver option. It's very weird everything was working perfectly I haven't installed or changed anything settings wise and it just stopped working. Today it worked a couple times but now it's not anymore.

**Comment by fcaronte** [comment]
> Not really sure how to do all that as I own the LG V30 but I did make sure it wasn't on the battery saver option. It's very weird everything was working perfectly I haven't installed or changed anything settings wise and it just stopped working. Today it worked a couple times but now it's not anymore.

try to send this log here and  all screen were you put amazmod to disable battery saver and do same thing for amazfit app too

**Comment by fcaronte** [comment]
> Ok yep I did that last night for both apps I'm not sure what log you need but here's 2 of them I restarted my phone and lost all errors but still get the the uuid error
> 
> https://drive.google.com/file/d/10c_4aUPAH9wBjvxo2xSVFECihhKJ2ODK/view?usp=drivesdk
> 
> https://drive.google.com/file/d/10cSklN0KhTdlFUqfM1L4HXDa5ed6x20Z/view?usp=drivesdk
> 
> Screenshot of battery exclusions
> https://pasteboard.co/ItUurBq.png

i see only screenshot and the problem is there. you have install service on phone too and you need to uninstall and keep only amazmod+amazfit app (service need only on watch)

**Comment by kerplunk86** [comment]
Oh yep I think I did that a month ago by accident but it never messed up. I have deleted it and it still hasn't fixed the issue sadly.

Here's a screenshot of my amazmod.log

https://pasteboard.co/ItVOUrU.png

I'm assuming this is why I can't get notifications but idk what it means.

**Comment by fcaronte** [comment]
I think after you delete the bad service app, you need to reboot watch and phone and then to be sure to update setting and connection, disable notification and enable again.
Ps the log need more data to be useful try put log level to debug on amazmod setting

**Comment by kerplunk86** [comment]
Okay here is the log on debug mode

https://drive.google.com/file/d/11NXxGQsngvQVKMpUrNCQZHCZq31hJKzR/view?usp=drivesdk

**Comment by deadl0ck** [comment]
I'm still seeing issues - AmazeMod seems to lose contact with AmazFit after an hour or 2. It's not as bad as it was, but still a PITA.

I'll try a few more things and report back if I find anything of interest

**Comment by kerplunk86** [comment]
If anything you could try to reset the watch to factory settings and then reinstall amazmod I did that and everything is back to normal.

**Comment by deadl0ck** [comment]
Too drastic for me @kerplunk86 - I've a work profile on my phone with a lot of certs etc - it's not simple to set up

**Comment by fcaronte** [comment]
close for now if need we can reopen
