### ISSUE TITLE
Screen timeout - incorrect time period

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#668]
when the screen timeout set to 20 seconds, the actual time is half of it.

**Comment by fcaronte** [comment]
Is never set to 20 sec, but stock 14sec or 3min during install process, after a lot of test seem that huami allow only 14sec as default or more than 2min, other value seem to not be applied

**Comment by fcaronte** [comment]
Now I understand what you mean, and yes for me 20 work correctly, and I see that counting in my mind seem lower time but after use a chronometer I see 19.6 but probably I touch start I little after show the notification

**Comment by 1immortal** [comment]
mmm..... i'll re-test it.
Thanks :)
