### ISSUE TITLE
Custom notifications on watch aren't dismissed

### ISSUE THREAD

**Issue by alexagr** [AmazMod/AmazMod#680]
Custom notifications on watch aren't automatically dismissed when read on phone. I reported this issue before and unfortunately it's still the case with the latest 1902 version. My phone is Xiaomi Mi8 SE with MIUI 10.2.3.0.

**Comment by fcaronte** [comment]
you need to disable both two "ungroup notifcations" and "keep notification" but is not supported from self ungrouped notification (some whatsapp notification for example)

**Comment by alexagr** [comment]
Right - my mistake - turning off "ungroup notifications" fixed the problem
