### ISSUE TITLE
Notification sounds and widget sorting

### ISSUE THREAD

**Issue by 4eGuevara** [AmazMod/AmazMod#685]
1. Something wrong with notification sounds in last 2 or 3 builds - its appear or dissapear randomly. Sometimes after reboot watch its appear, sometimes dissapear. Notification sound mute in watch setting doesn't help, only global mute.
2. After each connecting phone to watch widget sorting cleared

**Comment by fcaronte** [comment]
1- service 1904 should work correctly
2- try go to reorder widget, go to the end and clear saved order, then enable your widget and go at top of page and long press on "widgets" to save setting correctly

**Comment by 4eGuevara** [comment]
1-I'm on service 1904 already))))
2-Thx, I'll try

**Comment by fcaronte** [comment]
Amazmod sound is play on create of custom UI notification, try to understand when you see the problem, stock notification sound is not manage from amazmod

**Comment by 4eGuevara** [comment]
Ok, and? I have a problem with a sound notification. Sometimes I hear the sound, sometimes not. And I can't find any regularities from which it depend. Once I reboot the watch and I have a sound, next time after reboot not

**Comment by fcaronte** [comment]
Take a logcat from amazmod app when is not working, so we can give a check

**Comment by 4eGuevara** [comment]
Or maybe you don't understand - stock sound notifications works correctly - they play or not play depend from the watch settings. Notification, managed by amazmod, played as... I don't know as what and when))))))

**Comment by fcaronte** [comment]
But when is not play notification work correctly vibrate etc ? Only miss sound?

**Comment by 4eGuevara** [comment]
Yep. Everything else work correctly. In the morning I heard quiet sound, not loud not only vibrate, but I didn't do anything before... But now I noticed that in the clock settings first I should add the volume to full, and then completely screw it and only after that I don't hear the sound at all.

**Comment by 4eGuevara** [comment]
The point is that I don't want to hear that sound at all)))) But it appear and appear again for unexplained reasons

**Comment by 4eGuevara** [comment]
"2- try go to reorder widget, go to the end and clear saved order, then enable your widget and go at top of page and long press on "widgets" to save setting correctly" - thx a lot! It helped!

**Comment by 4eGuevara** [comment]
And one more question - till the 1902 or 1901 build I never heard the sounds from amazmod notification - it was bug or it was feature?))) And now, from 1903, sound is the bug or it's feature? I can't understand) In what case you want logcat?)

**Comment by fcaronte** [comment]
If you want to disable sound, enable the silent button form watch status bar, or go to setting and set to 0 volume

**Comment by 4eGuevara** [comment]
1. "enable the silent button form watch status bar" - it's helped in any case.
2. "go to setting and set to 0 volume" - I told you before, that it haven't helped always. For sure I should "add the volume to full, and then completely screw it". But even after that sound appears randomly

**Comment by fcaronte** [comment]
2- you talk about "tone volume" ? last 1904 custom ui sound is on tone volume as standard ui, there are two different volume on setting, and now i haven't a verge to try

**Comment by 4eGuevara** [comment]
Yes, tone volume. But actually there are 3 types on verge - notification, some other notification (I even don't know what kind of sounds this item adjust) and alarm clock. Two first items adjustment works like I told you before - sometimes it's works, sometimes not but 100% works if add the volume to full, and then completely screw it in any of them)

**Comment by fcaronte** [comment]
Are different sound and amazmod sound should stay under "tone volume" as
the stock notification. If remember good the other two are for call
notification and media players audio

Il mar 27 ago 2019, 11:14 CheGuevara <notifications@github.com> ha scritto:

**Comment by fcaronte** [comment]
I received other feedback about this problem, and seem that increase and set again to 0 work, but need to understand why and when is happen the problem. Can you try if the problem come after a full watch reboot?

**Comment by fcaronte** [comment]
Hi, any updates about sound problem?

**Comment by fcaronte** [comment]
Last Dev version have an option to manual switch off the sound, so is fixed and we can close here.
