### ISSUE TITLE
GreatFit/Calendar: make ability to select a specific calendar to be sent to watch

### ISSUE THREAD

**Issue by rain-bipper** [AmazMod/AmazMod#696]
For now all calendars from all accounts that exist on your phone are sent to GreatFit/calendar widget. A user may have multiple accounts, some of which he would not like to see in notifications.
So one need add an option to select a specific calendar to send to watch.

**Comment by rain-bipper** [comment]
I have patch with the implementation, but can't push it to git.
If some one kindly give me access, I'll make the pull request.

**Comment by rain-bipper** [comment]
@diotto @lfom What do you think about this feature?

**Comment by lfom** [comment]
Hello. If you have forked AmazMod, then you can send the pull request from you dev branch to upstream dev.

**Comment by GreatApo** [comment]
Seems nice! Let us know if you can push it.

**Comment by rain-bipper** [comment]
Ok, I'll try to fork and make PR tomorrow

**Comment by GreatApo** [comment]
This helpful code was implemented :P
