### ISSUE TITLE
Disable google maps notifications when android auto is running

### ISSUE THREAD

**Issue by williknow** [AmazMod/AmazMod#697]
May I suggest that maps notifications can be disabled when android auto is running on the phone?
I have maps on the screen in my car, the phone screen is off and i get useless maps notifications on my watch. Maybe you can add an option or disable the maps notifications on default in this case.
Thank you very much

**Comment by lfom** [comment]
Why not simply remove Maps from selected apps in AmazMod?

**Comment by williknow** [comment]
I would like to receive this notifications/directions when I am navigating without Android Auto. For example when walking or biking.

**Comment by lfom** [comment]
Then please share a screenshot with the AmazMod's Notifications log with the Auto/Maps notifications.

**Comment by williknow** [comment]
![screenshot](https://user-images.githubusercontent.com/52751624/64541868-e4a6db80-d322-11e9-8516-a5c3c6354b38.jpg)
The Android Auto notification icon in the status bar of the phone is persistent when android auto is running. Does this help?

**Comment by lfom** [comment]
Hmmm, it will be complicated, because the notifications actually come from Maps... Maybe the only way to prevent this is check if Auto has a notification and then block Maps while it's on.

**Comment by williknow** [comment]
That is exactly the solution I was thinking about.

**Comment by fcaronte** [comment]
I think the better idea is to add a specific setting to fast enable disable maps, without need everything to load al packages list, show system app and then select maps, this is too long steps

**Comment by fcaronte** [comment]
on last dev version you have a setting to enable/disable google maps notification without need to load all package every time you need maps notification

**Comment by GreatApo** [comment]
> Hmmm, it will be complicated, because the notifications actually come from Maps... Maybe the only way to prevent this is check if Auto has a notification and then block Maps while it's on.

That seems a good idea

**Comment by GreatApo** [comment]
Further research on this: here is a code that can detect if phone is in driving mode https://stackoverflow.com/questions/36293866/how-to-detect-whether-the-phone-connected-to-android-auto

I would also propose to switch off notifications or turn off vibration when on driving mode.

**Comment by GreatApo** [comment]
- New option to disable notifications when driving (enabled by default) (commit e4ebb4518b6afc23b8d48d9fafac6ae22ca8f71b)
- Block maps notifications when in driving mode (commit cd76048934c2fdd01d38599e6d416831f9c50e28)

Install the lattest bleeding edge version and let us know if everything is fine ;)
