### ISSUE TITLE
Readability of google maps notifications

### ISSUE THREAD

**Issue by williknow** [AmazMod/AmazMod#698]
One more suggestion regarding google maps notifications during navigation.
Is it possible to rearrange the information on the watch and increase the size of some information to improve the readabilty? 
Maybe as shown below:
![Anmerkung 2019-09-06 112912](https://user-images.githubusercontent.com/52751624/64422179-b8315c00-d0a3-11e9-8f65-ec94925dc8de.png)

Or with more content:
![Anmerkung 2019-09-06 123829](https://user-images.githubusercontent.com/52751624/64422192-c2535a80-d0a3-11e9-9054-7477a816f018.png)

**Comment by lfom** [comment]
Hardly it will happen since we don't have direct access to the navigation information (it is obtained from the notifications themselves, so it is very hard to filter the information).

**Comment by williknow** [comment]
So I will have to stick with additional companion apps which do not have such active and good developers like amazmod. Bad Luck!
