### ISSUE TITLE
Delay between phone notification and watch notification

### ISSUE THREAD

**Issue by ghiki** [AmazMod/AmazMod#702]
I have too much delay between notification arrives and shows in phone, and when It shows in the watch (around 5 seconds delay). First the watch vibrates (without showing anything), and after 5 seconds or so, It shows screen notification (you can see in attached video)
Amazmod versión is last 1904, and the phone (MIUI) has battery optimization disabled and app locked in Amazmod and in Amazfit apps

[MOV00002.zip](https://github.com/AmazMod/AmazMod/files/3609501/MOV00002.zip)

**Comment by rain-bipper** [comment]
Have the same issue. Native watch notification is show immediately but AmazMod's notification - with large delay.

**Comment by ghiki** [comment]
I tried with another watchface+amazmod notifs., and also with "Greatfit" watchface and stock notifications, so it seems to be something related with Amazmod<>Greatfit (anyway, stock notifications are slightly faster, but practically isn't noticeable)
The point is that if I wanted to use Greatfit watchface (the best in my opinion), I have to give up notifications working correctly? There's no fix for this?

[amazmodvsamazfit.zip](https://github.com/AmazMod/AmazMod/files/3610623/amazmodvsamazfit.zip)

**Comment by fcaronte** [comment]
I have same configuration and haven't that delay (REDMI note 7 + pace) For me is around 1sec, 
Try to clean watch maybe you have to much APK installed and maybe try to completely reinstall amazmod

**Comment by ghiki** [comment]
Are you using Greatfit? I have 10 or 11 APK installed, IDK how many apps are "too much" (are 1,72Gb free space). I'll try resetting the watch and trying only with watchface+Amazmod installed

**Comment by fcaronte** [comment]
I have superfit APK watchface, as only APK watchface installed(I use only one APK watchface at time because they stay all active and running on background) then I have timeline widget, calculator, and a ftp server app

**Comment by AndriiTropin** [comment]
I have configuration REDMI 5 plus + stratos + Greatfit watchface  and the same problem, delay between notification arrives and shows in phone. First the watch vibrates (without showing anything), and after 5 seconds or so, It shows screen notification.

**Comment by ghiki** [comment]
I also tried with Superfit watchface and exactly the same strange thing. Sometimes vibrates and after 5-10 seconds it doesn't show the message/notif., other times, it shows at the moment

**Comment by fcaronte** [comment]
Try a clean install and if possible wipe watch or remove all APK possible, if you need a watchface apk, keep only one

**Comment by ghiki** [comment]
Not working. I resetted factory settings and I installed only "Superfit", "TouchOne" and Calendar app. The impression is that the watch "sleeps" before It shows notification.

**Comment by fcaronte** [comment]
Try to revoke admin right and then after the toast message, give again and
wait to see the toast say enabled

Il gio 19 set 2019, 18:20 Dani <notifications@github.com> ha scritto:

**Comment by AndriiTropin** [comment]
I've checked, this is weird - when i turn off admin rights. notifications popup instantly but there is 5 seconds delay if i turn admin rights back on.

**Comment by fcaronte** [comment]
This is normal, after that notification have same lag? Can you try with
unlocked phone screen, and then with unlocked watch screen? To try
understand if was watch or phone side problem. I don't know if a log can
help but maybe try to catch when is lagging

Il ven 20 set 2019, 09:25 Andrii Tropin <notifications@github.com> ha
scritto:

**Comment by rain-bipper** [comment]
> Try to revoke admin right and then after the toast message, give again and wait to see the toast say enabled

This not worked for me. Still have large  delay between vibration and displaying notification. For now I revoked admin rights - will see if this help.

>  To try understand if was watch or phone side problem.

this is definetly not the phone side problem, since watch already receives notification and vibrates, but displays this very notification with delay.

**Comment by fcaronte** [comment]
On logcat you see something special? Now think better, rarely is happen to me to receive notifications, got vibrate e seem nothing show but usually press the unlock button e notification Is showed correctly. I don't find how to reproduce that and try to analyse but if for you is always happen I think that try with unlocked screen should show notification correctly and  this will confirm is a wake-up problem

**Comment by rain-bipper** [comment]
> On logcat you see something special? Now think better, rarely is happen to me to receive notifications, got vibrate e seem nothing show but usually press the unlock button e notification Is showed correctly. I don't find how to reproduce that and try to analyse but if for you is always happen I think that try with unlocked screen should show notification correctly and this will confirm is a wake-up problem

I'll try to research when I'll have a time (not soon unfortunately).
How wake-up connects to admin rights. 

It seems, that revoking admin rights really helps.
How can wake-up be related on admin rights? For what purposes AmazMod needs admin rights?

**Comment by fcaronte** [comment]
At now admin right is need only to lock again screen after notification is
gone and is need to save battery and avoid keep unlock screen for 14sec on
every notification

Il ven 20 set 2019, 10:19 rain-bipper <notifications@github.com> ha scritto:

**Comment by fcaronte** [comment]
> I've checked, this is weird - when i turn off admin rights. notifications popup instantly but there is 5 seconds delay if i turn admin rights back on.

have you try if, after enable again, start to work correctly? or immediately lag when enable it?

**Comment by ghiki** [comment]
I tried while phone is awake, same result. 
[540_30_2.77_Sep222019.zip](https://github.com/AmazMod/AmazMod/files/3639239/540_30_2.77_Sep222019.zip)

**Comment by fcaronte** [comment]
No with phone, try with unlocked watch to see if lag is the same

Il dom 22 set 2019, 03:42 Dani <notifications@github.com> ha scritto:

**Comment by ghiki** [comment]
Yep, you're right, I tried while the watch is awake (unlocked and in any menu option) and yes, the notification is practically immediate, so the problem is the watch sleeps "very much"

**Comment by fcaronte** [comment]
I don't know what could be the problem, but if you use an APK watchface try
to remove and use a wfz watchface

Il dom 22 set 2019, 16:49 Dani <notifications@github.com> ha scritto:

**Comment by ghiki** [comment]
I tried with stock "Prototype" watchface, uninstalling the Superfit/Greatfit APKs. The notification vibrates and shows instantly, so, definitely, the problem is with Amazmod+Any APK watchface. With stock notifications, this doesn't occur with APK watchface. Is it possible to extract a logcat ir similar from the watch?

**Comment by fcaronte** [comment]
If you had both two installed should be the problem, on my pace I use
superfit watchface but is the only APK watchface installed and work without
problem, unfortunately this APK watchface keep running and have more then
one installed give problem to this low ram device

Il dom 22 set 2019, 21:32 Dani <notifications@github.com> ha scritto:

**Comment by ghiki** [comment]
Nope, in the last video, Superfit 1.7 is the only watchface installled

**Comment by fcaronte** [comment]
Have you a custom ROM or any other modifications? I'm on stock international version 2.8.4.0 on pace with superfit 1.7 and work correctly, maybe we use different setting on watchface

**Comment by ghiki** [comment]
Currently stock 2.8.4.0, installed with this:
https://forum.xda-developers.com/smartwatch/amazfit/fw-tool-stock-firmware-installers-2017-t3725494

**Comment by fcaronte** [comment]
Ok same as me, so maybe try to play with setting on watchface as the phone
battery indicator or notification counter, then maybe just to confirm try
to remove the admin right  as do the other guy and see if with APK
watchface give the same problem, if not enable again and check

Il dom 22 set 2019, 22:09 Dani <notifications@github.com> ha scritto:

**Comment by fcaronte** [comment]
Finally I understand where is the problem and why is not happen to me. I try to disable always on second timehands and start to have that problem, so yes without it APK watchface stuck and give this Delay problem

**Comment by fcaronte** [comment]
New update, seem that disabling notification counter on APK watchface fox the lag problem, maybe phone battery widget give the same problem too, try to disable and check

**Comment by ghiki** [comment]
After 2-3 days testing, I can confirm that with "notification counter" removed from the watchface, the notifications are immediate

**Comment by fcaronte** [comment]
Perfect mystery solved, for the fix we need a watchface side fix. We can close here

**Comment by rain-bipper** [comment]
Where is the current sources of the AmazMod-service-1906? 
I am suffering over this issue and want to research it, but I see only version _"release": 1904, "beta" : 1906_ in **master** and _"release": 1894, "beta" : 1904_ in **dev**.

The issue is not always reproduceable, so I want to get latest version of service to be sure to fix the right thing. For example I didn't managed to reproduce the issue on debug version from **dev** branch, with current release version of GreatFit.

**Comment by GreatApo** [comment]
With our current understanding of watchfaces, the issue can not be fixed from APK side. I think the problem is cause because watchface is refreshed (SLPT mode).

A possible fix is delaying updating the notification counter system value.

**Comment by rain-bipper** [comment]
> A possible fix is delaying updating the notification counter system value.

Yes, this may be an acceptable solution, since the notifications themselves are more important than their counter

Can you, please, show me the place in GreatFit which induces the watchface counter update and causes the delay?

And another question: did you managed to run Android Profiler for watch? Newest Android Studio says that this device is unsupported :(  although documentation states that Profiler should work on Android 5.0+

**Comment by GreatApo** [comment]
> With our current understanding of watchfaces, the issue can not be fixed from APK side. I think the problem is cause because watchface is refreshed (SLPT mode).
> 
> A possible fix is delaying updating the notification counter system value.

So it seems that this makes some difference, however, there seems to be a greater problem from GreatFit's side...

Commit 444558720b78545621ee3ccaa06bf9ddbbad5251



> Can you, please, show me the place in GreatFit which induces the watchface counter update and causes the delay?
In the libs, a system variable (where notification counter value is store) is been monitored and watchface SLPT reboots when changed. But there seems to be more than one reboot, or sth strange is happening... 

> And another question: did you managed to run Android Profiler for watch? Newest Android Studio says that this device is unsupported :( although documentation states that Profiler should work on Android 5.0+
No idea what that is :P

**Comment by GreatApo** [comment]
My guess about the problem was correct, however, the notification counter was been updated in 2 different parts of the code (one for stock and one for custom notifications). I fixed the bug at commit 71998d71cad6a23ab146e916d6f292a0da5dc9c1

**Comment by innomaxx** [comment]
@GreatApo any updates / ideas / assumptions related to this issue?

**Comment by GreatApo** [comment]
> @GreatApo any updates / ideas / assumptions related to this issue?

Use the last edge built, it works :)
Report back if you still have problems (install both service and phone app)

**Comment by zouille83** [comment]
Hello,
I have the same problem , delay of 3/4 secondes between Phone and watch. I read you but I don't find the option ( I have the frenche version) .
Is ther a new version of Amazmod , I have this of the 20 september
