### ISSUE TITLE
GreatFit/Calendar: calendar sending is broken if event contains quotes in title or description

### ISSUE THREAD

**Issue by rain-bipper** [AmazMod/AmazMod#703]
Calendar sending is broken if event contains quotes in title or description - this is because malformed calendar json.
A fix is on the way.

**Comment by fcaronte** [comment]
I merge last fix to try but is not work and got FC, I try to avoid FC and if send data with quotes no event are sent but is not force close.today I haven't time to test better. I will check tomorrow

**Comment by GreatApo** [comment]
Thanks for spotting this out. You code was merged and improved (avoid null error, change to replaceAll, added in location too)

**Comment by rain-bipper** [comment]
> Thanks for spotting this out. You code was merged and improved (avoid null error, change to replaceAll, added in location too)

I think it is good idea to use JSONObject here. But since it is already works.. let's leave it untouched :)

**Comment by GreatApo** [comment]
@rain-bipper I couldn't agree more :joy:
