### ISSUE TITLE
Add hourly chime, like Casio watch

### ISSUE THREAD

**Issue by wladOSnull** [AmazMod/AmazMod#705]
I beg you, no one apps have that function (i was think, it's not so hard). Maybe, just hourly, maybe with custom period. Anything.

Bad english, don't kill me(((

**Comment by fcaronte** [comment]
On last Dev version is just added hourly chime vibrate + Casio sound on verge only 👍🏻

**Comment by GarryBu** [comment]
The version with the function is installed, the menu item is turned on, but the gong does not sound and there is no vibration.
