### ISSUE TITLE
Amazmod dosent work on phone

### ISSUE THREAD

**Issue by Ralixi** [AmazMod/AmazMod#711]
after installation amazmod as the tutorial shows, I open the amazmod app and my phone doesn't connect, my amazfit app shows a connection for the phone.

"it was not possible to connect to the AmazMod Service on the watch..."

PS: I have the Amazmod on my phone, I can see it when I scroll on my watch

**Comment by GreatApo** [comment]
> PS: I have the Amazmod on my phone, I can see it when I scroll on my watch

You mean your watch right? Have you restart both phone and watch?

**Comment by Ralixi** [comment]
yes of course.
I use step by step ... I even check for the DND mode and make sure its off someone online said it might cause a problem

**Comment by GreatApo** [comment]
It's a common mistake and I had to ask.

Sounds like you are setup correctly but the watch app doesn't reply back. If I were you I would restart the watch once again (but the receiver should have been working since you did).

In case you have many watches, make sure the correct one is connected on the Amazfit app

**Comment by Ralixi** [comment]
only one on my app , try several times repeat the prosses and install apk with installer and install manually.
The installation process goes well and finish successfully, but still the AmazMod cant recognize the watch.
I just Upload here what i see on my AmazMod app
https://ibb.co/JtRfNSm

**Comment by GreatApo** [comment]
I can't think of what may be the problem... You do have the latest service app right?

**Comment by Ralixi** [comment]
yep, just Downloaded it today from the google play store, 
I try to make a hard reboot for my watch now to check maybe it will help

**Comment by GreatApo** [comment]
> yep, just Downloaded it today from the google play store,
> I try to make a hard reboot for my watch now to check maybe it will help

The service is the watch apk (installed on the watch), you can get it from here: https://github.com/AmazMod/AmazMod/releases/download/v1.1.8-217-1904-release/AmazMod-service-1904.apk

**Comment by Ralixi** [comment]
yes already try it

**Comment by GreatApo** [comment]
I am out of ideas. When you have time, leave us your phone android version and a watch adb log.

**Comment by Ralixi** [comment]
Using my huawei p30 pro with EMUI 9.1.0.193

**Comment by Ralixi** [comment]
Well, I literally try all version of APK in git, try to delete restart like 500 times. 
And I solved at the end after 3 hours, Wanna know how? 
I just Downloaded the AmazMod apk from git and use it instead from google play store...

**Comment by fcaronte** [comment]
I ask because is happen one time to me, can you check maybe if you install the service app on phone too? You need to go on app manger because is not see on menu app list. Another try is force kill amazfit app and then amazmod app too, and on your watch you see correctly the amazmod widget right?

**Comment by Ralixi** [comment]
what do you mean by service app? when you get the AmazMod it should be stocked, As much as I understand my phone isn't the issue, The plugin is for the watch connects to the phone for a specific request code or looking for specific signature.
I search a lot, I try any function of the notification and any function of the battery at my phone I just give a shot for all, nothing helped.
I would just recommend people at the README file to download the Amazmod from the link provided at this repository :)  (at least that my conclusion after almost 4 hours and a deep search)

**Comment by fcaronte** [comment]
I'm not understand if you fix the problems, but to recap, on phone side you only install amazmod from playstore and no other thing or manual APK install right? Then on watch you need to see a new pace with amazmod widget where say the version number. You see that?

**Comment by Ralixi** [comment]
I did fix it with your Amazmod App apk, I download it to my phone and install it, And suddenly amazmod recognized the watch. 
At my phone, I Install the amazmod from google play store which didn't work all this time and no other thing on my phone, on my watch I try Installer, All apk versions for watch with 3 different software and try to install it with CLI, was not change.
Currently, I use 1904 on my watch.
All the time I saw the amazmod widget at my watch, but still didn't connect to my phone.

**Comment by GreatApo** [comment]
Anyway, the problem was solved. I haven't see any other users reporting compatibility issues between phone and watch app in the last releases thus lets assume this was limited to your case, for now.

It is noted that playstore has the same apps as GitHub.
