### ISSUE TITLE
Unlock device via bluetooth 

### ISSUE THREAD

**Issue by azpik** [AmazMod/AmazMod#713]
After installing amazmod unlock device via bluetooth function stoped working. When I open security settings it says then security key is invalid. I tried to reconfigure this function, but it didn't help. Xiaomi Mi5s Plus MIUI Global 10.2.4.0 (8.0.0), Amazmod 1.1.8 build217, Amazfit Verge A1811 firmware: 3.2.5.0 service 1904. 
![Screenshot_2019-09-30-19-41-57-458_com android settings](https://user-images.githubusercontent.com/8456573/65898693-ce88ba00-e3ba-11e9-9c98-fcf433a0de3f.png)

**Comment by fcaronte** [comment]
I try to enable on my redmi note 7 + verge + amazmod and work at first try. Try to check better your setting maybe on security phone setting under the advance setting menu

**Comment by azpik** [comment]
Yes. Only after phone reboot it works fine. Sory.
