### ISSUE TITLE
Backup and restore Activity and export Speed/FC/Altitude

### ISSUE THREAD

**Issue by looun** [AmazMod/AmazMod#72]
if possible, it would be great to be able to backup DB Activity as local file and restore it.
Also  it would be great  export Activity ( Speed/FC/Altitude) to CSV or TCX file data.
Thanks.

**Comment by lfom** [comment]
I don't think it's a good idea to backup/restore Sports/Activities DB as restoring the data may cause a lot of problems is it's a different version when it's restored. You can also already do this on you computer, makes little sense to keep the backup on watch as it will be erased if you unpair, for instance. The export feature was already requested, so maybe this should be closed as duplicated?

**Comment by diotto** [comment]
Heard of AmazeBackup ? Maybe it's what you need. Doing that with the watch is not exactly the goald of Amazmod.
https://forum.xda-developers.com/smartwatch/amazfit/utility-amazebackup-backup-tool-pace-t3801165
