### ISSUE TITLE
Add Sleep as an Android Support(HR & Accelerometer)

### ISSUE THREAD

**Issue by DarkFlamex1** [AmazMod/AmazMod#75]
While looking through the xda form user carloscolhao brought to my attention [Sleep as an Android.](https://sleep.urbandroid.org/) I have begun some research on this and have discovered the relative ease of the addition of this apps support.

Some references:
- [Sleep as an Android API](https://sleep.urbandroid.org/documentation/developer-api/)
- [Wearable Integration API](https://sleep.urbandroid.org/documentation/developer-api/wearable-integration-api/)
- [HumaiTech API](https://github.com/huamitech/rest-api/wiki) I can't read chinese so I do not know if this would help.

Also carloscolhao stated the below in the xda thread.
> Mi band 1, 2 and 3, as well as the Bip, Arc, Cor, all of them have integration with the sleep as an android app though 2 third party apps.

This probably could help us if we are able to find opensource versions as I believe the bip still runs android?

Anyways the current plan is:
- [x] Get accelerometer data from the watch.
- [x] Get Heart Rate data from the watch.
- [x] Either send the data to sync directly to Sleep as an Android from the watch OR sync the data with the AmazMod app on the phone, then sync with Sleep as an Android
- [x] Success? 

If anyone has any other idea/method on how to execute this please provide it in the comments! I will get started on this with a fork and then pull request in.

------
VP

**Comment by caoHenriques** [comment]
any progress?

this will be a wonderful nice feature, thanks
good work ;)

**Comment by DarkFlamex1** [comment]
Hey!
I started working on getting accelerometer data/HR data but school ended up starting :( I plan to get back to working on this in a week or two!

**Comment by caoHenriques** [comment]
Hi
Thank you very much for the reply. Looking forward for the progress. 

Good work ;)

**Comment by lfom** [comment]
Actually it was working through data sync via GoogleFit, but the new Google Fit seems to broke this. As watch/Amazfit already records sleep data, instead of recording data during sleep maybe we could just send sleep data to SAAA?

**Comment by DarkFlamex1** [comment]
It was working on Google fit? That's good news probably simplifies the whole thing. Yeah I think we could just send it instead of recording anything then!

**Comment by rpodgorny** [comment]
well, i don't know what you mean by "send" but please don't forget that sleep as android is using current hr and motion data to analyze your sleep AND to wake you up in the light sleep phase.

**Comment by lfom** [comment]
Actually sleep data sync still works, *but* MiFit must also send some activity data to GoogleFit, it you have recorded only steps that it won't work...

**Comment by 1immortal** [comment]
any idea on where and how to push it through?

**Comment by lfom** [comment]
@1immortal Yes: we must add code to service app so watch syncs data continuously to SAA. Watch must send HR and accelerometer data to SAA, where it is processed... Not a simple task as it seems.

**Comment by caoHenriques** [comment]
I hope someone can get this working :) it will help a lot of people.
Perhaps you can contact the sleep as an android team, they may want to help since they will get more clients with this project.

**Comment by rodricels** [comment]
#480 It's maybe related, coz measure constantly and sending it to sleep as an android it could be a solution.

**Comment by banhegyinorbert** [comment]
Well, I'm not a developer, but broadcasting an intent, that could be listened by Tasker would solve the data processing question, wouldn't it?

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Sleep as an Android Support(HR & Accelerometer)](https://trello.com/c/UgHMiGer/7-add-sleep-as-an-android-supporthr-accelerometer)

**Comment by rpodgorny** [comment]
...any plans to make the trello board public? ;-)

**Comment by PRIHLOP** [comment]
Hello.
I have a watch Amazfit Startos, and also I have a root access on it.
I tried to install this app(https://sleep.urbandroid.org/wp-content/uploads/release/Sleep-wear-release-2.2.apk) on watch via adb, and it installed and launched, but no connection to app on phone. Maybe you can implement proxy in your App like described on Urbandroid site [Wearable Integration API](https://sleep.urbandroid.org/documentation/developer-api/wearable-integration-api/), and maybe this integration can work.

If you needed some testing I can help with it.

**Comment by mxr2-a11y** [comment]
Hi. How's the progress on this development? Sorry, do not have trello account.

**Comment by micrusa** [comment]
Added in https://github.com/AmazMod/AmazMod/commit/ab679e4991324364241d7c2f3795a5b3c1d9ca99 and https://github.com/AmazMod/AmazMod/commit/5c168b5a663f0abe11882b20b1e2545d9c4c91a5

**Comment by PRIHLOP** [comment]
> Added in [ab679e4](https://github.com/AmazMod/AmazMod/commit/ab679e4991324364241d7c2f3795a5b3c1d9ca99) and [5c168b5](https://github.com/AmazMod/AmazMod/commit/5c168b5a663f0abe11882b20b1e2545d9c4c91a5)

Can I help with testing it? I have installed latest dev release and can help with testing or other activities.

**Comment by micrusa** [comment]
> > Added in [ab679e4](https://github.com/AmazMod/AmazMod/commit/ab679e4991324364241d7c2f3795a5b3c1d9ca99) and [5c168b5](https://github.com/AmazMod/AmazMod/commit/5c168b5a663f0abe11882b20b1e2545d9c4c91a5)
> 
> Can I help with testing it? I have installed latest dev release and can help with testing or other activities.

It won't work until our package gets whitelisted by saa team and currently code is unfinished and buggy, so I suggest not using it until we release next stable version. About testing no need, we are already testing everything

**Comment by PRIHLOP** [comment]
> > > Added in [ab679e4](https://github.com/AmazMod/AmazMod/commit/ab679e4991324364241d7c2f3795a5b3c1d9ca99) and [5c168b5](https://github.com/AmazMod/AmazMod/commit/5c168b5a663f0abe11882b20b1e2545d9c4c91a5)
> > 
> > 
> > Can I help with testing it? I have installed latest dev release and can help with testing or other activities.
> 
> It won't work until our package gets whitelisted by saa team and currently code is unfinished and buggy, so I suggest not using it until we release next stable version. About testing no need, we are already testing everything

Ok. Thank you very much for your diligence.

**Comment by 1immortal** [comment]
the latest beta of yesterday of SAA whitelisted us, current edgy has some voodoo stuff for SAA as well.
Please note that edgy builds are unpredictable, so if your watches will try to run away or sell your kidneys... it's not our fault.
If you'll do decide to play with that, please report on any bugs with logs.

**Comment by 1immortal** [comment]
As of the last release on play store - 1.2.3/1914 - there's an experimental SAA support, with support from SAA side.
The battery drain is horrible, this can be enabled from the Settings menu on AmazMod, and AmazMod support should be selected on the SAA application.
Please test this with caution, you might wake up with a batteryless watch.

**Comment by kpoman** [comment]
Horrible battery drain indeed ! Any ideas if this can be lowered a bit ? And about HR ?
