### ISSUE TITLE
Can't install Amazmod Service on Verge 3.2.7.0

### ISSUE THREAD

**Issue by zizzifirenze** [AmazMod/AmazMod#753]
Hello,
I tried to install the service on my Verge watch with 3.2.7.0 ROM both from phone and from a Windows PC.
On my motorola E4 plus the amazmod service app does not start.
On the PC the installation work till the end [the watch restart automatically] but I can't find the service widget on the watch or on the amazmod app installed on the phone [restarted manually].
Any idea on what I do wrong?
Thanks for your hard work on this project :)

**Comment by fcaronte** [comment]
I'm using Amazmod on verge with this rom. Try to go on last left page where are Alle the disabled widget, go at the and and you can find Amazmod open it go to widget reorder and enable Amazmod widget and save. If Amazmod is completely miss try to reinstall

**Comment by zizzifirenze** [comment]
> I'm using Amazmod on verge with this rom. Try to go on last left page where are Alle the disabled widget, go at the and and you can find Amazmod open it go to widget reorder and enable Amazmod widget and save. If Amazmod is completely miss try to reinstall

Thanks for your reply fcaronte. 
Three installation and still no widget on the Verge :(

**Comment by GreatApo** [comment]
Install the bleeding edge version, install the service, open if from apps menu, go to widgets and enable the service widget.

**Comment by zizzifirenze** [comment]
> Install the bleeding edge version, install the service, open if from apps menu, go to widgets and enable the service widget.

Thanks GreatApo, Nothing to do with bleeding edge versione, I tried to install again via PC and amazmod is on the Verge now but constantly disappear from the first page even If I untick other widgets in the amazfit app.
Restart ed both watch and phone and I can only see amazmod icon in widget list :(
#headache

**Comment by GreatApo** [comment]
I mentioned the bleeding edge version because it has a new way of detecting the widgets. Install both service and phone app. Then go to widgets from watch and enable the amazmod service widget 

I hope this helps :)
Verge is even more aggressive when it comes to widgets compared to pace and stratos.

**Comment by fcaronte** [comment]
I use verge daily without any problem, on amazfit app all widget are
disabled and using blending edge version, go to setting, enable first
option "keep widget" then go to widget menu from Amazmod app and enable all
wanted widget and save list (from phone you have problem to rearrange the
top of the list so maybe for now use the rearrange option from watch side,
or from phone keep your enable widget on center of the list )

Il sab 30 nov 2019, 11:32 Grammatopoulos Apostolos <notifications@github.com>
ha scritto:

**Comment by zizzifirenze** [comment]
> I mentioned the bleeding edge version because it has a new way of detecting the widgets. Install both service and phone app. Then go to widgets from watch's amazmod service icon and enable the amazmod service widget
> 
> I hope this helps :)
> Verge is even more aggressive when it comes to widgets compared to pace and stratos.

Seems it works, installed the bleeding service and finally I can see the widget in the watch list. 
Do I HAVE to uninstall the previous version [not the bleeding one] via PC? Or the bleeding version is overwrited?
#noobmodeon
Thanks all for your help!

**Comment by fcaronte** [comment]
Unfortunately all bleeding edge version need a clean install and can't
update due to different signature (maybe if you know how, you can sign APK
yourself everytime and update APK)

Il sab 30 nov 2019, 12:47 zizzifirenze <notifications@github.com> ha
scritto:

**Comment by zizzifirenze** [comment]
> Unfortunately all bleeding edge version need a clean install and can't update due to different signature (maybe if you know how, you can sign APK yourself everytime and update APK)

Bleeding installed with out uninstalling the standard version and all seems working fine, do you think I'll have to uninstall anyway via PC? I'm scared to lose the bleeding working version.

**Comment by fcaronte** [comment]
Umh if you was on standard version probably seem installed but you have
again the old one

Il sab 30 nov 2019, 15:25 zizzifirenze <notifications@github.com> ha
scritto:
