### ISSUE TITLE
Custom weather provider with hourly forecast

### ISSUE THREAD

**Issue by rain-bipper** [AmazMod/AmazMod#754]
How about add support of subject in AmazMod?

I have implemented DarkSky weather and Yandex geocoder providers; both server (phone) and client (watch) sides. Custom weather povider is integrated into watch system and shows weather in system's widget as well as in GreatFit watchface and in its own widget. It supports current weather, daily and hourly forecasts.

![screen](https://user-images.githubusercontent.com/48675838/69868354-89014400-12ba-11ea-9523-318801b2e2b0.png)
![photo_2019-11-29_15-13-55](https://user-images.githubusercontent.com/48675838/69868493-e8f7ea80-12ba-11ea-9d95-23dd73eb3545.jpg)

**Comment by fcaronte** [comment]
If Amazmod can manage stock weather provider will be really useful, if you know how and want to add free to do 👍

**Comment by GreatApo** [comment]
Nice... +1

**Comment by rain-bipper** [comment]
Ok, I'll prepare my code to be integrated to AmazMod. But I don't have much time right now, so don't expect soon :(

**Comment by rain-bipper** [comment]
OK. Here is a project of custom weather: https://github.com/rain-bipper/AmazInformatory

The project `host` is intended to run on the phone, the project `watch` is intended to run on the watch.
To integrate into AmazFit, it is enough to add the `lib-weather` library there, instantiate `WeatherController` and periodically call the `WeatherController.process()` method. An example of the workflow can be found in `com.formalizationunit.amaz.informatory.host.Facade`. 

The catch is that in order to use Internet services, the user needs to get API keys for them.
So to integrate into AmazFit on the phone side one will need:
1. add a page to the settings to enable custom weather feature.
2. on this page, add the input fields of API keys and information where they can be obtained.
3. add lib-weather library and write instantiation logic, depending on settings

To integrate the project on the side of watch, we need to decide how to organize the back channel - from the weather widget to the phone: the widget can request the phone to update the data. Now the widget uses `com.huami.watch.transport.Transporter` by its own, but that should be moved to AmazFit service. As an option, the widget will request the service about the update data, by intent.

What do you think about all of this?

**Comment by fcaronte** [comment]
interesting! I don't think to have skill to do that but if weather then will see on stock widget and stock watchface too, will be a killer feature!

**Comment by GreatApo** [comment]
Thank you very much for the push!

After a bunch of commits during the last months, Amazmod has it's own custom weather provider code (Openweather's API is used).
At the current state, the feature fully works. What needs to be done next to completely finish it, is the addition of GPS location tracking instead of a fixed location. 
I am closing this issue for now.
