### ISSUE TITLE
Android app intercepts "intent action view" when installing other APKs

### ISSUE THREAD

**Issue by ghiki** [AmazMod/AmazMod#762]
If I try to install any APK while Amazmod is installed, It shows "notfoundexception". Only can install APKs from file browser (Android 8.1)

Heres a video
https://youtu.be/VUWnpZe-JnE

**Comment by fcaronte** [comment]
i install this app on my miui 11 phone and can install normally. maybe is a bug of that app, try to install after amazmod. amazmod simple add another way to install apk and first time phone should ask you if you want to install using normal way or send to watch and install using amazmod

**Comment by ghiki** [comment]
Nope, i tried installing downloaded apk from browser (It calls "Downloads" Android app when clicking on it), so, I think the issue is the way Amazmod (Android app) inserts it's context menu on Android phone, but maybe is related to MIUI Android ROM menú (miui.eu ROM), so I will close the issue, since I tried with another app which adds itself to context APK extensión and same happens

**Comment by fcaronte** [comment]
Ok but as I say, I have redmi note 7 with MIUI Xiaomi eu weekly and I try to install your app and work at first try. I'm sure is something strange about MIUI permission or maybe a bug with the new package installer on some phone

**Comment by ghiki** [comment]
Apparently is not so strange in other devices/ROMs. Thanks anyway.
https://stackoverflow.com/questions/3253079/cant-install-apk-from-browser-downloads
https://stackoverflow.com/questions/39147608/android-install-apk-with-intent-view-action-not-working-with-file-provider
