### ISSUE TITLE
Amazmod  1904 notification doesn't work on Stratos 2

### ISSUE THREAD

**Issue by irounet** [AmazMod/AmazMod#763]
I've wiped my watch with version 2.3.11.1, added Hebrew support and i can receive notification from the amazfit (Hebrew is upside down).
Now i've installed Amazmod on the phone and on the watch (service 1904).  
I'v disabled the notification on Amazfit app and enabled it in the Amazmod to be the first watch widget. i turned on the "push notification" and choose whatsapp but im not getting any notification for whatsapp and for other apps i've added.

Please assist

**Comment by 1immortal** [comment]
Please check the notifications from the stock Amazfit app first, and check if you're getting any notifications.

**Comment by irounet** [comment]
@1immortal thanks for your reply.
As i wrote, when i only use Amazfit for notification all works as expected, i receive the whatsapp notification (in hebrew it appears upside down), when i turn of the notification on the amazfit and turn it on in amazmod im not getting any notifications.
in the amazmod app in my phone i can see "connected" under the watch's information

**Comment by fcaronte** [comment]
Probably you miss to add notification access to Amazmod. Try to check this and other app permission too

**Comment by irounet** [comment]
@fcaronte Thanks.
Can you please elaborate what do you mean by "miss to add notification access to amazmod"?
Attached you can find screenshots from amazmod app
![Screenshot_2019-12-19-12-25-58-709_com edotassi amazmod](https://user-images.githubusercontent.com/58769959/71166204-e570d700-225a-11ea-8ffe-6d09be5017b1.jpg)
![Screenshot_2019-12-19-12-24-27-971_com edotassi amazmod](https://user-images.githubusercontent.com/58769959/71166228-eace2180-225a-11ea-81fd-55edbaa25cfa.jpg)

Please advise

**Comment by fcaronte** [comment]
Go to phone setting and find "notification access" and give access to Amazmod
![Screenshot_2019-12-19-11-54-52-230_com android settings](https://user-images.githubusercontent.com/26366403/71168230-827d4100-2256-11ea-8239-11c318264ad3.jpg)

**Comment by irounet** [comment]
@fcaronte Bingo
Thank you very much, not it works perfect.
I dont remember doing it before i wiped my watch.

Thanks again
