### ISSUE TITLE
Crowdin

### ISSUE THREAD

**Issue by Henry2o1o** [AmazMod/AmazMod#766]
Do you still have Crowdin Miui access?

**Comment by fcaronte** [comment]
what do you mean with miui Crowdin? here crowdin is work only for amazmod translation

**Comment by Henry2o1o** [comment]
OK, thanks.

**Comment by Henry2o1o** [comment]
Hello, I just revised all DE-strings.
Some were not translated correctly.

**Comment by fcaronte** [comment]
If you revise throu

**Comment by fcaronte** [comment]
If you revise through crowdin, we can, or we just update, with the fixed string and you can see it on next update or using blending edge version
