### ISSUE TITLE
Button to open notification on phone

### ISSUE THREAD

**Issue by leonardcapillon** [AmazMod/AmazMod#770]
Hi,
Really loving AmazMod. 
For each notification it would be great to be able to chose "Open on phone" to open the application on the phone as if you clicked on the notification from the phone notifications (e.g. a facebook notification or a new whatsapp message).

I had a google wear watch before my Pace and it had this feature that I greatly miss on Amazfit !

Best regards, happy 2020
Leonard

**Comment by fcaronte** [comment]
Where should be the utility? Is not the same of take your phone and double tap on notification from lock screen? You need to unlock phone I both two case

**Comment by leonardcapillon** [comment]
Hi,

Imagine you are walking and your phone is in your pocket. You received a lot of notifications since you've started walking but you receive them on your watch, and none of them was really urgent and could wait for you to stop at your destination. But then, you receive a text from the people you are meeting and you need to answer it. It would be handy and faster to be able to open this one message directly on your phone without having to scroll through all other notifications you received on your lock screen since the beginning.

Or imagine you are busy on your computer doing something and your phone is beside the computer unlocked on some app. You receive a notification that you start to read on your watch. It's truncated on your watch, but by the time you finish reading what's on your watch, the notification disappeared to the notification tray. You can open the app on your phone to finish reading, without having to search for this particular notification in the notification tray, where we imagine you have a lot.
 
I receive a lot of notifications every day and I have a very big phone (Mi Max 3) that I only take out of my pocket when I receive something urgent. I use my watch a lot to filter notifications I don't judge urgent and can wait, from the ones that need my answer right away. 
The two use case above are very frequently happening to me and I imagine I'm not the only one receiving a lot of notifications

I really hope you chose to implement it, it would be so great !
Regards,
Leonard

**Comment by fcaronte** [comment]
Ok understand, we can add as request but I don't know when could be implemented

**Comment by leonardcapillon** [comment]
Great, thank you a lot. I will be waiting
Best regards
