### ISSUE TITLE
Service app unloads from memory

### ISSUE THREAD

**Issue by innomaxx** [AmazMod/AmazMod#774]
Hi AmazMod community!

I'm actually actively using this project and appreciate all the development efforts doing to make it better.
Some time ago I noticed that often watch's service app stops to show notifications from the companion app (Custom UI) or shows it with noticeable delay for fractions of second.

At these times in the service app widget UI button "Keep Awake" looks like unfilled circle (inactive). Every time I press it again to enable "Keep Awake", but a bit later the problem comes again and this button has "unfilled circle" appearance again.

* Device : Amazfit Pace A1612
* ROM version : untouched stock 2.8.4.0
* Service app version : 1904
* Companion app version : 1.1.8 (build 217)
* Device admin for the service app is enabled

Please tell me what type of another information I have to provide (logs,...) for further investigation.

Best regards,
Max

**Comment by fcaronte** [comment]
Your problem are cause from phone app side battery saver option, a lot of phone have more setting about battery saver and you should add to ignore list both amazfit and Amazmod app.

About keep awake is used to keep your watch unlocked with screen on so I suggest to keep it disabled

**Comment by innomaxx** [comment]
> you should add to ignore list both amazfit and Amazmod app

Both of them already have no restrictions under MIUI Battery Saver power options

**Comment by fcaronte** [comment]
Sometimes I noted this problem if use an APK Watchface, and maybe you can try the new Dev version edgy but it need to completely remove actual version (on phone you can save a backup) I'm on MIUI top and work correctly for me

**Comment by fcaronte** [comment]
> > you should add to ignore list both amazfit and Amazmod app
> 
> Both of them already have no restrictions under MIUI Battery Saver power options

Probably you forget to add the lock to Amazmod and amazfit app from the recent app (long press on app preview)

**Comment by innomaxx** [comment]
> you forget to add the lock to Amazmod and amazfit app from the recent app

No, both of apps are already locked up.
I don't think it's phone-side issue. It looks like watch's system LMK kills service app daemon or trying to restrict its activity in some way.

**Comment by fcaronte** [comment]
how much app/apk watchface have you installed? android try to keep everything open and apk watchface usually stay running when the aren't in use too. i suggest to install only one watchface apk at time

**Comment by innomaxx** [comment]
> how much app/apk watchface have you installed?

Only two : GreatFit (currently active) and ICWF.
I had just removed the last one and I will check this case. Please leave this issue opened.

**Comment by innomaxx** [comment]
@fcaronte no changes. AmazMod service is still frequently being killed by OS.

**Comment by fcaronte** [comment]
If you want, you can try to remove completely phone and service app and try install the Dev edgy version (unfortunately you can't update directly because they ha different signature). I'm always on Dev version and haven't this issues with my redmi note 7

**Comment by innomaxx** [comment]
Sorry for a long pause. Today I had removed stable and installed Dev edgy version - the problem is still here. Is here some debug logging functionality present? We would look inside and will have better understanding of situation.

**Comment by fcaronte** [comment]
Check if version number is 1905 and phone side 1.1.9 and yes edgy are compiled as debug version so you can check more log

**Comment by innomaxx** [comment]
Maybe it will clarify the situation. Here are logs extracted from watch : https://www.dropbox.com/sh/oljwy1yphvn50j4/AAD8ebpYGF6CVQ-_EX9YwMHoa?dl=0

**Comment by innomaxx** [comment]
@fcaronte any updates?

**Comment by fcaronte** [comment]
> @fcaronte any updates?

All work correctly for me, can you try removing greatfit watchface and use a stock watchface or maybe a simple wfz?

**Comment by innomaxx** [comment]
@fcaronte 
I had switched back to the release of AmazMod, changed GreatFit watchface to one of the system available and noticed no issues with custom UI notifications anymore. I think AmazMod isn't compatible enough with GreatFit and I will try contact GreatFit developer to discuss it.

Please leave this issue opened during all the investigation

**Comment by fcaronte** [comment]
What's your device? Greatfit Dev work on Amazmod too so he can read here :P

Il sab 22 feb 2020, 14:38 Max Hubach <notifications@github.com> ha scritto:

**Comment by innomaxx** [comment]
Redmi Note 5 Pro
Android 8.1.0
MIUI 9.5.19 Stable

**Comment by fcaronte** [comment]
Watch model ?

Il sab 22 feb 2020, 14:41 Max Hubach <notifications@github.com> ha scritto:

**Comment by innomaxx** [comment]
Amazfit Pace A1612, as in the first comment

**Comment by fcaronte** [comment]
Sorry i forgot about that, maybe you can try the new greatfit beta posted on xda by @GreatApo

**Comment by fcaronte** [comment]
> @fcaronte
> I had switched back to the release of AmazMod, changed GreatFit watchface to one of the system available and noticed no issues with custom UI notifications anymore. I think AmazMod isn't compatible enough with GreatFit and I will try contact GreatFit developer to discuss it.
> 
> Please leave this issue opened during all the investigation

At the and this is why usually I use wfz or stock watchface. I had this problem with a lot of APK Watchface at beginning seem work then start to screen stay off and you ear only vibration (if you immediately unlock watch manually you will see the notification) but with wfz and stock wf this isn't happening anymore (maybe is a low resources problem ?)

**Comment by innomaxx** [comment]
Thanks for explanation. Currently I have GreatFit v3.8 installed, I'll try the latest release and check it.

**Comment by GreatApo** [comment]
It could potentially be a CPU load problem because SLPT service is restarted when a notification arrives and the notification counter updates that value.

**Comment by innomaxx** [comment]
A couple of days ago I upgraded GreatFit to v4.1, now freezes are much less often than before.

**Comment by innomaxx** [comment]
@GreatApo the issue is back. Do you have any ideas or suggestions how to fix it? Which kind of data I need to provide to help you?

**Comment by GreatApo** [comment]
> @GreatApo the issue is back. Do you have any ideas or suggestions how to fix it? Which kind of data I need to provide to help you?

To start with, disable all custom widgets, use one default widget (those that you can find in stock watchfaces) and don't use weather widget too. Then reboot. Let me know if the problem is still there.

If that work, SLPT refresh is the problem.

**Comment by GreatApo** [comment]
Nope, my bad, that will not work also. I am going to try a fix tonight. I will let you know.

**Comment by innomaxx** [comment]
> Nope, my bad, that will not work also. I am going to try a fix tonight. I will let you know.

I'm looking forward for any updates, thanks a lot.

**Comment by GreatApo** [comment]
Let's move to one issue: https://github.com/AmazMod/AmazMod/issues/702
