### ISSUE TITLE
Function request: Answer all kinds of messages on the watch (from Viber, etc...)

### ISSUE THREAD

**Issue by YasDevGroup** [AmazMod/AmazMod#777]
Telegram is great, but still, it's not as popular as Viber for now, and most of my conversations are on Viber (and not only my), so I want you to support this option.

**Comment by fcaronte** [comment]
If your used app support replying from statusbar, should work and you only need to add that app inside Amazmod app setting

**Comment by YasDevGroup** [comment]
For me it worked only when I've dissected and then selected that apps again, but still, Thanks!

**Comment by 1immortal** [comment]
Hi, Viber and Line were tested on the latest Edgy builds, if a specific client is not working, please provide logs and open an issue for that.
As of Edgy, a new release is on its way :)
