### ISSUE TITLE
Music files uploaded to watch won´t appear in Media player

### ISSUE THREAD

**Issue by Medard22** [AmazMod/AmazMod#779]
Hi, sometimes I use AmazMod to upload new music to my watch. My problem is that the watch won´t initiate media scan after upload, so the music won´t show in Media player unless I restart the watch. I can either upload music using Amazfit app - which is clunky (it lists all music files in one big list) and uses WiFi for media upload, or via USB cable. 
I wonder if you could add a new feature in the Tweaking section, that would initiate media scan on the watch. Or initiate media scan after every file upload, but I guess that would negatively impact battery life. 
I use latest bleeding edge builds of both phone and watch app. Thanks.

**Comment by fcaronte** [comment]
have you try to use the launcher reboot, or maybe the clear memory option?

**Comment by Medard22** [comment]
Sorry I didn´t comment sooner. I just tried both options and unfortunately it´s not enough. Unless you reboot the watch the uploaded music files won´t appear in Music player.

**Comment by fcaronte** [comment]
this command should force media file scan. try to send using amazmod from the tweaking menu and let's me say if work.

adb shell am broadcast -a android.intent.action.MEDIA_MOUNTED -d file:///sdcard

**Comment by Medard22** [comment]
Running the command didn´t work at first, but after restarting the launcher the music files appeared in Music player. Either it takes a long time to finish media scanning, or the launcher restart is required.

![Screenshot_20200127_213111_com edotassi amazmod](https://user-images.githubusercontent.com/42897361/73211969-894c7d00-414d-11ea-8f5b-53c310e4756a.jpg)

**Comment by fcaronte** [comment]
> Running the command didn´t work at first, but after restarting the launcher the music files appeared in Music player. Either it takes a long time to finish media scanning, or the launcher restart is required.
> 
> ![Screenshot_20200127_213111_com edotassi amazmod](https://user-images.githubusercontent.com/42897361/73211969-894c7d00-414d-11ea-8f5b-53c310e4756a.jpg)

command is take correctly, probably is your first opinion and need a little time to re-scan again (on internet i read about some guys suggest to use this command but directly to music folder probably  to be more fast.
If you can check the command, wait a little and check if music is update, then let's me know if work without need a launcher reboot

**Comment by GreatApo** [comment]
I would suggest a feature that runs the command at the target folder directly after a sound file format is moved to watch.

**Comment by fcaronte** [comment]
> I would suggest a feature that runs the command at the target folder directly after a sound file format is moved to watch.

Exactly if the command is work directly to sdcard/music we can use it

**Comment by Medard22** [comment]
It seems the Amazfit Music player won´t refresh the track list until you restart the launcher. I ran the command:
` adb shell am broadcast -a android.intent.action.MEDIA_MOUNTED -d file:///sdcard/music`
Waited like 5 minutes and then opened the music player with no luck. The new songs appeared immediately after i restarted the  launcher. 

I wonder how the official Amazfit app transfers music. It sends files by creating a local wifi hotspot, the launcher reboot is however not required and the music appears in music player right away. Perhaps there is a command for this in the music player app making it refresh it´s playlist  after succesfull transfer.

**Comment by Medard22** [comment]
Clearing memory unfortunately doesn´t help.  Even running the command and restarting launcher is not always consistent and sometimes it may fail. 
The best way would be figuring out how the official app does music transfers, but I guess that would require some reverse engineering of either the amazfit app or music player app in watch :(

**Comment by GreatApo** [comment]
Workaround based on [Pascal's answer on this stackoverflow post](https://stackoverflow.com/questions/3300137/how-can-i-refresh-mediastore-on-android). (Commit 31bfc403892eb95e64f9523f195aca5f03a8f156)

My music widget was refreshed too. Install the latest bleeding edge service and let us know of the outcome...
