### ISSUE TITLE
Hourly gong doesn't work

### ISSUE THREAD

**Issue by GarryBu** [AmazMod/AmazMod#787]
The dev version with the function is installed, the menu item is turned on, but the gong does not sound and there is no vibration.

**Comment by GarryBu** [comment]
suggest making a custom vibration for the hourly gong. For example double short vibration

**Comment by fcaronte** [comment]
I try in this moment Hourly chime on the edgy version and work correctly. It has just two short vibration and on verge only play the sound (the other device hasn't a speaker so can only vibrate). I don't remember exactly but on global version should work too a maybe simple you have a lover vibration intensity and you don't take care about it

**Comment by GarryBu** [comment]
Doesn't work on Stratos on version edge in all modes. Vibration in default. I found one application for android, it works on the clock, but can not be configured.

**Comment by fcaronte** [comment]
Are you sure to install correctly the edgy version? You need to remove
device admin and uninstall the old service before try to install the edgy
or you will stay on the old version and can't work correctly if edgy is
installed only on one side, you need all two APK service+app updated
correctly, then try to enable from Amazmod phone setting or from the
service menu

Il lun 27 gen 2020, 07:21 GarryBu <notifications@github.com> ha scritto:

**Comment by GarryBu** [comment]
I have the latest edge version and the latest app on my phone. The function is enabled, but does not work.

**Comment by fcaronte** [comment]
Try to remove the other app you use, and say to me the service and app version you read. Then take log

**Comment by GarryBu** [comment]
[amazmod.log](https://github.com/AmazMod/AmazMod/files/4115875/amazmod.log)

**Comment by fcaronte** [comment]
Here is see only you enable it, but need a service side log to see if have
some problems

Il lun 27 gen 2020, 08:08 GarryBu <notifications@github.com> ha scritto:

**Comment by GarryBu** [comment]
How to enable logging in the service?  Where to see the file?

**Comment by fcaronte** [comment]
On Amazmod stats menu use the last bottom big button to create a packet of
both two the log

Il lun 27 gen 2020, 08:16 GarryBu <notifications@github.com> ha scritto:

**Comment by GarryBu** [comment]
[log_bundle.log.gz](https://github.com/AmazMod/AmazMod/files/4115904/log_bundle.log.gz)

**Comment by fcaronte** [comment]
Sorry I forgot to say you to set to take debug level logging, at the end of
Amazmod setting on log level put debugging then reproduce the bug and take
a new log

Il lun 27 gen 2020, 08:22 GarryBu <notifications@github.com> ha scritto:

**Comment by GarryBu** [comment]
What menu item should be on?
Error warn Info debug trace?
My English is poor :(

**Comment by fcaronte** [comment]
![IMG_20200127_090015](https://user-images.githubusercontent.com/26366403/73158236-861ca700-40e3-11ea-87d3-73f11c0caed4.jpg)
Here

**Comment by GarryBu** [comment]
![Screenshot_2020-01-27-11-02-58-561_com edotassi amazmod](https://user-images.githubusercontent.com/60334441/73158347-9ee18880-40f4-11ea-9d6c-d9bde1bf1045.jpg)

**Comment by GarryBu** [comment]
[log_bundle.log(1).gz](https://github.com/AmazMod/AmazMod/files/4116029/log_bundle.log.1.gz)
[amazmod(1).log](https://github.com/AmazMod/AmazMod/files/4116030/amazmod.1.log)

**Comment by GarryBu** [comment]
full log in trace mode

[log_bundle.log(2).gz](https://github.com/AmazMod/AmazMod/files/4116117/log_bundle.log.2.gz)
[amazmod(2).log](https://github.com/AmazMod/AmazMod/files/4116118/amazmod.2.log)

**Comment by GarryBu** [comment]
Work if the vibration duration is 300ms. 200ms does not work. 
[amazmod(3).log](https://github.com/AmazMod/AmazMod/files/4116147/amazmod.3.log)
[log_bundle.log(3).gz](https://github.com/AmazMod/AmazMod/files/4116148/log_bundle.log.3.gz)

**Comment by fcaronte** [comment]
Try using 200ms and work too, because chime vibration of ore this setting
and use a custom one

Il lun 27 gen 2020, 09:36 GarryBu <notifications@github.com> ha scritto:

**Comment by GarryBu** [comment]
200ms not working
[log_bundle.log(4).gz](https://github.com/AmazMod/AmazMod/files/4116230/log_bundle.log.4.gz)
[amazmod(4).log](https://github.com/AmazMod/AmazMod/files/4116231/amazmod.4.log)

**Comment by GarryBu** [comment]
[amazmod(4).log](https://github.com/AmazMod/AmazMod/files/4116234/amazmod.4.log)

**Comment by 1immortal** [comment]
Heya,

This tested with the latest edgy of today on S3 and S with 2.3.10.4 and 2.3.11.1, in all cases the hourly vibration worked flawlessly. please try to remove the service, reinstall it and make sure that you granted admin rights to AmazMod on the watch, and if it still won't work, please try to factory reset your watch.

**Comment by GarryBu** [comment]
During the experiment, it became clear that the hourly gong does not work with a vibration duration of 200ms.  Correction;  set vibration length to 300ms. Watch Stratos2

**Comment by fcaronte** [comment]
> During the experiment, it became clear that the hourly gong does not work with a vibration duration of 200ms. Correction; set vibration length to 300ms. Watch Stratos2

Is not clear nothing because for all guys I ask to check, work correctly with this option too is something wrong with your watch setting

**Comment by GreatApo** [comment]
Hourly chime works on my watch too...

**Comment by 1immortal** [comment]
@GarryBu - what rom version/stock/modded are you running? I've tested this issue on Verge/Stratos/Pace devices, both stock and Stratosfied ROMs, and on each one of them, it worked without any issues.

**Comment by GarryBu** [comment]
"duration of vibration 200ms" tried?

**Comment by 1immortal** [comment]
yes, worked on Stratos and Verge without any issues.

**Comment by 1immortal** [comment]
@GarryBu  can you provide any additional input before this issue gets closed?
I've tested this with Android 7 and 9, on 4 different physical watches, and on all it works as defined, with edgy builds.

**Comment by GarryBu** [comment]
On other versions with a long vibration of 200ms, notifications come regularly Can close
