### ISSUE TITLE
VK - v kontakte - user unable to reply

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#800]
reported by email - lich20153@yandex.ru - he can reply by his mobile, there's no reply option on the watch.
Please see attached logs.
[log_bundle (2).log.gz](https://github.com/AmazMod/AmazMod/files/4148404/log_bundle.2.log.gz)

**Comment by fcaronte** [comment]
He can reply directly from statusbar?

**Comment by 1immortal** [comment]
yes, checked it with him, his reply was :
![20200203_174944](https://user-images.githubusercontent.com/5845985/73694868-9fc07e80-46e1-11ea-8f66-c975d16c1da1.jpg)

**Comment by fcaronte** [comment]
the log is unreadable for me, can't open it

**Comment by 1immortal** [comment]
fixed log file, thanks :)
[log_bundle (4).log.gz](https://github.com/AmazMod/AmazMod/files/4152503/log_bundle.4.log.gz)

**Comment by 1immortal** [comment]
Well, after @diotto investigation, it seems as VK app work in a custom way in the notification shade, and its unfortunately impossible to tap in for replies from the watch.
