### ISSUE TITLE
App Manager Dosent Show All Apps But APK IS installed

### ISSUE THREAD

**Issue by Tpelaaja** [AmazMod/AmazMod#809]
So i Installed flappy bird For My Pace watch but App Manager Dosent see it or app's screen either Dosent reconize it Any fix?

**Comment by fcaronte** [comment]
Are you sure this APK is compatible with pace? A lot of app seem installing but are unsupported

**Comment by 1immortal** [comment]
try to reboot the watch and check if the app is under the app manager.

**Comment by Tpelaaja** [comment]
Nope. Did it over 10 times. And If Theres a list of Apps that work with The Pace that would be nice & I actually Have a Moto360 with Similar Specs To The Space + Thats The Westin version. Looking For More apps

**Comment by Tpelaaja** [comment]
Just got a spreadsheet of working Apps. Works!
