### ISSUE TITLE
[Widget] SOS Button

### ISSUE THREAD

**Issue by gerciljunio** [AmazMod/AmazMod#826]
firstly, congratulations on AmazMod, mainly because it already comes with the built-in AmazfitInternetCompanion and of course, the many other useful functions for smartwatches, I am a hardware and software developer and I usually create products for personal use for my family and friends, everyone has a amazfit both verge and pace.

recently, I created some apps to control the automation of my home, etc ... and I thought ... It would be nice if it had a built-in function in AmazMod to put an SOS widget and configure in the smartphone's AmazMod application for which URL the signal will be sent when the button is pressed, in this way, it is up to each user to put their URL or, to use existing services (cloud) API, such as SMS services, push, calls, etc.

to go further, AmazMod would also be nice when detecting the pressed SOS button, sending the smartphone's latitude and longitude in the URL, with that, it is not even necessary to use the clock's location.

Detail of requested feature (SOS Button):

 * Include widget with SOS button on the clock
 * Define in the application for the smartphone in settings, which will be the URL called using AmazfitInternetCompanion
 * When pressing the SOS button on the watch sends a request to the URL defined in the application settings on the smartphone and if possible, automatically appends the smartphone's latitude and longitude to that URL

**Comment by 1immortal** [comment]
Hi @gerciljunio ,

That's actually a very nice idea, and it sounds like you wrote half of it inside your head :)
This can be taken even further:
If we can access the accelerometer data on the watch, it can be automated - if a watch experiences a fast acceleration downwards and no additional movement, it will report to the defined benefits.
@GreatApo @diotto @fcaronte  - what do you think guys?

**Comment by gerciljunio** [comment]
@1immortal Glad you liked the idea, in fact, there are many possibilities with that, if you add the accelerometer then, I venture to say that the sky is the limit, lol! It is also possible to create webhooks in applications such as MacroDroid and Tasker, and create actions to send SMS, make calls, etc ... this way when you press the SOS button, call the webhook and execute the defined actions ...

Anyway, I think sending data from the accelerometer along with the location and whatever else is possible (LOL), it will be great! =)

I'm looking forward to it!

**Comment by GreatApo** [comment]
That is a nice idea. Indeed you could make a item in the service menu that will cause an action of the phone app, that won't be that difficult. After that it depends on what you want to do, msg, tasks, URL get/post requests... however that's a big and too general list.

I would propose on giving a try to code exactly what will meet your needs and that could potentially evolve to sth broader.
