### ISSUE TITLE
Little database.

### ISSUE THREAD

**Issue by dgcasana** [AmazMod/AmazMod#835]
If you are traveling and your mobile is stolen, or you lose it, you have a problem but also surely you will not remember any phone number of your family to ask for help.
It would be nice to have a text file with several phones, perhaps a password, a shopping list ... no more than 50 lines of text that could be managed from the phone app and you always had it accessible from the watch.

**Comment by 1immortal** [comment]
some sort of a basic data vault?

**Comment by dgcasana** [comment]
Yes, I was thinking about the old Casio's databank, but synchronized with the phone

**Comment by fcaronte** [comment]
As now Amazmod file manager can read text file, so you can keep what you want inside it

**Comment by GreatApo** [comment]
That sounds like a great security data compromise while there are easier ways to store data safely. Nowadays all your phones along with some other data are stored online, like google contacts, which makes almost impossible to loose them. Accessing those data is easy from any device with internet access, that you will need anyway to extract the data stored in the watch. If you want to see those data from a text reader directly in the watch, then what if you lose the watch? everyone will have access on those data, as long as they have access in your watch, even while you sleep.

Additionally, I don't see how a shopping list will help if you loose your phone. That is more like a notes feature, or synchronizing your google keep to watch, which is completely different.

I would suggest an online password manager. Many users use Amazmod and we can't compromise security in that degree. On the other hand, providing something solid would be time consuming while I don't see many users in need of a watch password manager.
