### ISSUE TITLE
App shortcut in launcher

### ISSUE THREAD

**Issue by nickreiner** [AmazMod/AmazMod#836]
Isn't there supposed to be a shortcut to an app in the AmazMod launcher if you install a new app?

There was before when I was testing apps out, but I can't get a shortcut for the Amazlist app now. I tried reinstalling the app and restarting the launcher and watch, but there's still no shortcut for the app.

https://i.imgur.com/qE6KmOX.png

**Comment by fcaronte** [comment]
If the app is compatible should appear here after a long click on your circled text "apps"

**Comment by nickreiner** [comment]
Ok great, that did it. Thanks
