### ISSUE TITLE
Stratos 3 - Heart-rate Chart <- No chart data available

### ISSUE THREAD

**Issue by derekyiukk** [AmazMod/AmazMod#842]
I'm using Stratos 3. In the app, there is chart for battery usage. However, the heart-rate chart is not shown and with message 'No chart data available.' What should I do to have it displayed. Thanks.

**Comment by fcaronte** [comment]
It will show all your manual heart rate measurements

**Comment by derekyiukk** [comment]
Thanks a lot.
