### ISSUE TITLE
Watch in DND, custom notifications are not saved

### ISSUE THREAD

**Issue by GreatApo** [AmazMod/AmazMod#847]
When watch is DND, notifications are send, user is not disturbed, notification counter is updated however, custom notifications are not stored in the notification list. I prepared part of the code in commit b1804b2ee9578727994a094011a7895a94c6eaa7 however a change still needs to be make because app crashes when opening notifications list (more info in code).

My code is in comment to avoid the crashes.

**Comment by fcaronte** [comment]
finish your work here. 
https://github.com/AmazMod/AmazMod/commit/85d8e99c8d8ce638f84b3348a810fadc8816d6e7
and then move there
https://github.com/AmazMod/AmazMod/commit/5bb09689652273eb02428ca6d9519c71150df49f
I think we can close
