### ISSUE TITLE
Migrate from Android Preference to AndroidX Preference

### ISSUE THREAD

**Issue by diotto** [AmazMod/AmazMod#856]
On Android 10 the Android Preference library was deprecated. We must migrate to the new AndroidX Preference library.

https://developer.android.com/guide/topics/ui/settings

**Comment by diotto** [comment]
https://joebirch.co/uncategorized/exploring-android-jetpack-preferences/

**Comment by diotto** [comment]
Search in preferences: https://github.com/ByteHamster/SearchPreference/blob/master/README.md

**Comment by EgorOA** [comment]
Is it the reason to use SDKversion 29 now?
I can't install a couple of days latest releases on my phone with Android 6.0.1 :(

**Comment by diotto** [comment]
Hello @EgorOA , unfortunately we need to follow Android versions and upgrade our code. We upgraded to sdk 29 some time ago but I switched minimum sdk to 25 last week, this is what broke amazmod to you.
I'll try to revert it back to 21 but soon we'll have to change this again or we can't use new features on app.

Best regards!

**Comment by fcaronte** [comment]
https://github.com/AmazMod/AmazMod/commit/03ecc2fda269c982f1a39c83ed9ef00dcb05370290% done here miss some fix here and there but is almost complete

**Comment by EgorOA** [comment]
> ...unfortunately we need to follow Android versions and upgrade our code. We upgraded to sdk 29 some time ago but I switched minimum sdk to 25 last week, this is what broke amazmod to you.
> I'll try to revert it back to 21 but soon we'll have to change this again or we can't use new features on app.

I think that you have to make announce to inform users about that. For me this is not good news and I guess that I'm not alone

**Comment by fcaronte** [comment]
@EgorOA this API level increase what mean for you? Get error during install?

**Comment by EgorOA** [comment]
> @EgorOA this API level increase what mean for you? Get error during install?
Exactly

**Comment by fcaronte** [comment]
Setting search should work fine now :)

@EgorOA on last edgy I put again support for api 21 let's say if work and new search bar on setting is work too

@1immortal for you try to check if with last edgy you have again lag problem on stratos 3

**Comment by EgorOA** [comment]
It's ok now!
Thank you very much!!!

**Comment by diotto** [comment]
@fcaronte your downgrade to 21 will make amazmod crash in Android 5.0. There as option that does not work.
SettingsActivity.java line 178:         result.highlight(myPreferenceFragment, getResources().getColor(R.color.colorCharging, getTheme()));

The getColor needs API 23.
I'm upgrading to 23, which is still compatible with @EgorOA Android 6.0 .
Can you test if it's working for you @EgorOA  ? Thanks

**Comment by EgorOA** [comment]
> Can you test if it's working for you @EgorOA ?

It's ok for me, thanks!

**Comment by fcaronte** [comment]
About android.preference we must replace everywhere is called right?

**Comment by fcaronte** [comment]
i think migration to android x preference is finished. if you can confirm we can close this
