### ISSUE TITLE
Humidity and wind direction - N/A

### ISSUE THREAD

**Issue by buczoprazy** [AmazMod/AmazMod#862]
Hi,

From a few weeks my stratos not showing wind speed and humidity.
Yesterday I have enabled option send wheater data in Greatfit/calendar menu and it showed only for one day. This morning again is showing N/A.

Do you have any advice howto fix it please?

![IMG_20200417_074636](https://user-images.githubusercontent.com/53972032/79540669-724c6580-8080-11ea-8399-ac3eb7242672.jpg)
![Screenshot_20200417-075525](https://user-images.githubusercontent.com/53972032/79541043-0dddd600-8081-11ea-9b9c-870ad4014389.jpg)
![Screenshot_20200417-075510](https://user-images.githubusercontent.com/53972032/79541071-18986b00-8081-11ea-9997-89a0afc38a3c.jpg)

**Comment by fcaronte** [comment]
As you can see from your screenshot, you haven't put your API key and so Amazmod weather can't work correctly. You need to go to openweather site, registered for free and will get your API key for free. Amazmod has a free key for when you put work without a key, but probably is full and can't work correctly so use your key is the best solution

**Comment by buczoprazy** [comment]
> As you can see from your screenshot, you haven't put your API key and so Amazmod weather can't work correctly. You need to go to openweather site, registered for free and will get your API key for free. Amazmod has a free key for when you put work without a key, but probably is full and can't work correctly so use your key is the best solution

Wow,cheers mate! I was thinking that something is not right with my wach.
I really appreciate your help.Thank you.
