### ISSUE TITLE
Stratos 3 - invalid date on HR readings

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#873]
tested with 1910
![IMG_20200511_195006](https://user-images.githubusercontent.com/5845985/81639438-9eab9580-9424-11ea-98aa-6b2d4b5b1247.jpg)

**Comment by fcaronte** [comment]
The bug Is the calendar data right? Confirm this

**Comment by 1immortal** [comment]
yes x_x

**Comment by fcaronte** [comment]
Fixed on last Dev
