### ISSUE TITLE
Edgy - Hebrew/Arabic notification handling

### ISSUE THREAD

**Issue by 1immortal** [AmazMod/AmazMod#884]
Sometimes it works fine, and sometimes it behaves like crazy and doesn't work at all.
No Hebrew fonts on the watch, uses only Hebrew provided by AmazMod.
![Untitled](https://user-images.githubusercontent.com/5845985/82546464-c905fd00-9b60-11ea-9c78-802d8577c1d4.png)

[amazmod (6).log](https://github.com/AmazMod/AmazMod/files/4661679/amazmod.6.log)

**Comment by bouhady** [comment]
[log_bundle.log.gz](https://github.com/AmazMod/AmazMod/files/4661825/log_bundle.log.gz)

**Comment by 1immortal** [comment]
![20200524_102009](https://user-images.githubusercontent.com/5845985/82748179-9c442680-9da8-11ea-88bd-3702236b0b1c.jpg)

**Comment by 1immortal** [comment]
And one more log of xxxx on Hebrew text, tested with Stratos and latest edgy
[log_bundle.log.gz](https://github.com/AmazMod/AmazMod/files/4673142/log_bundle.log.gz)

**Comment by fcaronte** [comment]
Fixed here
https://github.com/AmazMod/AmazMod/commit/97e08965385fa28676b0ac37fc9ac0ac46e60bfe

Notification replies support here
https://github.com/AmazMod/AmazMod/commit/b488dd9ab2a159d8cd4a518183ef71f360ebcfd9
