### ISSUE TITLE
DM Messages

### ISSUE THREAD

**Issue by EllyptiumOfficial** [AmazMod/AmazMod#885]
AMAZing work. I've noticed that I can't reply to Instagram Direct Messages. Can you please add it?

Thanks a lot!

**Comment by 1immortal** [comment]
Hi,

On your smartphone, is it possible to reply directly to DMs via the notification shade?

**Comment by EllyptiumOfficial** [comment]
Yes, I can. And if I mark the custom UI notification, I still can't.

**Comment by fcaronte** [comment]
I try just now and work correctly, is possible you reply to a notification just removed from watch? If yes should be the problem

**Comment by 1immortal** [comment]
Hi,

DMs been tested with the latest edgies on several devices, and no issues were detected.
Please try to reproduce/recreate the issue, and as @fcaronte stated above, it could be a condition of a removed/read notification reply after it got actually removed from the notifications.

**Comment by EllyptiumOfficial** [comment]
Ok, thanks for all. That was the problem. Thank you again. 

Just one more thing, I've been having performance issues such as launcher blocks and mass notification vibration and sound with only one notification. Should I open a new issue brach or can we disscus it here?

**Comment by 1immortal** [comment]
Please open a new one.

Thanks!
