### ISSUE TITLE
screen time wake on amazfit verge

### ISSUE THREAD

**Issue by nexaz013** [AmazMod/AmazMod#892]
when i install latest amazmod, my amazfit verge have issue with screen time so long to shut down (enter save mode, off screen) sceen wake about 3 minute (original just less 1 minute ithink)

**Comment by SerPep** [comment]
Same on my Pace! It's no suitable for battery life...

**Comment by nexaz013** [comment]
> Same on my Pace! It's no suitable for battery life...

oh same at pace? hmm we wait the fix

**Comment by stefanandessmann** [comment]
Same on my Stratos2, went back to 1.2 and 1910 - all fine again

**Comment by fcaronte** [comment]
Usually this is happen when you start a service update but then isn't installed correctly, a watch reboot reset the timeout, but probably you try to update a different signature apk and so you need to manually remove old service and then install new one

**Comment by SerPep** [comment]
I don't think is my case, the service seems correctly installed, but I'll try to uninstall it and re-install it again

**Comment by 1immortal** [comment]
Please try to reboot your watch after an upgrade to see if the wake solved or not. if the screen still remain on after the reboot, please go to the AmazMod widget and grant admin permission
![screen](https://user-images.githubusercontent.com/5845985/83163886-39d68780-a114-11ea-9323-d5d25b5f2e81.png)

**Comment by SerPep** [comment]
Just tried, but nothing changed, it's still alive!!!

**Comment by 1immortal** [comment]
@SerPep was it an upgrade from a previous service installation, or a clean one, ran by the installer/manual adb installation?

**Comment by SerPep** [comment]
It was an upgrade from the 1910 performed by the AmazMod app, just auto-updated from PlayStore. Now I've just resettled the watch, added again it to my amazfit profile, and I'm going to installa again the 1910. I'll try to update again from the smartphone and I'll see what will happen. Any suggestion?

**Comment by stefanandessmann** [comment]
> Usually this is happen when you start a service update but then isn't installed correctly, a watch reboot reset the timeout, but probably you try to update a different signature apk and so you need to manually remove old service and then install new one

Thanks, a clean install did it

**Comment by fcaronte** [comment]
i add a more check to avoid this problem of timeout stuck. install last edgy to try.

**Comment by nexaz013** [comment]
My problems solve only clear data in  amazmod service on my amazfit verge
