### ISSUE TITLE
Apk install not working

### ISSUE THREAD

**Issue by GuizaoBR** [AmazMod/AmazMod#893]
I can't install apk on Amazmod 1911, I can install just with adb...

**Comment by fcaronte** [comment]
seem that 1911 release have some strange thing, try to install last edgy version service
https://github.com/AmazMod/AmazMod/releases/download/edgy/AmazMod-service-release-dev-1911-202005301150.apk

**Comment by GuizaoBR** [comment]
@fcaronte download link not working

**Comment by fcaronte** [comment]
yes because now is going to be out official to playstore but you can take here
https://github.com/AmazMod/AmazMod/releases/tag/1.2.1_228-1912
