### ISSUE TITLE
Using keyboard on Amazfit Pace

### ISSUE THREAD

**Issue by matousvolf** [AmazMod/AmazMod#894]
After installing TouchOne keyboard to my Pace, I changed the input method, but nothing changed. When I try to type some text, I have to use my phone. Then I realized that the input method does not save. When I change it and tap Close, it resets to the default option.

**Comment by fcaronte** [comment]
Yes sometimes happen, need some time to load. On inputs method chose touchone click 2\3 time, wait a little and test using field box to test

**Comment by micrusa** [comment]
Try on 1912, it should work fine

**Comment by matousvolf** [comment]
Yes, now it works. Thank you for making my life more comfortable guys!
