### ISSUE TITLE
Reply not working on telegram

### ISSUE THREAD

**Issue by GuizaoBR** [AmazMod/AmazMod#897]
I tried reply messages on telegram with Amazmod 1912, I received the send confirmation but the message aren't sended for real. I've tested on whatsapp and the reply work well with him

**Comment by fcaronte** [comment]
I try and is working, but yes sometimes can happen replying are not sent really, what's you watch model? If is stratos 3 problem is the slow connection problems

**Comment by GuizaoBR** [comment]
My model is verge A1811.
For me always when I tried with telegram didn't work :(

**Comment by gtung3388** [comment]
> I try and is working, but yes sometimes can happen replying are not sent really, what's you watch model? If is stratos 3 problem is the slow connection problems

i got similar issue , i m S3, the amazod connected fine yesterday with my android phone, not connect anymore this morning, even run  the  1912 exe file from pc to S3 directly...

**Comment by fcaronte** [comment]
> > I try and is working, but yes sometimes can happen replying are not sent really, what's you watch model? If is stratos 3 problem is the slow connection problems
> 
> i got similar issue , i m S3, the amazod connected fine yesterday with my android phone, not connect anymore this morning, even run the 1912 exe file from pc to S3 directly...

S3 have connection problem, for me when I can't connect correctly I need to force close amazfit app and the it connect again correctly. About the replies on S3 in fresh connection work correctly then after a while it start to not send correctly but probably is caused by connection problems. When I was using verge I never get replies problem with any app 🤷🏻‍♂️

**Comment by gtung3388** [comment]
i figured out , if found the connection not connect with long period, try the restore at the amazmod Setting , will back to work .. Will see, thks ur sharing.

**Comment by GuizaoBR** [comment]
@fcaronte i discovered the problem. When I add password to acess telegram he block the reply messages from notifications, so I disabled that and reply from amazmod worked very well.
Sorry from my mistake, hahahaha!
