### ISSUE TITLE
Can't change input method
it just can't save the change

### ISSUE THREAD

**Issue by LCS-Official** [AmazMod/AmazMod#900]

**Comment by 1immortal** [comment]
Hi,

are you using Edgy or the stable 1.2.1/1912 ?

**Comment by fcaronte** [comment]
Please try to be slow during this step and press more time, then wait a little and try if work on the field text. It use an ADB command and so it need some second to be applied

**Comment by 1immortal** [comment]
and on what watch its hapenning?

**Comment by LCS-Official** [comment]
I'm using 1. 2. 1

**Comment by fcaronte** [comment]
And Watch service? The keyboard setting is related only on service side app. Install the lasted 1912 and try as say on the previous message

**Comment by LCS-Official** [comment]
I just clicked the other input method ,but when I click close,it came back again

**Comment by fcaronte** [comment]
Click 2\3 time on touchone keyboard (or what you use) then wait a little and try the text field and again what your service version?

**Comment by LCS-Official** [comment]
... It still don't work

**Comment by LCS-Official** [comment]
What will happen if I uninstall HuamiIME?

**Comment by fcaronte** [comment]
You don't need to uninstall and probably need rotto to be do, take a watch
log after doing the steps show by me, and send here. (You can use AmazMod
phone app to take a zip of watch log)

Distinti saluti.
Francesco Caronte

Il gio 4 giu 2020, 13:18 LCS-Official <notifications@github.com> ha scritto:

**Comment by LCS-Official** [comment]
Thanks a lot 
But could you please add a save button there?

**Comment by fcaronte** [comment]
Umh nope because is a direct ADB command and don't need to save but simple to wait a little before close. But yes I will try to give a check if can be better

**Comment by fcaronte** [comment]
ok i give a check with log, and is work correctly, simple need some time to apply selected keyboard, and so if you go to test immediately you will get the old huami keyboard but during this, your selected keyboard is enabling and so if you go to test again you will get the correct one

**Comment by LCS-Official** [comment]
Thanks a lot!
