### ISSUE TITLE
Amazmod app disconnects on Huawei 10

### ISSUE THREAD

**Issue by psomlyai** [AmazMod/AmazMod#905]
Dear All,

I'm using a Stratos (Pace 2) and installed Amazmod 1912 on it. On the phone I installed the latest 1.2.1 from the AppStore. I followed the instructions enabled only Amazmod notifications and disabled the Amazmod ones. Still most of the time I get the "connect without service" message on the phone, which is a Huawei 10. I un- and reinstalled both apk and app on both device to no avail. I restarted them both. Still nothing...I spent hours to figure it out, but no luck. And then sometimes the app suddenly connects for a short time. The watch app works fine, it's just the phone app, which gives me some hard time...It is really confusing, however I understand there could be various reasons for it. 
Any advice!?

I appreciate all help...:)

Regards,

Peter

![Screenshot_20200613_023602_com edotassi amazmod 1](https://user-images.githubusercontent.com/66854775/84557115-36e8b300-ad20-11ea-8f53-dda9259dc2fe.jpg)
![Screenshot_20200613_023241_com edotassi amazmod 1](https://user-images.githubusercontent.com/66854775/84556998-1ff59100-ad1f-11ea-8b5a-6137cbd0bb0d.jpg)
![Screenshot_20200613_023252_com edotassi amazmod 1](https://user-images.githubusercontent.com/66854775/84557021-60eda580-ad1f-11ea-873a-b2baf9cf4944.jpg)

**Comment by 1immortal** [comment]
Hi,

Please follow these steps on your phone for both Amazfit and AmazMod apps:
https://dontkillmyapp.com/huawei

**Comment by psomlyai** [comment]
Thanks Immortal. I tried the recommended above to no avail. I guess my phone is quite a stubborn one...:)

**Comment by 1immortal** [comment]
have you tried to uninstall the AmazMod service from your watch and try to install it back?

**Comment by psomlyai** [comment]
Yap. I did...Again to no avail... I guess I'm just gonna use Amazmod on the watch and ignore the phone app.

**Comment by psomlyai** [comment]
I think I got it people!!! After hours meditating on it...My watch keeps disconnecting from the WiFi. If I want to "be connected" to the phone app, I need to have the WiFi connected on my watch. And then voila!!!

**Comment by 1immortal** [comment]
seems like the OP fixed it, good job :)
