### ISSUE TITLE
Google Assistant support

### ISSUE THREAD

**Issue by srijansaxena11** [AmazMod/AmazMod#913]
Is it possible to get Google Assistant support on Amazfit Verge (and others possibly) instead of Alexa or alongwith it? I have seen people trying to push Google Assistant APK and it does not work.

**Comment by 1immortal** [comment]
Google assistant will probably work with a full google framework, something that is impossible to run on the crippled MIPS devices that uses Android 5.1.1 on our watches, so ...
unless there will be a way to run full wear OS on Amazfit devices, you can simply forget it.
The only device that might somehow be able to somehow run something that is similar to that is the NEXO watch, and nobody wants to deal with it, its a diabolic device originated in Mordor, made by demons and bats, with integrated 5G antenna in it.
