### ISSUE TITLE
Camera remote doesn't work on miui when amazmod is in the background

### ISSUE THREAD

**Issue by DanMcz** [AmazMod/AmazMod#928]
I really love the idea of having a camera remote on my wrist, I missed it a lot when changed from garmin.
At that time I used it with garmin app that sent a notification, which was the trigger for tasker to send volume up press, and worked perfectly on miui. 

However, the current implentation in amazmod only send volume up when I'm in the amazmod app, and does nothing anywhere else, for example in camera apps. 
Can you please fix it? 
If needed, I can send logs.

Edit: I allowed autostart for amazmod, gave all the permissions, and removed miui battery optimizations. Miui also can't be the exact problem, because tasker did the same without any further tweaking.
If you could manage to implement tasker the same way (by sending a notification). that would be also good for me.

Thanks in advance!

**Comment by 1immortal** [comment]
Hi,

This feature is still very experimental, that's why it's on the edgy only.
please provide logs for additional investigation, but it's not ready yet :(

**Comment by fcaronte** [comment]
The Easy trick to send volume up button seem to can't be use out of app (android limitations) so as now this feature isn't work for everyone

**Comment by DanMcz** [comment]
I believe it can be done using accessibility services plugin, but sure not an easy trick to do.
I will search further and provide logs when I got home... 

But till then I believe it would be way easier to do the tasker implementation, you would only need to crwate a button that generates a notificatuon on the phone, and the rest could be done the garmin way abd could also trigger the camera shutter. 
Thanks for your work anyway:)

**Comment by DanMcz** [comment]
> The Easy trick to send volume up button seem to can't be use out of app (android limitations) so as now this feature isn't work for everyone

I believe it can be done using accessibility services plugin, but sure not an easy trick to do.
I will search further and provide logs when I got home...

But till then I believe it would be way easier to do the tasker implementation, you would only need to crwate a button that generates a notificatuon on the phone, and the rest could be done the garmin way abd could also trigger the camera shutter.
Thanks for your work anyway:)

**Comment by DanMcz** [comment]
I made a logcat, here's it: https://drive.google.com/file/d/1B2_SLdyqrEx0PMXFZFA2dYdhF_EVr8JA/view?usp=drivesdk

**Comment by 1immortal** [comment]
Hi,

This functionality is moved to backlog and will be handled if/when active development of AmazMod will get back.
Thanks for your input.
