### ISSUE TITLE
Service v1914 battery drain

### ISSUE THREAD

**Issue by H3R371C** [AmazMod/AmazMod#935]
High battery drain (over 15% per hour) after service update to 1914 on Stratos 2.3.12.1. After rolling back to 1913 normal battery consumption resumes @~1% per hour.

**Comment by diotto** [comment]
Hi, did you made a reboot after installing 1914?
Huami devices have a bug in adb which causes battery drain sometimes after
a package is installed.
I'm using 1914 daily and found no problem. Thanks

Em sáb, 26 de set de 2020 08:45, H3R371C <notifications@github.com>
escreveu:

**Comment by H3R371C** [comment]
It drained to 0% overnight twice. It counts as a reboot, right? No unusual drain after rolling back to 1913, so I guess the watch is fine and not a problem.

**Comment by 1immortal** [comment]
please remove the service and have it installed again. on some rare occasions this happens.

**Comment by H3R371C** [comment]
The problem is in Sleep As Android integration. It drains battery overnight and sometimes it doesn't stop draining even after reset. After deactivating this option, drain stops. By the way, have to deactivate in both the AmazMod and Sleep As Android. It somehow still works even if it is only active in Sleep As Android.

**Comment by 1immortal** [comment]
that's why this option is disabled by default. SAA integration is in a very experimental state and is not recommended to work with.
