### ISSUE TITLE
"No service found" in main screen, even when I have the service installed and running

### ISSUE THREAD

**Issue by gonzalofarias** [AmazMod/AmazMod#936]
Watch: Amazfit Verge
Rom version: 3.2.7.5
Phone: Xiaomi Redmi Note 5 Pro
Amazmod Version: 1.2.3
Service version: 1914
Admin privileges for service is ON.
Widget added to watch's screen.

It's a hit or miss, sometimes it does display the heart rate chart and the service version correctly, but most of the times it just says "No service found". 

Is there anything else I should do to make sure it always stays connected?

**Comment by 1immortal** [comment]
Hi,

are there any connectivity issues with the Zepp stock app?
you need to lock both Zepp and AmazMod apps in the memory for proper functionality.

**Comment by gonzalofarias** [comment]
Hi,

no, there are no problems connecting with Zepp. Every time I open the app it synchronizes perfectly. I have both apps (Zepp and Amazmod) excluded from battery saving too.

**Comment by fcaronte** [comment]
Can you check if maybe you install phone  + service apk on verge too? You need to keep only 1914 service version
