### ISSUE TITLE
Amazmod crash once trying enter to setting

### ISSUE THREAD

**Issue by arikhaz** [AmazMod/AmazMod#939]
I install Amazmod - 1.2.3 build 231 on xiaomi 9. 
Once trying to enter setting or special settings the application crash . Any idea why it happened? 
and how can i fix it so i will able to connect my stratos 3 watch .... 

thanks

**Comment by seyar-parleypro** [comment]
Same behaviour on honor 9, android 9. Watch also stratos 3 with no service installed on it

**Comment by 1immortal** [comment]
should be fixed on the latest dev, please try to install a new build in few more days
