### ISSUE TITLE
Amazmod fails to connect with 'amazfit bip u'.. null in 'adb device listing usb connection

### ISSUE THREAD

**Issue by kingdj** [AmazMod/AmazMod#940]
Hey I tried to install amazmod to 'amazfit bip u' smartwatch but the device didn't appeared in 'adb devices' while it was connected via USB.

Could you pls help me here.
& How to unable debugging in smartwatch connected via USB.
The mobile app crashes while clicking on settings & services doesn't even start. The anazfit app even fails to connect with smartwatch.

**Comment by GreatApo** [comment]
Amazfit bip u doesn't run android, you can't install anything on it.

**Comment by kingdj** [comment]
Okay thanks for the reply.
But can't we install Python based programming.
