### ISSUE TITLE
Amazmod does not update from 1912 to 1914 on Stratos 3

### ISSUE THREAD

**Issue by bonjour81** [AmazMod/AmazMod#941]
Hi there!

I have setup Amazmod 1912 some time ago on my Stratos3.
When opening Amazmod android app, a pop-up offers to upgrade to 1914.
It seems to upload something to the watch ( 17MB, at a few kb/s, take around 1h! ) and then nothing happens.
Amazmod stays in 1912 (next time I open app phone, it will ask again).

Did I missed something for the upgrade ?
Is it expected that the upload is so slow (  ~ 5kb/s ) ?  (watch is ~30cm far from phone).

I can also upgrade by USB, but I was not sure if I shall follow exact same steps as for a fresh install.

Regards,

**Comment by 1immortal** [comment]
Hi,

please remove the service and install the new version manually from your PC.
