### ISSUE TITLE
Won't connect to my Amazfit Band5

### ISSUE THREAD

**Issue by chirag-p** [AmazMod/AmazMod#943]
AmazMod is required to use my Amazfit band 5 with Sleep As Android app. My watch connects with the Zepp app and AmazFit Tools. To be able to use sleep tracking on Sleep as Android, I need to connect my watch using AmazMod. It will not connect. 

It asks me to instanll apk and let it "send to watch". I follow the steps and file uploader cannot send it to my watch. 

Below is the message I get: 

**Success!**
File: Amazmod-service-1914.apk
Result: something goes wrong

FYI. I checked with Sleep as Android and Amazfit Tools to see if my Amazfit band 5 is compatible for Sleep as Android and it is compatible. 

Also the app also crashes on my phone when I click on settings. I have a samsung galaxy s20+

Please help with this issue.

**Comment by fcaronte** [comment]
Amazfit Band use a closed os and so you can't install Amazmod
