### ISSUE TITLE
installation of 1914 Apk on Amazfit Bip S

### ISSUE THREAD

**Issue by wvhulle** [AmazMod/AmazMod#945]
In the installation instructions on the start page of this project, there is no extra information on how to install the apk on the Bip S.
The adb server on windows 10 in the installation wizard does not recognize the device. 

Do I need to install a driver first?
````
error: device '(null)' not found
- waiting for device -

**Comment by fcaronte** [comment]
Bip S use an closed os and do you can't install Amazmod

**Comment by leao-nardo** [comment]
im getting the same error in verge with os 3.2.7.5 . is it locked too ?

**Comment by 1immortal** [comment]
no, try to verify your ADB drivers and that your watch can be detected by your PC
