### ISSUE TITLE
HRV with SleepAsAndroid? 

### ISSUE THREAD

**Issue by RubenKelevra** [AmazMod/AmazMod#946]
I've read about an beta integration of sleep as android with my Amazefit Pace.

I was wondering if this includes or will include in the future the new HRV feature of SleepAsAndroid:

https://sleep.urbandroid.org/hrv-tracking/

Would be pretty dope to not have to buy and wear an additional device which does basically the same thing just for this one measurement. 😬

Thanks in advance for looking into this!

**Comment by 1immortal** [comment]
this implementation was made some 2 years ago into SAA, please check it with them.
note that it will drain your watch to death during the night, and you will probably wake up with a flat battery.
As of AM - it's as dead as can be, you can try to with with the latest released build for tests.
