### ISSUE TITLE
the installer says "error: device '(null)' not found". 

### ISSUE THREAD

**Issue by kolegaa** [AmazMod/AmazMod#947]
[
![image](https://user-images.githubusercontent.com/78544828/111750680-cf095f00-8893-11eb-8f28-f697dc11192a.png)
](url)
my device is the amazfit verge###

**Comment by fcaronte** [comment]
Verge Is known to have a bad dock charger and so you need to connect better (try to keep pressed the upper part) or change usb port and try again.

**Comment by kolegaa** [comment]
i tried it on another computer and it worked, and i dont know how to close this so i just left this the way it was
