### ISSUE TITLE
[feature request] put sound input to reply WhatsApp 

### ISSUE THREAD

**Issue by leao-nardo** [AmazMod/AmazMod#950]
now theres the yes , no and 'custom' options to answer zap msg.
but as verge have mic we could send voice reply . that would be awesome.

i would love to help in implementing that but im quite newbie. if any experienced dev could coach/ mentor like in code dojosi could even try.

**Comment by 1immortal** [comment]
few attempts have been made before, impossible with the cripple mic implementation on PACE/Verge models.

**Comment by leao-nardo** [comment]
"cripple mic implementation" how exactly  ? can you put links where its talked / explained that ?
